### PR TITLE
Pickers: Fix so controlled pickers will only focus when it has focus

### LINKED ISSUE #7543: TagPicker: suggestion list is shown strangely
### Environment Information 
- __Package version(s)__: 6.119.0

If I set both value 
...
onEmptyInputFocus={() => _testTags}
selectedItems={[_testTags[0]]}
...

#### Actual behavior:
The suggestion list will auto show when I check then uncheck the checkbox **Disable Tag Picker**
 
#### Expected behavior:
Only show suggestion list when we focus on picker.

### PR DESCRIPTION
**Pull request by joschect**
…focus

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #7543
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

Fix it so the controlled picker will only focus when it has focus. This ensures that it won't steal focus whenever it gets new props.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -118,9 +118,13 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
           items: newProps.selectedItems
         },
         () => {
-          // Need to reset focus in the same that way that we do if an item is selected by a non-controlled component
-          // See _onSelectedItemsUpdated.
-          this.resetFocus(focusIndex);
+          // Only update the focus if this component is currently focused. If the items are managed by another component,
```
Comment (Vitalius1) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: The second sentence confused me a little... 

> If the items are managed by another component, then that component should control focus

Is this also documented elsewhere rather than just having this internal comment? Do we even need to this second part of the comment?

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: We might not need it. I mainly put it there as an explanation. I'll make that more clear since it's really that we don't want it stealing focus when it shouldn't.

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Fixed
