### PR TITLE
Pickers: bring pickers in line with W3 ARIA 1.1 specs

### LINKED ISSUE #10702: Narrator does not read the error message displayed while we enter incorrect email address.
Environment Details: 
Application Name: Customer Service Insights
Windows Version: Windows10
Browser Versions: Microsoft Edge 44.18362.267.0
Screen Reader Version: Narrator
Mas violated : MAS 3.3.1

Repro Steps:
1. Open application Customer Service Insights.​
2. Home page should open for Customer Service Insights.​
3. Navigate to Global Navigation Bar at the top of the screen and select "Workspaces Panel".​
4. Delete any workspace by hitting "Share" button on any workspace. "Share this workspace" popup screen should appear.​
5. Select "Share" tab item.​
6. Verify that all the elements of "Share Workspace-Share" are accessible and MAS Compliant.

Actual:
 Narrator does not read the error message displayed while we enter incorrect email address.

Expected:
Narrator should read the error message displayed while we enter the incorrect email address.

User Impact:
The screen reader users will not understand the entered email is wrong as narrator does not announce the error message.

### LINKED ISSUE #10820: [Accessibility][Programmatic access]: ARIA attributes must conform to valid values (Bug 1)
Breakout of issue #8655

### LINKED ISSUE #10823: [Accessibility][Usable]: Screen reader is not providing information about no suggestion appearing on screen when user provide inappropriate entry in edit field . (Bug 4)
Breakout of issue #8655

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [x] Addresses an existing issue:
 - Fixes #10702
 - Fixes #10820 
 - Fixes #10823 
- [x] Include a change request file using `$ yarn change`

#### Description of changes
Pickers: bring pickers in line with w3 1.1 specs

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10872)

### CODE REVIEW

**Comment by khmakoto** [comment]
@joschect seems like you need to update snapshots.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -958,7 +963,13 @@ export class BasePickerListBelow<T, P extends IBasePickerProps<T>> extends BaseP
       <div ref={this.root} onBlur={this.onBlur}>
         <div className={classNames.root} onKeyDown={this.onKeyDown}>
           {this.getSuggestionsAlert(classNames.screenReaderText)}
-          <div className={classNames.text}>
+          <div
+            className={classNames.text}
+            aria-owns={suggestionsAvailable || undefined}
+            aria-expanded={!!this.state.suggestionsVisible}
+            aria-haspopup="true"
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Why is this `true` here instead of `listbox/dialog` like before?

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Good catch
