### PR TITLE
ComboBox: fix for issue resetting suggestedDisplayValue

### LINKED ISSUE #9965: ComboBox: suggestedDisplayValue property of comboBoxState is not getting reset on clearing selectedKeys
#### Actual behavior:
I'm trying this code where formValidator.form.profile.value is a state and getting reset on click of a button.

Current Issue. When i'm trying to select value of comboBox using key board it is setting suggestedDisplayValue. But even if i'm clearing selectedKey to null it is not resetting suggestedDisplayValue and in turn text getting displayed in comboBox
`<ComboBox
    label="profile?"
    onChange={onComboBoxChange}
    options={profiles}
    required
    selectedKey={formValidator.form.profile.value}
/>` 
#### Expected behavior:
 It should clearComboBox if selectedKey gets reset

#### Priorities and help requested:

 Requested priority: (Blocking, High, Normal, Low)  High
 
Products/sites affected: Yes

### PR DESCRIPTION
**Pull request by marygans**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9965
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

When a user clicks the combobox dropdown, closes it by clicking outside of the dropdown, and clears the content of the combobox, suggestedDisplayValue is reset. 

**Before:** 
before-01

**After:** 
after-01

_(React state in DOM now updates here)_
after-02

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10102)

### CODE REVIEW

**Comment by marygans** [comment]
@joschect or @jspurlin  any thoughts/feedback on this?

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -231,7 +231,8 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
 
       this.setState({
         selectedIndices: indices,
-        currentOptions: newProps.options
+        currentOptions: newProps.options,
+        suggestedDisplayValue: undefined
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: I think that we should only do this if null is passed in. Otherwise the suggested value should be whatever it would be normally.

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: I don't follow totally. null is passed in to what?

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Read the issue. Updated the code to get this going.

**Comment by marygans** [comment]
> @marygans Can you add some more technical detail about what the issue was, the fix you put in place (and why), and the validation you did to make sure this fix is good?
> 
> Also, are there any unit tests that could be added to make sure the behavior is correct and doesn't accidentally regress in the future?

Missed this and will get it resolved today 👍 
Technical details for this fix is addressing the scenario of when a user would like to reset the values on a page, this suggestedValue state remains and never cleared. This fix now allows the value to be cleared when resetting values on the page.

**Comment by marygans** [comment]
@joschect how does this look?
