### PR TITLE
SpinButton: Making disabled SpinButtons non-focusable

### LINKED ISSUE #11766: SpinButton is still focusable after being disabled
### Environment Information

- **Package version(s)**: 6.210.5
- **Browser and OS versions**: All browsers, all OSs

### Please provide a reproduction of the bug in a codepen:
Repro steps.
1. Open https://codepen.io/ArturoCalderon/pen/ExarybR
2. Switch to the bottom section and press TAB

#### Actual behavior:
Disabled SpinButton component is still focusable by keyboard.

#### Expected behavior:
Disabled SpinButton component should no longer be focusable by keyboard, as stated in here: https://github.com/OfficeDev/office-ui-fabric-react/issues/4387

### Priorities and help requested:
Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: [Microsoft Project for the Web](project.microsoft.com/)

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11766
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Disabled `SpinButtons` were still focusable which is a pattern we used in the past but have stepped away from. This PR makes the component non-focusable when it's disabled.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11783)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 1]
```diff
@@ -211,8 +211,9 @@ export class SpinButton extends React.Component<ISpinButtonProps, ISpinButtonSta
                 onFocus={this._onFocus}
                 onKeyDown={this._handleKeyDown}
                 onKeyUp={this._handleKeyUp}
-                readOnly={disabled}
+                disabled={disabled}
                 aria-disabled={disabled}
+                readOnly={disabled}
```
Comment (xugao) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: can remove `readOnly`

**Comment by khmakoto** [comment]
@xugao I removed `readOnly`. Btw, could you merge the PR? Aneesha is on vacation so she won't be able to review it and I don't have admin privileges.
