### PR TITLE
Replacing 'office-ui-fabric-react/lib/Styling' with '@uifabric/styling'

### LINKED ISSUE #7374: @fabricui/fluent-theme SSR issues
Using fluent-theme will throw errors on using something like nextJS. I know I can import from lib-commonjs, but even those commonjs packages will import stuff like `office-ui-fabric-react/lib/Styling` which in turn uses es modules (instead of referencing `office-ui-fabric-react/lib-commonjs/Styling`).

There is more problems like `document undefined` due to `@microsoft/load-themed-styles/lib/index` `registerStyles` not checking if document is defined.

I could go and create the stack traces and detailed error messages, but I guess that the new fluent-theme is still in preview and this has not yet been optimized.

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7374
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Replacing references to `office-ui-fabric-react/lib/Styling` with references to `@uifabric/styling` in `fluent-theme` package.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/example-app-base/src/components/templates/PageImageSet.tsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import * as React from 'react';
 import { BaseComponent, IBaseProps, IClassNames, customizable } from 'office-ui-fabric-react/lib/Utilities';
```
Comment (Vitalius1) [inline packages/example-app-base/src/components/templates/PageImageSet.tsx]: Just out of curiosity... is this an issue only with the Styling import?

Comment (khmakoto) [reply packages/example-app-base/src/components/templates/PageImageSet.tsx]: I don't think it is an issue only with the styling import, but we need to take a deeper look at each case before moving forward.

File: packages/fluent-theme/src/fluent/styles/Dialog.styles.ts [hunk 2]
```diff
@@ -4,7 +4,7 @@ import {
   IDialogFooterStyleProps,
   IDialogFooterStyles
 } from 'office-ui-fabric-react/lib/Dialog';
```
Comment (kenotron) [inline packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: Problem runs very deep here - the problem is that we have all of these imports from OUFR/lib/components
@Vitalius1 - maybe you can take a crack at address this?
@dzearing - should OUFR itself be a dependency for fluent-theme at all?

**Comment by khmakoto** [comment]
@dzearing and @kenotron I've changed this PR so it only tackles the imports specifically in the `fluent-theme` package as discussed in the original issue #7374.

File: packages/fluent-theme/src/fluent/styles/Dialog.styles.ts (hunk 2 above)
Comment (JasonGore) [reply packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: I don't see how to get around having OUFR as a dependency for theming packages. These styles are targeting specific component props and styles and need component typings.

Comment (kenotron) [reply packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: If that is the case, then we are actually implying that by using fluent theme, then you cannot do SSR. That's a TERRIBLE trade off.

Comment (JasonGore) [reply packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: To be clear, I wasn't commenting on HOW this is imported (as I'm not sure the options here), but only that theming packages will need component typings unless we forego all type safety (or making a typings package?)

Comment (kenotron) [reply packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: Other hacks one can do would be to rewrite "require" like with "rewire" package or something... REALLY seems extreme to me.

Comment (cliffkoh) [reply packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: When I spoke to @dzearing about this, he opted to optimize for AMD consumers (given that we know of major partners on AMD consuming Fabric) over CommonJS consumers...

For CommonJS consumers, I think David recommended they do some workaround since we can't solve it for both AMD/CommonJS at the same time. One possible workaround I can think of is that they would just have to use something like babel/TS to transpile the ESM into CJS.

Comment (cliffkoh) [reply packages/fluent-theme/src/fluent/styles/Dialog.styles.ts]: And.. yeah, this inconsistency in our imports is a bit of a mess (including how we special optimize for AMD). From @dzearing's POV, the long term fix is to investigate breaking apart the OUFR package (i.e. each component is its own package import).

**Comment by khmakoto** [comment]
Thanks for the approval @cliffkoh. I'm just putting the `Do Not Merge` label so that this doesn't get squashed before David can take another look at it.

Thanks.

**Comment by cliffkoh** [comment]
Ping @dzearing, @khmakoto is awaiting your review to merge.
