### PR TITLE
Fixed controlled TextField with multiline and autoAdjustHeight does not adjust when setting value via state

### LINKED ISSUE #3941: Controlled TextField with multiline and autoAdjustHeight does not adjust when setting value via state
### Bug Report

- __Package version(s)__: Latest

Are you willing to submit a PR to fix? Yes

#### Describe the issue:

When using a TextField as a controlled component (where the `value` prop has been set to a state variable) with multiline and autoAdjustHeight enabled, the height does not automatically adjust when the `value` state variable changes.

The height only updates once the user manually enters text in the field.

### If applicable, please provide a codepen repro:

https://codepen.io/nero120/pen/LQWMOe

### PR DESCRIPTION
**Pull request by nero120**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3941
- [ ] Include a change request file using `$ npm run change` (reports No change file is needed)

#### Description of changes

Updated TextField component so that _adjustInputHeight is called when value is changed via prop update. This ensures the height is adjusted when value updates for a controlled TextField (with multiline and autoAdjustHeight true).

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -116,7 +116,10 @@ export class TextField extends BaseComponent<ITextFieldProps, ITextFieldState> i
       this.setState({
         value: newProps.value,
         errorMessage: ''
-      } as ITextFieldState);
+      } as ITextFieldState,
+        () => {
+          this._adjustInputHeight();
```
Comment (manishgarg1) [inline packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: >_adjustInputHeight [](start = 15, length = 18)

Can you please add a change file with "patch" for textfield

Comment (manishgarg1) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: run "npm run change" from the root

---
In reply to: [167708512](https://github.com/OfficeDev/office-ui-fabric-react/pull/3942#discussion_r167708512) [](ancestors = 167708512)

Comment (nero120) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: @manishgarg1 when I run that command it prints the following:

```
Starting "rush change"

Target branch is origin/master
No change file is needed.
```

What should I do?

Comment (erichdev) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: @nero120  Try `npm run change -- -b upstream/master` (rush is comparing your changes to master, but since your changes were committed to your master branch, this will compare it to Fabric's master)

Comment (nero120) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: @erichdev nope:

```
ERROR: Command failed: git diff upstream/master... --dirstat=files,0
       fatal: ambiguous argument 'upstream/master...': unknown revision or path not in the working tree.
       Use '--' to separate paths from revisions, like this:
       'git <command> [<revision>...] -- [<file>...]'
```

I confess to not understanding why this doesn't 'just work', I haven't done anything particularly unique here - doesn't everyone submit a pull request from their fork's master branch?

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: "upstream" is a remote name. Do you have a git remote pointing to officedev? You can add it like so:

```bash
git remote add upstream https://github.com/OfficeDev/office-ui-fabric-react.git
```

Comment (nero120) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: Thanks @dzearing, but after running your command then `npm run change -- -b upstream/master` I get the error:

```
Starting "rush change"

Target branch is upstream/master
fatal: ambiguous argument 'upstream/master...': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

Is there some other way I can create this file or can you accept the pull request without it?
