### PR TITLE
Cancel should set timeoutId to null

### LINKED ISSUE #3781: async.debounce.cancel() results in further calls not being fired
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

When calling cancel on a debounced function, future calls to the debounced function are never queued.
This is because timeoutId is not cleared on the cancel call

### PR DESCRIPTION
**Pull request by abettadapur**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3781 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
* Create a markExecuted function, which clears timeout and sets timeoutId to null
* Cancel, flush, and invoke now call this markExecuted function

### CODE REVIEW

File: packages/utilities/src/Async.ts [hunk 1]
```diff
@@ -400,25 +404,25 @@ export class Async {
...
+    let pending = (): boolean => {
+      return !!timeoutId;
+    };
+
     let cancel = (): void => {
-      if (timeoutId) {
-        this.clearTimeout(timeoutId);
+      if (pending()) {
+        // Mark the debounced function as having executed
+        markExecuted(new Date().getTime());
```
Comment (cschleiden) [inline packages/utilities/src/Async.ts]: If I cancel before it was ever executed should we still do that?
