### PR TITLE
Prevent TooltipHost from mutating calloutProps property.

### LINKED ISSUE #4715: TooltipHost and ChoiceGroup components mutate props
### Bug Report

- __Package version(s)__: 5.92.00
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Describe the issue:

TooltipHost mutates calloutProps object before passing it to Tooltip as a prop.

#### Actual behavior:

TooltipHost mutates calloutProps with assign() call when used as prop for Tooltip.

```
            calloutProps={ assign(calloutProps, {
              onMouseEnter: this._onTooltipMouseEnter,
              onMouseLeave: this._onTooltipMouseLeave
            }) }
```

#### Expected behavior:

TooltipHost should not mutate external prop object. It should create a new object if it wants to change it before passing it to Tooltip.

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #4715 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fix object mutation in TooltipHost.

#### Focus areas to test

N/A

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.tsx [hunk 1]
```diff
@@ -82,10 +82,11 @@ export class TooltipHost extends BaseComponent<ITooltipHostProps, ITooltipHostSt
             targetElement={ this._getTargetElement() }
             directionalHint={ directionalHint }
             directionalHintForRTL={ directionalHintForRTL }
-            calloutProps={ assign(calloutProps, {
-              onMouseEnter: this._onTooltipMouseEnter,
-              onMouseLeave: this._onTooltipMouseLeave
-            }) }
+            calloutProps={ assign({},
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Tooltip/TooltipHost.tsx]: much better..... the other option is to use spreads (that seems a bit more in vogue these days)
