### PR TITLE
Ios scroll fix

### LINKED ISSUE #6315: scrolling not possible inside Modal with iOS
### Please provide a reproduction of the bug in a codepen:
 

https://codepen.io/anon/pen/wEmwXJ

### Bug Report 
 
 
- __Package version(s)__: 6.67.2
- __Browser and OS versions__: iOS 11.4.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:
 
With the current fabric version it is not possible to have a custom scrolling area inside the Modal component. The scrolling doesn't work in iOS safari (in other browsers its working).
With fabric 6.52.0 it is still working. 
broken version: https://codepen.io/anon/pen/wEmwXJ 
working version: https://codepen.io/anon/pen/zJRgyP
 
#### Actual behavior:
 
Scrolling not possible.
 
#### Expected behavior:
 
Scrolling should be possible.

### PR DESCRIPTION
**Pull request by kkjeer**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6315 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Before this fix, custom scrolling inside a Modal component was not scrollable on iOS Safari. The reason was in the `_preventOverscrolling` function in scroll.ts - the _element variable used to detect scrolling events was the "scrollableContent" element rather than the child element within the Modal. Since the scrollableContent element has an equal scrollHeight and clientHeight if custom scrolling is used, `_preventOverscrolling` calculated that the element had been scrolled to the bottom and prevented further scrolling. This change calls `findScrollableParent` on the event target to get the correct element to perform calculations on.

Examples of custom scrolling with Modals with this fix (using mobile device simulator on Chrome):

Basic custom scrolling (fixed header, cyan scrollable area):
modal-custom-scrolling

Nested custom scrolling (fixed header, cyan scrollable area with yellow scrollable children):
modal-nested-scrolling

#### Question for discussion: should the "scrollableContent" div have `data-is-scrollable=true` set?
Calling `findScrollableParent` is more performant if scrollable divs have the `data-is-scrollable` attribute since it avoids expensive `getComputedStyle` calls. However, in a scenario such as the custom Modal scrolling examples above, where the scrollableContent div has a scrollable child that does not have `data-is-scrollable` set, then scrollableContent will be returned as the scrollable parent, and its child div will not be scrollable.

Possible options here:
1. Do not set `data-is-scrollable` on the scrollableContent.
a. Pros: If the user has scrollable divs inside scrollableContent, they will be correctly identified as the scrollable element even if they do not have the `data-is-scrollable` attribute.
b. Cons: If the user does not have any custom scrollable divs inside scrollableContent, unnecessary expensive `getComputedStyle` calls will be made in order to determine that scrollableContent is the scrollable div.
2. Set `data-is-scrollable` on the scrollableContent (current approach - updated after offline discussion).
a. This would require the user to set `data-is-scrollable` on any custom scrollable children of scrollableContent.
3. Allow the user to set the `data-is-scrollable` attribute on scrollableContent via a Modal prop.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/utilities/src/EventGroup.ts [hunk 1]
```diff
@@ -200,7 +200,7 @@ export class EventGroup {
         eventName: eventName,
         parent: parent,
         callback: callback,
-        useCapture: useCapture || false
+        useCapture: options !== undefined && typeof options === 'boolean'
```
Comment (dzearing) [inline packages/utilities/src/EventGroup.ts]: Take a look at `removeEventListener` down below in this file. It ends up passing in useCapture from the record.

I think you should change this useCapture to just `options` and cache options. The purpose of having this in the record is so that we pass the same thing back into `removeEventListener`.
