### PR TITLE
Merge-Styles: Infer types of subComponentStyles in IProcessedStyleSet

### LINKED ISSUE #6060: [merge-styles] Processed style sets' subcomponent properties cannot be passed as styles prop due to type mismatch.
### Please provide a reproduction of the bug in a codepen:
 
Codepen doesn't provide TS typechecking, so here's a reproduction repository: https://github.com/Nimelrian/OfficeFabric-SubComponentStyles-bug

Just clone it, run yarn / npm install and either compile it using yarn / npm build or open it in VS Code. App.tsx shows the typing error.

### Bug Report 
 
 
- __Package version(s)__:
  - @uifabric/merge-styles: 6.7.0
  - office-ui-fabric-react: 6.53.0
  - typescript: 3.0.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: (Blocking, High, Normal, Low): High, as it renders subComponentStyles useless
 
#### Describe the issue:
 
The helper type `IProcessedStyleSet` maps all properties of a `Styles` interface's `subComponentStyles` to `IStyleFunction<any, IStyleSet<any>>`. This causes type mismatches when trying to pass these to other components via the `styles` prop.

#### Behavior prerequisites:
The following code is given:
```ts
interface IStyles {
  root: IStyle
  subComponentStyles: {
    choiceGroup: IStyleFunctionOrObject<IChoiceGroupStyleProps, IChoiceGroupStyles>;
  }
}

const getStyles = (): Partial<IStyles> => ({
  root: {
    background: "red"
  },
  subComponentStyles: {
    choiceGroup: {
      root: {
        background: "green"
      }
    }
  }
})

const getClassNames = classNamesFunction<{}, IStyles>();

class App extends React.Component {
  public render() {
    const classNames = getClassNames(getStyles);
    return (
      <div className={classNames.root}>
        <ChoiceGroup
          options={[{ key: "1", text: "1" }, { key: "2", text: "2" }]}
          styles={classNames.subComponentStyles.choiceGroup}
        />
      </div>
    );
  }
}
```

#### Actual behavior:
 
A typing error occurs at the `styles` prop of `ChoiceGroup`:
```
Type 'IStyleFunction<any, IStyleSet<any>>' is not assignable to type 'IStyleFunction<IChoiceGroupStyleProps, IChoiceGroupStyles> | Partial<IChoiceGroupStyles> | undefined'.
  Type 'IStyleFunction<any, IStyleSet<any>>' is not assignable to type 'IStyleFunction<IChoiceGroupStyleProps, IChoiceGroupStyles>'.
    Type 'Partial<IStyleSet<any>>' has no properties in common with type 'Partial<IChoiceGroupStyles>'.
```
 
#### Expected behavior:
 
No typing errors occur.

#### Proposal:
Change the typing of IProcessedStyleSet to automatically infer the types of the StyleFunctions. I'll create a PR for this and refer this issue from there.

### PR DESCRIPTION
**Pull request by Nimelrian**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6060 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Previously, `IProcessedStyleSet` just mapped the properties of `subComponentStyles` to `IStyleFunction<any, any>`. This caused typing issues when trying to pass the processed styles to sub components. I have added an additional helper type `TrimToFunction` which takes a type as parameter and discards all non-function types from that type. In other words, passing a `IStyleFunctionOrObject<Foo, Bar>` to it returns a `IStyleFunction<Foo, Bar>`.

#### Focus areas to test

I tested this in my local project by using TypeScript's module augmentation to overwrite the merge-styles typings with my fix. I didn't notice any issues and was able to pass the processed `subComponentStyles` to a ChoiceGroup, which wasn't possible before.

### CODE REVIEW

File: packages/merge-styles/src/IStyleSet.ts [hunk 1]
```diff
@@ -6,6 +6,8 @@ export type Diff<T extends keyof any, U extends keyof any> = ({ [P in T]: P } &
 
 export type Omit<U, K extends keyof U> = Pick<U, Diff<keyof U, K>>;
 
+export type TrimToFunction<T> = T extends (...args: any[]) => any ? T : never;
```
Comment (cliffkoh) [inline packages/merge-styles/src/IStyleSet.ts]: I love this but we have intentionally been trying to avoid using "hard" TS 2.8 features, which is part of the reason why we aren't still yet on Typescript 3 and we have some unideal typings in here. 

Let me talk to the team to see if we can get this in.

Comment (cliffkoh) [inline packages/merge-styles/src/IStyleSet.ts]: I'm a little puzzled by the `never`.

If someone were to define an interface `IStyles` as follows:
```ts
interface IStyles extends IStyleSet<IStyles> {
  root: IStyle;
  subComponentStyles: {
    choiceGroup: Partial<IChoiceGroupStyles>
  };
}
```
This technically is a valid IStyleSet as it represents the "object" portion.

But the conditional would then expectedly reduce it to a never... (e.g. below for classNames.subcomponentStyles.choicegroup)

```ts

const getStyles = (): Partial<IStyles> => ({
  root: {
    background: "red"
  },
  subComponentStyles: {
    choiceGroup: {
      root: {
        background: "green"
      }
    }
  }
});

const getClassNames = classNamesFunction<{}, IStyles>();

class App extends React.Component {
  public render() {
    const classNames = getClassNames(getStyles);
    return (
      <div className={classNames.root}>
        <ChoiceGroup
          options={[{ key: "1", text: "1" }, { key: "2", text: "2" }]}
          styles={classNames.subComponentStyles.choiceGroup}
        />
      </div>
    );
  }
}
```

Amazingly, there are no TS errors. The compiler accepted `never` to be assigned to styles, and the styles prop now has type `never`.

Comment (cliffkoh) [reply packages/merge-styles/src/IStyleSet.ts]: The right thing is probably
`export type InferredStyleFunction<T> = T extends (...args: any[]) => any ? T : () => T; `

**Comment by Nimelrian** [comment]
The screener fail seems strange. The last commit by me should not have any effect on the visual outcome. Must be a change made to the master branch which I merged.

**Comment by micahgodbolt** [comment]
I've seen the same screener failures elsewhere....its not you

**Comment by cliffkoh** [comment]
@dzearing can you approve the conditional type usage?
