### PR TITLE
TextField: Fix value clearing on render when value prop is undefined

### LINKED ISSUE #5146: [bug] - Textfield not empty if value undefined
### Bug Report
Package version(s): 5.107.0
### Priorities and help requested (not applicable if asking question):
Requested priority: Normal

#### Describe the issue:
render gets not triggered when value changes to undefined

https://github.com/OfficeDev/office-ui-fabric-react/blob/3ccea373457639519f55d9762c862d44ae4da36c/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L125

#### Actual behavior:

Textfield does not reset

#### Expected behavior:

Textfield should be empty

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/KeNrgP

### LINKED ISSUE #5518: TextField clearing value and validating on submit of containing form
### Bug Report 
 
- __Package version(s)__: 6.2.0 (can repro with  6.32.0 also)
- __Browser and OS versions__: Chrome 67.0.3396.99
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:

When using the `TextField` component in a form, I'm noticing a new (didn't notice this two days ago) issue with the form. When state is set in the submit of the form, the `TextField` clears its content and re-validates even though I'm using `e.preventDefault` in `onSubmit` function
 
#### Actual behavior:

 On submitting a form the `TextField` component re-renders, clears the input value and re runs validation of the TextField
 
#### Expected behavior:

As with a normal input type the value should not be cleared on submit (once preventing default submit behavior) and the validation shouldn't re-run.
 
### If applicable, please provide a codepen repro:
 
https://codesandbox.io/s/llkk1qqj4q

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5518
- [x] Include a change request file using `$ npm run change`

#### Description of changes

#5349 was merged to fix #5146 in which changing the *prop* `value` to `undefined` would not update state. However, #5349 swung too far in the other direction, clearing *state* `value` on prop update even if *prop* `value` was previously `undefined`. This change aims to fix #5518 while keeping the fix in place for #5146.

The assumption here is that if *prop* `value` was previously defined, the user intends for the component to be controlled and that therefore the state should be cleared when a *prop* `value` becomes undefined. However, if the *prop* `value` was previously undefined, it should have no effect on state.

I've added tests to ensure both situations remain fixed. (I confirmed one and the other of these tests failed in the conditions before and after #5349 was merged.)

#### Focus areas to test

Test `value` prop effects on state.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -122,7 +122,9 @@ export class TextField extends BaseComponent<ITextFieldProps, ITextFieldState> i
   public componentWillReceiveProps(newProps: ITextFieldProps): void {
     const { onBeforeChange } = this.props;
 
-    if (newProps.value !== this.state.value) {
+    // If old value prop was undefined, then component is controlled and we should
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: component is *uncontrolled* if value is undefined, right?

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: Shouldn't this just be `this.props.value !== undefined && newProps.value !== this.state.value` ?

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx [hunk 2]
```diff
@@ -131,7 +133,7 @@ export class TextField extends BaseComponent<ITextFieldProps, ITextFieldState> i
       this._latestValue = newProps.value;
       this.setState(
         {
-          value: newProps.value,
+          value: newProps.value || '',
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: If value is `0` numerical, this would not work.

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: I don't quite understand why this one is needed tho.

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx (hunk 1 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: What if the prop previously had a value? That is the substance of #5146. If undefined is not valid for clearing state when value prop was previously defined, then we're going to need a more clear definition for behavior.

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: gotcha!

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx (hunk 2 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: Value is defined as a string or undefined only, not as a number. This is needed to bring symmetry with state behavior, which otherwise defines state.value to '' if value prop is undefined (see constructor). I made this change because I found that if I changed value prop to undefined, then state value became undefined, which is inconsistent with initial state in constructor.

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: ok please merge if you're good with everything!

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx (hunk 1 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: An alternative is to force controlled behavior for clearing, like passing in ``` `` ```, but I worry that `undefined` is just too close to default behavior in React to ignore even in controlled scenarios...

**Comment by an5rag** [comment]
Thanks @JasonGore! I just updated my fabric version and was surprised why my inputs were getting cleared eventhough they were not controlled. (I was using setState to keep track of the contents of the form -> so it re-rendered the inputs)
Which version of fabric's release will contain this fix?
