### PR TITLE
Callout and HoverCard: Fix anchor positions

### LINKED ISSUE #10721: Component positioning going off screen
### Environment Information

- **Package version(s)**: 7.43.1

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/slimemold/pen/bGGGdzY

Examples of repro's in OWA:
image
image

#### Actual behavior:

Components are rendering off the page when near the edges.

#### Expected behavior:

Component positioning should render the whole component on the page

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: OWA

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #10721
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Callout and HoverCard: Fix anchor positions

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10730)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts [hunk 1]
```diff
@@ -481,7 +472,6 @@ function _finalizeReturnEdge(
  * @param {RectangleEdge} bounds
  * @param {RectangleEdge} [alignmentEdge]
  * @param {boolean} coverTarget
- * @param {previousPositions} previousPositions
```
Comment (jdhuntington) [inline packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts]: add comment for new param

File: packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts [hunk 2]
```diff
@@ -491,19 +481,17 @@ function _finalizeElementPosition(
   bounds?: Rectangle,
   alignmentEdge?: RectangleEdge,
   coverTarget?: boolean,
-  previousPositions?: boolean
+  doNotFinalizeReturnEdge?: boolean
```
Comment (jdhuntington) [inline packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts]: It's my own bias, but I think functions are easier to understand if they don't take boolean flags as args. They tend to accumulate over time and are not easy to grok when looking at invocations.

Since this method is small, can there be 2 methods instead of an `if`? I think this lets you walk back several changes and have `_positionCard` make a more straightforward method call all the way through.

File: packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts [hunk 3]
```diff
@@ -877,6 +867,15 @@ export function positionCallout(
   return _positionCallout(props, hostElement, elementToPosition, previousPositions);
 }
 
+export function positionCard(
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts]: Why are creating a public `positionCard` and a private `positionCard` method here?

Comment (joschect) [reply packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts]: Because then we can do whatever we want to change the private position card and keep entirely out of the api.

File: packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts (hunk 2 above)
Comment (joschect) [reply packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts]: I think that we could do that in the future. For now it's hidden enough that it should be okay.
