### PR TITLE
Spinbutton: allow classname to be passed through

### LINKED ISSUE #5327: SpinButton: className prop is not applied
### Bug Report 
 
- __Package version(s)__: 5.112.0 (and probably more recent releases)
- __Browser and OS versions__: All
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Maybe
 
Requested priority: (Blocking, High, Normal, Low)
Normal
 
Products/sites affected: (if applicable)
VSTS

#### Describe the issue:
 
Consumer specified className for the SpinButton component is ignored despite being a part of the interface in [SpinButton.types.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts).
 
#### Actual behavior:
 
Class is not applied.
Using getClassNames is not a desired option as it seems to completely eliminate other styling on the control when all I want is to add my own class to the SpinButton.
 
#### Expected behavior:
 
Class is applied to the outermost element of the component
 
### If applicable, please provide a codepen repro:
[Repro](https://codepen.io/anon/pen/bKKwdJ)

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5327
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Spinbutton: allow classname to be passed through
- the styles and classnames structure of spinbutton is not using the standard `styled` mechanism
- placed a new getClassName prop param to make it consistent; but we really should refactor this spinbutton to be standard way in Fabric later 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.classNames.ts [hunk 1]
```diff
@@ -20,10 +20,11 @@ export const getClassNames = memoizeFunction(
     disabled: boolean,
     isFocused: boolean,
     keyboardSpinDirection: KeyboardSpinDirection,
-    labelPosition: Position = Position.start
+    labelPosition: Position = Position.start,
+    className: string | undefined = undefined
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.classNames.ts]: This classname should probably be `className?: string` - it does not match the interface otherwise (`className?: string` has different semantics from `classname: string | undefined`)
