### PR TITLE
Rating: focus issues

### LINKED ISSUE #3638: Tabbing onto rating control always sets focus on the first star
### Bug Report

- __Package version(s)__: 5.29.0
- __Browser and OS versions__: Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)  High

Products/sites affected: (if applicable)

#### Describe the issue:

Include a rating control. Set its initial value to > 1.
Tab onto to the control. The focus goes on first star and rating gets set to 1.

#### Actual behavior:

Tab onto to the control. The focus goes on first star and rating gets set to 1.

#### Expected behavior:

Focus should go onto the last selected star.

### LINKED ISSUE #3639: Read-only rating control has inconsistent tab behavior
### Bug Report

- __Package version(s)__: 5.29.0
- __Browser and OS versions__: Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

We have used a read only rating control in a detailed list. The tabbing behavior of the control is inconsistent.

#### Actual behavior:

The control is accessible via tab / arrow keys the first time. Then once the control goes out of focus it is not accessible via keyboard.
On debugging, noticed that the tab index is 0 for the first time and post focus change tab index gets set to -1.

#### Expected behavior:

The keyboard navigation should be consistent. Either we cannot navigate or we can always navigate.

### PR DESCRIPTION
**Pull request by lambertwang**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3639
- [x] Addresses an existing issue: Fixes #3638
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Sets defaultActiveElement to the initial rating for the Rating component.
Added isFocusable to the Rating focusZone for consistent keyboard movement behavior.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Rating/Rating.tsx [hunk 1]
```diff
@@ -70,24 +70,38 @@ export class Rating extends BaseComponent<IRatingProps, IRatingState> {
...
 
+      starIds.push(this._getStarId(i - 1));
+
       stars.push(
         <button
           className={ css('ms-Rating-button', styles.ratingButton, {
-            ['ms-Rating--large ' + styles.rootIsLarge]: this.props.size === RatingSize.Large,
-            ['ms-Rating--small ' + styles.rootIsSmall]: this.props.size !== RatingSize.Large
+            ['ms-Rating--large ' + styles.rootIsLarge]: size === RatingSize.Large,
+            ['ms-Rating--small ' + styles.rootIsSmall]: size !== RatingSize.Large
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Rating/Rating.tsx]: size === RatingSize.Small?

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/Rating/Rating.tsx]: you can have a default value for size, but it seems error prone to consider everything not large as small.

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/Rating/Rating.tsx]: Just noticed this while i was here. (I know you didn't make it this way :)

File: packages/office-ui-fabric-react/src/components/Rating/Rating.tsx [hunk 2]
```diff
@@ -70,24 +70,38 @@ export class Rating extends BaseComponent<IRatingProps, IRatingState> {
...
+    } = this.props;
+
+    for (let i = min as number; i <= (max as number); i++) {
       let ratingStarProps: IRatingStarProps = {
         fillPercentage: this._getFillingPercentage(i),
-        disabled: this.props.disabled ? true : false
+        disabled: disabled ? true : false
       };
 
+      starIds.push(this._getStarId(i - 1));
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Rating/Rating.tsx]: not clear why you need an array to save the results, when you can just call the function in the one place you need the id...
