### PR TITLE
DocumentCardTitle: fixing an infinite loop condition calling setState.

### LINKED ISSUE #5308: DocumentCardTitle: "Maximum call stack size exceeded" caused by not truncating the long text
### Bug Report 
 
- __Package version(s)__: 5.112.0

#### Describe the issue:
 
In `DocumentCardTitle`, we have logic for deciding to truncate the title text or not in `_doesTitleOverflow`:
```
    // First check
    return (
      titleElement.scrollHeight > titleElement.clientHeight + TRUNCATION_VERTICAL_OVERFLOW_THRESHOLD ||
      titleElement.scrollWidth > titleElement.clientWidth
    );
  }
```

When trying to truncate it in `_startTruncation`, there is also a check for the length of the title text
```
    // Second check
    // If the title is really short, there's no need to truncate it
    if (originalTitle && originalTitle.length >= miniLength) {
````
We got infinite loop issue "Maximum call stack size exceeded" in a case where  `originalTitle` is `nospacenospacenospacenospacenospace` which has length 35 which is less than the miniLength which is 40. Actually it will render as the snapshot in certain mobile view:
image

It will pass the first check to try to truncate but will fail the second check before truncating so it never get truncated. In `_shrinkTitle`, the `setState` make it re-render and try to re-truncate and finally be a infinite loop.

#### Actual behavior:
 
Infinite loop when rendering DocumentCardTitle
 
#### Expected behavior:
 
No infinite loop

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #5308 
- [X] Include a change request file using `$ npm run change`

#### Description of changes
The infinite loop is caused by this succession of events: 

`onResize` event triggers the `_updateTruncation()` which in turn triggers `_startTruncation()` which is calling `setState()` causing the `componentDidUpdate()` to be invoked. Next in line is `_shrinkTitle()` and here were everything is breaking.

Initially this `setState()` is called here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx#L144

... which is causing `componentDidUpdate()` to be called again and it circles back to the same `setState()` as before until it fails the check in here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx#L140

... when this happens it calls `_startTruncation()` again causing another `componentDidUpdate()` which circles back to this line over and over again. ThE EnD 🤓 
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/6518)

Before: https://gyazo.com/134540469dc71adc4fad96d446770568
After: https://gyazo.com/bab7fe1ed685cc7f3f899d6e2ff729cf

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx [hunk 1]
```diff
@@ -137,14 +134,12 @@ export class DocumentCardTitle extends BaseComponent<IDocumentCardTitleProps, ID
       const { truncatedTitleFirstPiece, truncatedTitleSecondPiece } = this.state;
       this._isTruncated = true;
 
-      if (!truncatedTitleFirstPiece && !truncatedTitleSecondPiece) {
```
Comment (Vitalius1) [inline packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx]: Removing this block as `_shrinkTitle()` is called only on `componentDidUpdate()` when both pieces should have been already set in the `_startTruncation()` after mounting.

File: packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx [hunk 2]
```diff
@@ -137,14 +134,12 @@ export class DocumentCardTitle extends BaseComponent<IDocumentCardTitleProps, ID
...
-        this._startTruncation(this.props);
+      if (truncatedTitleFirstPiece || truncatedTitleSecondPiece) {
```
Comment (Vitalius1) [inline packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx]: Adding this check to stop infinitely calling `setState()` which will cause looping back to the same spot through `componentDidUpdate()`. When the shrinking reached so that both strings are empty stop updating.

**Comment by Vitalius1** [comment]
@mikewheaton could you kindly take a look? Thanks

**Comment by Vitalius1** [comment]
@yiminwu any chance you can take a look? Thanks!

**Comment by Vitalius1** [comment]
😠 where is everyone?

File: packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx [hunk 3]
```diff
@@ -137,14 +134,12 @@ export class DocumentCardTitle extends BaseComponent<IDocumentCardTitleProps, ID
       const { truncatedTitleFirstPiece, truncatedTitleSecondPiece } = this.state;
       this._isTruncated = true;
 
-      if (!truncatedTitleFirstPiece && !truncatedTitleSecondPiece) {
-        this._startTruncation(this.props);
```
Comment (Markionium) [inline packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx]: Where did this line go? Is it not needed anymore?

Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx]: @Markionium yes, I believe it's an extra unnecessary check. `_shrinkTitle()` is called only when the component is already mounted and `_startTruncation()` was called once in `componentDidMount()` where also is attached a `resize` listener which in turn calls `_startTruncation()` again. Next `componentDidUpdate()` is fired and reaches the `_shrinkTitle()`. Initially, the block I removed is skipped as we should have both segments already defined and we are slicing them little by little. The issue comes in play when you resize the window small enough so that the slicing eventually sets them to empty strings and now the block I removed is executed calling `_startTruncation()` which will `setState` causing the `componentDidUpdate()` to call `_shrinkTitle()` and comes to the same check over and over again because the strings will remain empty thus causing the infinite loop.

I hope this explains why it was removed.

Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx]: I believe this strings could reach empty to this method only if you would refresh the shrinked window and after the mount you start the truncation and set them to`''` in `_startTruncation()`. So why call `_startTruncation()` again over and over if the result will not change. Instead I put a check on the slicing below this code block.

Comment (Markionium) [reply packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.tsx]: Sounds sensible to me. I just wanted to make sure it wasn't accidentally removed :D

**Comment by Markionium** [comment]
@dzearing I think we can merge this :D

**Comment by KevinTCoughlin** [comment]
Is the default card supposed to render its title with 2 lines after this fix?

**Before (master)**

image

**After**

image

**Comment by Vitalius1** [comment]
@KevinTCoughlin good question... I didn't notice this change. Let me investigate and see what is happening.

**Comment by Vitalius1** [comment]
@KevinTCoughlin found the issue with 1 line vs 2 lines. What happens is that when running locally I believe by design we are supposed to have 2 lines and this is what we get. But on the website we need to blame UHF for rendering just one line due to some styles coming from it setting `box-sizing: border-box` on everything and the initial measurement of the `DocumentCartTitle` element fails to do what was designed. I will confirm with the designers how many lines it needs to render and submit a separate fix for it if needed.

**Comment by Vitalius1** [comment]
@mikewheaton @yiminwu @dzearing would appreciate a quick review and merge as it up for 10 days already 😊
