### PR TITLE
HoverCard: Dismiss on key/mouse down, Add directionalHint, Fix target prop  

### LINKED ISSUE #2470: HoverCard: target prop is inconsistent
Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: (if applicable)

#### Describe the issue:

Target should be a` HTMLElement | string` to support string selector.

### PR DESCRIPTION
**Pull request by atneik**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2470
- [x] Include a change request file using `$ npm run change`

#### Description of changes

- Dismiss card on key or mouse down
- Add ability to specify target using a query string
- Add directionalHint

#### Focus areas to test

Dismiss behavior of the card.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.tsx [hunk 1]
```diff
@@ -95,6 +100,10 @@ export class ExpandingCard extends BaseComponent<IExpandingCardProps, IExpanding
     );
   }
 
+  public get element(): HTMLDivElement {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.tsx]: not a fan of exposing the element.

File: packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.tsx [hunk 2]
```diff
@@ -139,7 +154,7 @@ export class HoverCard extends BaseComponent<IHoverCardProps, IHoverCardState> {
 
     this._dismissTimerId = this._async.setTimeout(() => {
       if (!(this.props.sticky && type === 'mouseleave')) {
-        const rect = this._hoverCard.getBoundingClientRect();
+        const rect = this._expandingCard.element.getBoundingClientRect();
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.tsx]: Is there a better way than to measure this? For example, when the cursor goes over it, set a state to true, when it leaves, set a state to false, then never measure? Measuring is very expensive.

Comment (atneik) [inline packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.tsx]: This will be only called when the card is open and trying to dismiss, and not when a user is casually moving the cursor over targets. 

Callbacks in the event of `mouseLeave` and `mouseEnter` manage the state of `isHoverCardVisible`. But this technique fails when the card expands and is overlapping the target; wherein upon cursor move `mouseEnter` from card is called before `mouseLeave` from the target, resulting in end state of `isHoverCardVisible` to be false. 

If there is a cheaper way to know if the card is going to overlap the target, then we can short-circuit the measure.

File: packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.tsx (hunk 1 above)
Comment (atneik) [inline packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.tsx]: I know this is an anti-pattern. I had to expose it to use in `HoverCard` for measurement. Is there a better way to get hold of the element?

File: packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.Target.Example.tsx [hunk 3]
```diff
@@ -46,8 +47,8 @@ class HoverCardField extends BaseComponent<IHoverCardFieldProps, IHoverCardField
           this.state.contentRendered &&
           <HoverCard
             expandingCardProps={ this.props.expandingCardProps }
-            instantOpenOnClick={ true }
             target={ this.state.contentRendered }
+            cardDismissDelay={ 300 }
```
Comment (Jahnp) [inline packages/office-ui-fabric-react/src/components/HoverCard/examples/HoverCard.Target.Example.tsx]: Just thinking out loud--from a guidance/usage perspective, it may be useful to explicitly call out in the example that you're adding a delay here.
