### PR TITLE
Stack empty divs

### LINKED ISSUE #7189: Horizontal/VerticalStack should not add `display: none` to `>:empty` selectors.
### Environment Information 
 
- __Package version(s)__: @uifabric/experiments - current
- __Browser and OS versions__: All

### Please provide a reproduction of the bug in a codepen:
Codepen seems to be down now but Katherine knows what I am talking about. :) 

image
 
Code: 
https://github.com/OfficeDev/office-ui-fabric-react/blob/0ae1191e4b7695ef0b439603c48900622da07706/packages/experiments/src/components/Stack/Stack.styles.ts#L38

This is undesirable because 
1. people expect empty divs to behave as a block element.
2. it is an unexpected and uncommon behavior of Stacks to change the behavior of empty divs

#### Actual behavior:
 
Empty divs that have block properties and other styling do not show up/take up space.
 
#### Expected behavior:
 
Empty divs that have block properties and other styling SHOULD show up/take up space.

### PR DESCRIPTION
**Pull request by kkjeer**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7189 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Remove `display: "none"` styling on empty Stack children. StackItem now returns `null` rather than an empty `<span />` if it does not have any children.

Examples:

HorizontalStack:

When child elements 1, 3, and 5 are empty (`<Text />`):
```
<div class="ms-HorizontalStack root-331">
    <span class="item-244"></span>
    <span class="item-244">2</span>
    <span class="item-244"></span>
    <span class="item-244">4</span>
    <span class="item-244"></span>
</div>
```
horizontal_empty

When child elements 1, 3, and 5 are empty StackItems, which return null: (`<HorizontalStack.Item />`):
```
<div class="ms-HorizontalStack root-331">
    <span class="item-244">2</span>
    <span class="item-244">4</span>
</div>
```
horizontal_null

VerticalStack:

When child elements 1, 3, and 5 are empty (`<Text />`):
```
<div class="ms-VerticalStack root-226">
    <span class="item-227"></span>
    <span class="item-227">2</span>
    <span class="item-227"></span>
    <span class="item-227">4</span>
    <span class="item-227"></span>
</div>
```
vertical_empty

When child elements 1, 3, and 5 are empty StackItems, which return null: (`<VerticalStack.Item />`):
```
<div class="ms-VerticalStack root-226">
    <span class="item-227">2</span>
    <span class="item-227">4</span>
</div>
```
vertical_null

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/experiments/src/components/Stack/StackItem/StackItem.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@ const view: IStackItemComponent['view'] = props => {
   const childNodes: React.ReactElement<{}>[] = React.Children.toArray(props.children) as React.ReactElement<{}>[];
   const first = childNodes[0];
   if (!first) {
-    return <span />;
+    return null;
```
Comment (cliffkoh) [inline packages/experiments/src/components/Stack/StackItem/StackItem.tsx]: 👍

**Comment by cliffkoh** [comment]
That.. was fast... 👏
