### PR TITLE
[PeoplePicker] Accessibility fixes

### LINKED ISSUE #2279: [PeoplePicker] "Delete" button on resolved suggestion does not have an ARIA label
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High (Accessibility) 

Products/sites affected: ODSP, any consumer of web UI

#### Describe the issue:

Resolved suggestions in the PeoplePicker component have an "X" button to remove the suggestion, but that "X" button doesn't have an ARIA label.

#### Actual behavior:

Screen reader does not describe purpose of button.

#### Expected behavior:

Screen reader describes purpose of button.

### PR DESCRIPTION
**Pull request by martellaj**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2279, #1611 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

- Adds `removeButtonAriaLabel` prop to provide a screen reader label for the "X" button in default selected item components in picker
- Adds status message so that screen reader will announce there are suggestions available in picker

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -180,7 +180,8 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
       selected: this.selection.isIndexSelected(index),
       onRemoveItem: () => this.removeItem(item),
       disabled: disabled,
-      onItemChange: this.onItemChange
+      onItemChange: this.onItemChange,
+      removeButtonAriaLabel: this.props.removeButtonAriaLabel
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: nit, add removeButtonAriaLabel to line 172

File: packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemDefault.tsx [hunk 2]
```diff
@@ -14,7 +14,8 @@ export const SelectedItemDefault: (props: IPeoplePickerItemProps) => JSX.Element
     item,
     onRemoveItem,
     index,
-    selected
+    selected,
+    removeButtonAriaLabel = ''
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemDefault.tsx]: reason to default this to empty string? do you want ariaLabel to always show up even if it is empty?

Comment (martellaj) [inline packages/office-ui-fabric-react/src/components/pickers/PeoplePicker/PeoplePickerItems/SelectedItemDefault.tsx]: I just wanted to ensure nothing would break; I'll take out the default value and verify that it's all good regardless.

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.scss [hunk 3]
```diff
@@ -138,4 +138,15 @@
     background: $ms-color-neutralTertiaryAlt;
     color: $ms-color-neutralDark;
   }
+}
+
+.suggestionsAvailable {
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.scss]: @cschlechty is there a preferred method for hiding text used for the sole purpose of alerts? I thought we'd done that in some other components.
