### PR TITLE
Button: Wrap in span if doNotLayer

### LINKED ISSUE #3521: Nested buttons in ContextMenu
### Bug Report

- __Package version(s)__: 5.17.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: LPC

#### Describe the issue:

When we use the DefaultButton with a context menu and doNotLayer=true, the html generated contains nested buttons element which is not legal html.

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3521
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Clean up content render, and wrap button and contextual menu in span if doNotLayer to avoid buttons in buttons.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -214,19 +215,27 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
...
+        { onRenderChildren(props, this._onRenderChildren) }
+        { !this._isSplitButton && (menuProps || menuIconProps || this.props.onRenderMenuIcon) && onRenderMenuIcon(this.props, this._onRenderMenuIcon) }
+        { this.state.menuProps && !this.state.menuProps.doNotLayer && onRenderMenu(menuProps, this._onRenderMenu) }
+      </div>
+    </Tag>
+
+    if (menuProps && menuProps.doNotLayer) {
+      return (
+        <span style={ { display: 'inline-block' } }>
+          { Content }
```
Comment (jspurlin) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Technically in HTML a div can't be inside of a span which happens in this case

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: ah, I can go with a div then

**Comment by micahgodbolt** [comment]
is travis having issues lately? I think the test is running, but it's not reporting back to here.

**Comment by jspurlin** [comment]
I'm not aware of any issue with travis, I also don't know how to access travis outside of the link that's usually provided as part of the travis check (that's currently missing)...

**Comment by micahgodbolt** [comment]
https://travis-ci.org/OfficeDev/office-ui-fabric-react/

**Comment by micahgodbolt** [comment]
tests all passed, but travis is not reporting
