### PR TITLE
Do not ignore onKeyDown for buttons with a menu

### LINKED ISSUE #3914: onKeyDown on Button does not fire for Button with a menu
### Bug Report

- __Package version(s)__: 5.48.1
- __Browser and OS versions__: Not relevant

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  High

Products/sites affected: (if applicable) LPC Keyboard users

#### Describe the issue:

TLDR; The `onKeyDown` event on the button is never triggered for a `Button` with a menu

When rendering a Button (withMenu) inside an element with an onKeyDown handler the keydown event does not stop propagating. 
In the case of LPC we have a button with a menu inside a `Link` component. This results into us navigating to the link. Setting `onKeyDown={e => e.stopPropagation()}` on the Button never fires.

#### Actual behavior:

onKeyDown does not fire for menu buttons.

#### Expected behavior:

onKeyDown fires for menu buttons.

### If applicable, please provide a codepen repro:

http://jsbin.com/gesipamone/edit?js,console,output

### PR DESCRIPTION
**Pull request by Markionium**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3914
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fire the provided `onKeyDown` event for Buttons with menus when a key other than `Arrow down` is pressed.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -496,13 +496,17 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
...
-  private _onMenuKeyDown(ev: React.KeyboardEvent<HTMLElement>) {
+  private _onMenuKeyDown(ev: React.KeyboardEvent<HTMLDivElement | HTMLAnchorElement | HTMLButtonElement>) {
     if (ev.which === KeyCodes.down) {
       let { onMenuClick } = this.props;
       onMenuClick && onMenuClick(ev, this);
       !ev.defaultPrevented && this._onToggleMenu();
       ev.preventDefault();
       ev.stopPropagation();
+    } else {
+      if (this.props.onKeyDown) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Can you just move 507 to line 500, outside of the if? I think onKeyDown should always be executed if passed in.

Additionally, I believe if `ev.defaultPrevented` is true, we should maybe skip our default logic.

Comment (Markionium) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Yes can do :)

**Comment by dzearing** [comment]
Looks good!
