### PR TITLE
Theme Designer: a11y panel & fabric palette table updates.

### LINKED ISSUE #11634: Theme Designer incorrectly states theme is accessible
The Theme Designer has a couple of issues that make it incorrectly identify a theme as accessible:

1. It doesn't check for accessibility of neutralSecondary. This color is used as secondary text across many components, which need to be accessible at 4:1 contrast
 image

2. It does not correctly generate the proper neutralSecondary value, based on the default setting of "Text". This value is #323130, and neutralSecondary should be #605e5c, but it shows as #a3a2a0
image

### PR DESCRIPTION
**Pull request by aneeshack4**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11634 
- [x] Include a change request file using `$ yarn change`

#### Description of changes
Adding secondary text to a11y panel, adding neutralSecondaryAlt to Fabric Palette slots table, fixing ThemeRulesStandards & ThemeGenerator producing color inaccuracies
image

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11664)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts [hunk 1]
```diff
@@ -39,8 +39,8 @@ export enum FabricSlots {
   neutralQuaternary, // BaseSlots.backgroundColor, Shade[Shade.Shade5]);
   neutralTertiaryAlt, // BaseSlots.backgroundColor, Shade[Shade.Shade6]); // bg6 or fg2
   neutralTertiary, // BaseSlots.foregroundColor, Shade[Shade.Shade3]);
-  // deprecated: neutralSecondaryAlt, // BaseSlots.foregroundColor, Shade[Shade.Shade4]);
-  neutralSecondary, // BaseSlots.foregroundColor, Shade[Shade.Shade5]);
+  neutralSecondaryAlt, // BaseSlots.foregroundColor, Shade[Shade.Shade5]);
+  neutralSecondary, // BaseSlots.foregroundColor, Shade[Shade.Shade4]);
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts]: is this intentional?

File: packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts [hunk 2]
```diff
@@ -150,49 +130,62 @@ export function themeRulesStandardCreator(): IThemeRules {
   _makeFabricSlotRule(FabricSlots[FabricSlots.neutralTertiaryAlt], BaseSlots.backgroundColor, Shade.Shade6, true); // bg6 or fg2
   _makeFabricSlotRule(FabricSlots[FabricSlots.neutralTertiary], BaseSlots.foregroundColor, Shade.Shade3);
   _makeFabricSlotRule(FabricSlots[FabricSlots.neutralSecondary], BaseSlots.foregroundColor, Shade.Shade4);
-  _makeFabricSlotRule(FabricSlots[FabricSlots.neutralPrimaryAlt], BaseSlots.foregroundColor, Shade.Shade5);
+  _makeFabricSlotRule(FabricSlots[FabricSlots.neutralSecondaryAlt], BaseSlots.foregroundColor, Shade.Shade5);
+  _makeFabricSlotRule(FabricSlots[FabricSlots.neutralPrimaryAlt], BaseSlots.foregroundColor, Shade.Shade6);
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts]: you can't just change the shade number, unfortunately, because each shade is tied to a specific coefficient in shades.ts. This will cause the algorithm to be off. Leave the neutralSecondaryAlt changes for a separate PR, since that will be difficult.

File: packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts (hunk 1 above)
Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts]: Yes Shade5 in the comment of neutralSecondary doesn't match the original setting anyways (which is Shade4 down below on line 132) so I corrected it to Shade4

File: packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts (hunk 2 above)
Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts]: removed it!

File: packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts [hunk 3]
```diff
@@ -40,8 +40,8 @@ export enum FabricSlots {
   neutralTertiaryAlt, // BaseSlots.backgroundColor, Shade[Shade.Shade6]); // bg6 or fg2
   neutralTertiary, // BaseSlots.foregroundColor, Shade[Shade.Shade3]);
   // deprecated: neutralSecondaryAlt, // BaseSlots.foregroundColor, Shade[Shade.Shade4]);
-  neutralSecondary, // BaseSlots.foregroundColor, Shade[Shade.Shade5]);
-  neutralPrimaryAlt, // BaseSlots.foregroundColor, Shade[Shade.Shade6]);
+  neutralSecondary, // BaseSlots.foregroundColor, Shade[Shade.Shade4]);
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts]: change these comments back
