### PR TITLE
DatePicker: Accessibility fixes

### LINKED ISSUE #1584: Date Picker: screen reader accessibility issues
### Bug Report

- __Package version(s)__: 2.10.3
- __Browser and OS versions__: edge+firefox 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, but I am not sure how to resolve it.

Requested priority: Normal 

Products/sites affected: VSTS

#### Describe the issue:

The date picker doesn't read out appropriate messages to give visually impaired users to use the control effectively. These are following issues.
1. When the focus is on input element of date picker.
2. Tabbing to following elements in calendar control and verify inspect properties
- 'Previous Month' 
- Next Month
- Previous Year
- Next Year
- Months (Jan, Feb to Dec)
- Go to today
3. Tab to a date and verify inspect properties.
4. Verify the inspect properties for the month data grid present in the page.

#### Actual behavior:
1. Help text is null. Narrator reads as  '\<aria-label that we have set>, editing' and does not give any information of how it is invokable or is it invokable.
2. Name property is null. Narrator reads as 'group'.
3. Name property is <number> eg: '28'. Narrator reads as '28'.
4.
- IsGridPatternAvailable and IsTablePatternAvailable is true for the datagrid
- Because of the above properties, Narrator reads the date as 'table , 20' for the first time when user focuses on the date

#### Expected behavior:

1. Help text should be 'Press Enter to open the Calendar to select a date' or any such information so that the user will know that there is a calendar control.
2. Name property should be appropriate, simple and should define the purpose of the element. Name property for month names should be '\<month>,\<year>'.
3. Name property should be '\<date>, \<day>, \<month>, \<year>' eg. 20 Thursday April 2017 
4. IsGridPattern and IsTablePattern properties should be false for the datagrid

### PR DESCRIPTION
**Pull request by mdahamiwal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1584 
- [x] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [x] Documentation update

#### Description of changes
Date picker fixes:
1. Calendar popup has Dialog role with label as "calendar" (option to customize the label).
2. "Go to Today" is now assigned button role
3. Days have more readable labels. Earlier - 03/08/2017, Now - 3 August, 2017

Search box fix:
1. In Edge browser the `flex` property is read incorrectly as `0%` instead of `0px` like in other browsers. so making it explicit.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by mdahamiwal** [comment]
@cschlechty , @micahgodbolt can you guys review this ?

File: packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx [hunk 1]
```diff
@@ -115,6 +115,7 @@ export class Calendar extends BaseComponent<ICalendarProps, ICalendarState> impl
                   onNavigateDate={ this._onNavigateDate } /> }
 
                 { showGoToToday && <span
+                  role='button'
```
Comment (cschlechty) [inline packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: You need to add space as an activation key, too. Do the action shift focus to the current date?

Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: done. Apart from this I have converted days and months role to match http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20%28Basic%29/demo.htm. We don't need a table layout here.

Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: Yes, that's the current behavior.

**Comment by mdahamiwal** [comment]
@dzearing , we are using FocusZone at https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx#L69-L84 but on ▶️ press, the focus doesn't move to next line after current row ends. ⬆️ , ⬇️ seems to be working fine. Any idea what are we doing differently here compared to other places.

**Comment by mdahamiwal** [comment]
@micahgodbolt, @cschlechty can you guys have a look? Thanks

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx [hunk 2]
```diff
@@ -123,7 +123,7 @@ export class CalendarDay extends BaseComponent<ICalendarDayProps, ICalendarDaySt
         <FocusZone>
           <table
             className={ css('ms-DatePicker-table', styles.table) }
-            role='grid'
+            role='application'
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: @cschlechty @jspurlin 

`role=application` here; will this cause problems? Is this right?

Comment (cschlechty) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: yes, it'll force the screen reader to change modes. why not just properly structure the table and let users use their accelerators?

Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: Table structure is not useful in case of calendar, as we don't want to announce column, column headers and rows given its intuitive in case of calendar. I am following the one provided at http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20%28Basic%29/demo.htm. It aligns with our windows Calendar as well.

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx [hunk 3]
```diff
@@ -157,17 +156,19 @@ export class CalendarDay extends BaseComponent<ICalendarDayProps, ICalendarDaySt
                             ['ms-DatePicker-day--today ' + styles.dayIsToday]: day.isToday,
                             ['ms-DatePicker-day--highlighted ' + styles.dayIsHighlighted]: day.isSelected
                           }) }
-                        role='gridcell'
+                        role='link'
+                        href='#'
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: why does this div have an href?

File: packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx [hunk 4]
```diff
@@ -168,6 +169,7 @@ export class DatePicker extends BaseComponent<IDatePickerProps, IDatePickerState
       isRequired,
       disabled,
       ariaLabel,
+      pickerAriaLabel,
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: Above you say `@defaultvalue Calendar` but there isn't a default value here or below where it's used.

File: packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss [hunk 5]
```diff
@@ -55,7 +55,7 @@
   font-size: inherit;
   color: $ms-color-black;
   background-color: transparent;
-  flex: 1 1 0;
+  flex: 1 1 0px;
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss]: was this to fix a bug somewhere? the px should be superfluous.

**Comment by mdahamiwal** [comment]
@cschlechty we purposefully need `role=application` to allow navigation through grid layout. If screen reader is in scan mode it will read the cell data instead of moving focus to next/prev date when arrows are pressed. Here is description of why its required in some cases https://www.marcozehe.de/2012/02/06/if-you-use-the-wai-aria-role-application-please-do-so-wisely/

File: packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss (hunk 5 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.scss]: Yes, its an Edge but the browser reads `1 1 0` as `1 1 0%` which breaks the layout, for other browsers its read correctly as `1 1 0px` so making it explicit.

File: packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx (hunk 4 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: check `defaultProps` above

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx (hunk 3 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: we have assigned `role=link` which requires `href` to be present. check https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx [hunk 6]
```diff
@@ -123,7 +123,6 @@ export class CalendarDay extends BaseComponent<ICalendarDayProps, ICalendarDaySt
         <FocusZone>
           <table
```
Comment (cschlechty) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: If you're using application, put role="presentation" on the table to signal that it's just for layout

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx (hunk 3 above)
Comment (cschlechty) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: You likely want something like "javascript:;" as the href as # will change the url

Comment (cschlechty) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: Also, this should probably be a button since it's not doing any navigation and is same page.

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx (hunk 6 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: Not sure if I understand the concern correctly - these roles are not dependent as far as I know. I am using application to switch screen reader mode (which we need). I am no longer using `role=presentation` as you suggested and it makes sense to keep the table roles intact.

Comment (cschlechty) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: If you're keeping application, it implies its mainly for formatting. If you want it navigable as a true table, it'd need headers and a table description etc

Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx]: I am applying application on entire calendar control not on table so it just switches the ATs mode when anything inside calendar control is focused. I tested with screen readers and the experience is smooth with table cells and headers being announced properly.
