### PR TITLE
Positioning: Fix issue where anchor edge would flip even if previous positions calculated

### LINKED ISSUE #9132: Hover card jump
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
The hover card is "jumping" if user move mouse into the card when the card is rendering
fabric_hovercard_jump

Reproable on fabric display site: https://developer.microsoft.com/en-us/fabric#/controls/web/hovercard 
 
#### Expected behavior:
 
The card should not "jump" when it is rendering

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #9132
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

Positioning: Fix issue where anchor edge would flip even if previous positions calculated

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/10557)

### CODE REVIEW

**Comment by joschect** [comment]
@dzearing screener failure appears to be unrelated.

File: packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts [hunk 1]
```diff
@@ -442,13 +442,22 @@ function _getFlankingEdges(edge: RectangleEdge): { positiveEdge: RectangleEdge;
...
+ * The finalized return edge should not flip if the element has already been positiuoned successfully to prevent the callout from
+ * appearing to jump
  *
  * @param elementRectangle
  * @param targetEdge
  * @param bounds
+ * @param previousPositions
  */
-function _finalizeReturnEdge(elementRectangle: Rectangle, returnEdge: RectangleEdge, bounds?: Rectangle): RectangleEdge {
+function _finalizeReturnEdge(
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/utilities/positioning/positioning.ts]: possible to have a unit test update to test the scenario?

**Comment by dzearing** [comment]
looks better, compared it to livesite and there's no more jump.
