### PR TITLE
Jolore/calendar updates

### LINKED ISSUE #4415: Accessibility -DatePicker - focus should stay inside callout until date is selected or picker is dismissed
### Bug Report

- __Package version(s)__: 5.57
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Planner

#### Describe the issue:

When focus is inside the date picker component, you are able to tab outside of the datepicker. Focus needs to stay inside the callout until a date is picked or the picker is dismissed with a click outside the callout or the ESC key. We have an accessibility bug filed against Planner for this issue.

### LINKED ISSUE #4623: DatePicker steals focus on dismiss
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__:  all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)  Normal

#### Describe the issue:
1. Have a form with multiple inputs
2. Open the datepicker calendar
3. Change your mind and move to edit another input on the form. Click that input
4. DatePicker calendar closes, but the DatePicker input is now focused, not the input I clicked

### PR DESCRIPTION
**Pull request by lorejoh12**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4415, fixes #4623
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Updating the rest of the styling for the calendar component to latest design guidelines. Also fixing some bugs in Calendar and DatePicker.

Fixing one of the bugs referenced in #3300, with Datepicker's disableAutoFocus not preventing focus after click. Not resolving it since it was a more expansive feature request.

Fixes #4415 by wrapping the date picker in a focusTrapZone, making it so that focus stays inside while tabbing and goes back to beginning or end. DatePicker will close on ESC key or after selecting a date.

Fixes #4623 by removing the custom logic for resetting focus on dismiss of the date picker. Now we rely on FocusTrapZone to reset the focus back where it should go when the date picker closes, which resolves the issue.

inside MSFT can see this link for updates: http://jolore/fabric/#/examples/calendar

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx [hunk 1]
```diff
@@ -194,6 +196,10 @@ export class CalendarMonth extends BaseComponent<ICalendarMonthProps, {}> {
     }
   }
 
+  private _onSelectMonthKeyDown = (index: number): (ev: React.KeyboardEvent<HTMLElement>) => void => {
+    return (ev: React.KeyboardEvent<HTMLElement>) => this._onKeyDown(() => this._onSelectMonth(index), ev);
```
Comment (KevinTCoughlin) [inline packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx]: Do you want both `ENTER` and `SPACE` because otherwise `onClick` will work for both mouse and `SPACE` since its a `<button/>`. I ask because I recently fixed a semi-related bug where buttons were firing their handlers twice -- https://github.com/OfficeDev/office-ui-fabric-react/pull/4662.

If we continue with this approach, I do think we can reduce this function signature by at least eliminating one closure, but I need to try myself with code.

File: packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx [hunk 2]
```diff
@@ -21,6 +21,7 @@ import {
 } from '../../Utilities';
 import { compareDates, compareDatePart } from '../../utilities/dateMath/DateMath';
 import * as stylesImport from './DatePicker.scss';
+import { FocusTrapZone } from 'office-ui-fabric-react/lib/FocusTrapZone';
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: This import should be a relative path.

File: packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx (hunk 1 above)
Comment (lorejoh12) [reply packages/office-ui-fabric-react/src/components/Calendar/CalendarMonth.tsx]: For the SPACE issue, good call, that was an unintentional bug. Should be fixed now.

File: packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx (hunk 2 above)
Comment (lorejoh12) [reply packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: fixed now, thanks for helping figure this out David
