### PR TITLE
Fix merge-styles: class names in selector values expanded into parent…

### LINKED ISSUE #3278: merge-styles put expanded rules in selector into parent scope
### Bug Report

- __Package version(s)__: 5.9.0
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: (if applicable)

#### Describe the issue:
`
const marginTopStyle = mergeStyles({marginLeft: "10px"});
mergeStyles({
  selectors: {
    "& > * + *": marginTopStyle,
  },
})`

will generate into CSS rule:
`css-xx{margin-left:10px;}`

#### Actual behavior:

The merge styles generates
`css-xx{margin-left:10px;}`

#### Expected behavior:

The merge styles should generate
`css-xx > * + *{margin-left:10px;}`

### PR DESCRIPTION
**Pull request by stephenzsy**
… scope instead within the selector

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3278
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fix: registered class in selectors are expanded into the parent class instead of in selector

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by christiango** [comment]
Can you add some tests here that fail before this change and pass after?

File: packages/merge-styles/src/styleToClassName.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ function extractRules(
       const expandedRules = stylesheet.argsFromClassName(arg);
 
       if (expandedRules) {
-        extractRules(expandedRules, rules);
+        extractRules(expandedRules, rules, currentSelector);
```
Comment (dzearing) [inline packages/merge-styles/src/styleToClassName.ts]: The tests are easy to write. Run `npm run start-test` in the merge-styles package folder and then just add tests. I recommend when hitting these cases, make a test first to validate it fails your assertion, then fix the bug.

File: common/changes/@uifabric/merge-styles/style-to-classname_2017-10-31-23-57.json [hunk 2]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "@uifabric/merge-styles",
+      "comment": "Fix mergeStyles generates wrong CSS rules for registered classnames as selector values",
```
Comment (dzearing) [inline common/changes/@uifabric/merge-styles/style-to-classname_2017-10-31-23-57.json]: I don't know what scenario this is fixing. The PR comments don't mention what's going fixed either.

**Comment by stephenzsy** [comment]
`
    Expected value to equal:
      ".css-0{background:red;}.css-1 > *{background:red;}"
    Received:
      ".css-0{background:red;}.css-1{background:red;}"
`

File: packages/merge-styles/src/styleToClassName.ts (hunk 1 above)
Comment (stephenzsy) [reply packages/merge-styles/src/styleToClassName.ts]: Added tests

File: common/changes/@uifabric/merge-styles/style-to-classname_2017-10-31-23-57.json (hunk 2 above)
Comment (stephenzsy) [reply common/changes/@uifabric/merge-styles/style-to-classname_2017-10-31-23-57.json]: Updated description

File: packages/merge-styles/src/styleToClassName.test.ts [hunk 3]
```diff
@@ -129,6 +129,18 @@ describe('styleToClassName', () => {
...
+  it('can expand previously defined rules in selectors', () => {
+    const className = styleToClassName({ background: 'red' });
+    const newClassName = styleToClassName({
+      selectors: {
+        '& > *': className
+      },
+    });
+
+    expect(newClassName).toEqual('css-1');
+    expect(_stylesheet.getRules()).toEqual('.css-0{background:red;}.css-1 > *{background:red;}');
```
Comment (dzearing) [inline packages/merge-styles/src/styleToClassName.test.ts]: cool!
