### PR TITLE
Dropdown: Change order of native props so className prop will overwrite properly

### LINKED ISSUE #2221: Dropdown down arrow displaced when className is set to null or undefined
### Bug Report

- __Package version(s)__: 4.21.0
- __Browser and OS versions__: Chrome 59.0.3071.115

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? No :(
Requested priority: Low

#### Describe the issue:

If in a dropdown you set className property to null or undefined, the down arrow is displaced to the top  of the container. It is problematic when you are composing components and the dropdown inherits the class name from the parent component properties.

#### Actual behavior:
The down arrow is displaced to the top of the container

#### Expected behavior:

The down arrow should stay in its place ;)

### If applicable, please provide a codepen repro:

https://codepen.io/Intnovaction/pen/MoRNoJ

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2221
- [x] Include a change request file using `$ npm run change`

#### Description of changes

insert native props at top of Dropdown div element so className prop will overwrite properly

#### Focus areas to test

Dropdown

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -127,6 +127,7 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
           <Label className={ css('ms-Dropdown-label') } id={ id + '-label' } ref={ this._resolveRef('_dropdownLabel') } required={ required }>{ label }</Label>
         ) }
         <div
+          { ...divProps }
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: instead of moving divProps all the way up to the top, how about just moving className below divProps. often users want to override the role or an aria value, and putting divProps up here won't allow them to do that.

Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Sure, changed so className is under divProps (back to it's original order)
