### PR TITLE
SplitButton: Fix MenuIcon color and other styling

### LINKED ISSUE #6128: Button: SplitButton MenuIcon is too dark
Seems we got the size right, but missed a difference in color
Current menuIcon in split button is #333333 while regular menu icon is #666666

#666666 is the correct value. Might as well double check other values as well. 

image

### PR DESCRIPTION
**Pull request by natalieethell**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6128 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Corrects the color and other styling for the SplitButton MenuIcon. You can see that the rightmost ChevronDown icon is lighter in the "After".

Before:
image

After:
image

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -315,6 +315,10 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
     const { iconProps } = this.props;
 
     if (iconProps) {
+      if (iconProps.className) {
+        const { className, ...rest } = iconProps;
```
Comment (kenotron) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: I actually don't think this conditional needs to be there - destructuring should work even if className doesn't exist. Then you can probably do css(...) like you do already...
