### PR TITLE
getFocusStyle: Add -moz-focus-inner to fix outline bug

### LINKED ISSUE #2206: Buttons: In firefox, buttons are showing dotted outline when focused no matter if outline:none is set
This is a known behavior on firefox and [this](https://stackoverflow.com/questions/71074/how-to-remove-firefoxs-dotted-outline-on-buttons-as-well-as-links) stack overflow discussion pointed out the solution. I also see jquery has applied the same workaround for all their buttons (see below snippet from jquery)
/* workarounds */
/* reset extra padding in Firefox, see h5bp.com/l */
input.ui-button::-moz-focus-inner,
button.ui-button::-moz-focus-inner {
    border: 0;
    padding: 0;
}

And I am thinking about doing the same for all button.ms-button in office fabric code, thoughts?

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2206 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/styling/src/styles/getFocusStyle.ts [hunk 1]
```diff
@@ -21,6 +21,7 @@ export function getFocusStyle(
   return mergeStyles(
     {
       outline: 'transparent',
+      '::-moz-focus-inner': { border: 0 },
```
Comment (dzearing) [inline packages/styling/src/styles/getFocusStyle.ts]: why is this needed? What behavior does it change?

Also, should autoprefixing be adding this rule if outline transparent is present?

Comment (micahgodbolt) [inline packages/styling/src/styles/getFocusStyle.ts]: button
