### PR TITLE
Dropdown & ComboBox options screen reader fix

### LINKED ISSUE #7408: Screen readers double-reading option text in ComboBox and Dropdown options
### Environment Information 

- __Package version(s)__: 6.111.2,  repros on latest demo page version
- __Browser and OS versions__: Latest Chrome

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/6.114.0/#/examples/dropdown
 
#### Actual behavior:
 
Using the NVDA screenreader to navigate the options in the dropdown or combo box results in the "text" provided to that option being read twice. This happens because when the component's aria label and title props are not defined, the component falls back to using the text prop as a default ariaLabel and title. This causes screen-readers to duplicate the text when reading it out. This behavior is unwanted and not necessary.
 
#### Expected behavior:
 
This text should be read only once. Aria label and title attributes should only be rendered if provided via props.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, will submit shortly
 
Requested priority: Normal
 
Products/sites affected: Microsoft Teams

### PR DESCRIPTION
**Pull request by ConorWuertz**
#### Pull request checklist

- [ ] Addresses an existing issue: Does not completely fix #7408 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

ComboBox and Dropdown options now don't include ariaLabel unless provided via props. This prevents aria labels from falling back to the text prop like before, which led screen readers to double-read that text while navigating the options. Note: double reading will still occur because of the title attribute.

ComboBox now respects its ariaLabel prop and does not include the aria-labelledby attribute when provided with an ariaLabel.

#### Focus areas to test

Dropdown and ComboBox accessibility

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -1,31 +1,30 @@
 import * as React from 'react';
-
-import { CommandButton, IButtonStyles, IconButton } from '../../Button';
-import { Callout } from '../../Callout';
-import { Checkbox } from '../../Checkbox';
-import { KeytipData } from '../../KeytipData';
-import { Label } from '../../Label';
+import { Autofill, IAutofill } from '../Autofill/index';
```
Comment (ConorWuertz) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: my VSO plugin reordered these imports and alphabetized them. I can revert this part if its unwanted.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx [hunk 2]
```diff
@@ -551,8 +550,8 @@ export class DropdownBase extends BaseComponent<IDropdownInternalProps, IDropdow
         onMouseMove={this._onItemMouseMove.bind(this, item)}
         role="option"
         aria-selected={isItemSelected ? 'true' : 'false'}
-        ariaLabel={item.ariaLabel || item.text}
-        title={item.title ? item.title : item.text}
+        ariaLabel={item.ariaLabel}
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx]: I understand the change to the aria-Label, but is the change to the title really necessary? This minimally regresses the scenario where the option text is far too long .. now that there's no title, you have no way to tell what the full option text is.

@natalieethell @ecraig12345

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx [hunk 3]
```diff
@@ -332,7 +332,7 @@ describe('Dropdown', () => {
       expect(titleElement.textContent).toEqual('4');
     });
 
-    it('Shows correct tooltip with and without title prop specified', () => {
+    it('Shows correct tooltip only with title prop specified', () => {
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx]: Changing the behavior of existing unit tests like this is usually tricky because they usually have a reason for asserting a certain behavior... 

And so this would either be introducing a regression or a breaking change and hence we need to be extra careful.

The specific regression here is in the other comment above.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx (hunk 2 above)
Comment (ConorWuertz) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx]: Using the title attribute is bad practice for accessibility. IMO, its better to fix the accessibility issue for default use cases and allow consumers of the component to decide when to use a title.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title#Accessibility_concerns
There's some good links here about the issues with the title attribute

Comment (cliffkoh) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx]: Hi @ConorWuertz, thanks for the link and I agree with the point you're making. 

However, even though the reliance on title for tooltip purposes is not great, this change here is potentially (and very plausibly) disruptive to everyone already relying on this. All of a sudden, you can no longer mouse over a clipped text in production apps using Fabric Dropdown where it was previously possible. 

I recommend preserving the current treatment of title until such point @ecraig12345 rewrites Dropdown and ComboBox and we can do something better here (and be in a better position to make breaking changes..)

Comment (ConorWuertz) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx]: Ok, that's a bummer as we'll still see the double-readout issue if we keep the title, but I'll go ahead and adjust this PR to change only the aria-label functionality.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx (hunk 3 above)
Comment (ConorWuertz) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx]: reverting this change

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx [hunk 4]
```diff
@@ -1,15 +1,14 @@
...
-import { mount } from 'enzyme';
-
-import { KeyCodes, resetIds } from '../../Utilities';
 import { Dropdown } from './Dropdown';
 import { DropdownBase } from './Dropdown.base';
-import { DropdownMenuItemType, IDropdownOption, IDropdown } from './Dropdown.types';
+import { DropdownMenuItemType, IDropdown, IDropdownOption } from './Dropdown.types';
+import { KeyCodes, resetIds } from '../../Utilities';
+import { mount } from 'enzyme';
+/* tslint:disable:no-unused-variable */
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx]: Can you remove these lines, or just revert this file entirely since you didn't end up making any changes here?

Comment (ConorWuertz) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.test.tsx]: will do

**Comment by cliffkoh** [comment]
Hmm sorry this took so long to merge. @ConorWuertz you have the permissions to hit the merge button right?

**Comment by MdAmeerMind** [comment]
Hi,
Narrator still narrating combobox menu option text twice for (Chrome + NVDA) (JAWS + IE) ,
It is reproducible on test release site provided above.
https://fabricweb.z5.web.core.windows.net/oufr/6.118.0/#/examples/ComboBox#Variants
And also on demo site.
https://developer.microsoft.com/en-us/fabric#/components/ComboBox#Variants

As mention in above comments, fix is released in `office-ui-fabric-react@v6.118.0` , but I am still able to  reproduce bug using `office-ui-fabric-react@6.154.0`

**Comment by natalieethell** [comment]
Hey @MdAmeerMind! This is actually expected for now. If you look at the discussion above, we decided it's best to keep both the `title` and `aria-label` attributes for those relying on `title` for overflow text behavior.

@cliffkoh:
> Hi @ConorWuertz, thanks for the link and I agree with the point you're making.
> 
> However, even though the reliance on title for tooltip purposes is not great, this change here is potentially (and very plausibly) disruptive to everyone already relying on this. All of a sudden, you can no longer mouse over a clipped text in production apps using Fabric Dropdown where it was previously possible.
> 
> I recommend preserving the current treatment of title until such point @ecraig12345 rewrites Dropdown and ComboBox and we can do something better here (and be in a better position to make breaking changes..)
https://github.com/OfficeDev/office-ui-fabric-react/pull/7409#discussion_r242296595

@natalieethell:
> You make a good point @ConorWuertz! However, I agree with @cliffkoh here, we should keep title as is for now.

> Ideally, down the line we wouldn't rely on title for overflow and would instead use something like Tooltip. This would not only show on mouse over, but also on focus, which adds visiblity for keyboard-only users and touch-only users.
https://github.com/OfficeDev/office-ui-fabric-react/pull/7409#discussion_r242378612
