### PR TITLE
[hover card] fix bug for quickly enter/leave card cannot dismiss card correctly

### LINKED ISSUE #3605: [hover card] if I quickly enter/leave the hover card, the card does not dismiss as expected sometimes
### Bug Report

- __Package version(s)__: latset

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

1. hover to trigger a card
2. use mouse quickly move through the card
3. the card will be opened again and cannot dismiss

#### Actual behavior:

hover dismiss

### PR DESCRIPTION
**Pull request by MirandaGe**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3605 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

1. setState cannot be used in componentWillUpdate
2. did not clear dismiss timer correctly
3. setState according to prev state should be done in callback function in setState.

#### Focus areas to test

tested on local build branch

### CODE REVIEW

**Comment by Jahnp** [comment]
@atneik @chaofeng2014--can one of you take a look at this?

File: packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.tsx [hunk 1]
```diff
@@ -162,14 +162,17 @@ export class HoverCard extends BaseComponent<IHoverCardProps, IHoverCardState> {
 
   @autobind
   private _executeCardOpen(ev: MouseEvent) {
+    this._async.clearTimeout(this._openTimerId);
```
Comment (atneik) [inline packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.tsx]: Should we move `this._async.clearTimeout(this._dismissTimerId)` in `_cardOpen` here for consistency with `_executeCardDismiss`?
