### PR TITLE
merge-styles: insert style tag at placeholder or as first element of head

### LINKED ISSUE #9786: CSS loaded in wrong order?
We had this problem since a long while, currently we're using `6.134.0`. However to verify that this still occurs I even upgraded to the latest version (`7.8.2`).

Setup:
 - Typescript react app (with latest `Create React App`)

Problem:
For some reason on **production builds** (with `npm start` it works!) the order of the CSS which is loaded is wrong, which leads to styling-problem. Up until now we could somehow always workaround the problem, by specifying a more accurate CSS identifier for our own classes, but now this even happens with the fabric core classes `ms-bgColor....`.

Example:

In the following screen we have a `DefaultButton` which has an additional custom CSS class applied as well as a `ms-bgColor` class....as you can see the `root-38` class overrides the styles from the more specific classes:
image

I read that the `ms-bgColor` classes are not the recommended way of doing things anymore...ok so I did it via the `getTheme()` (additionally done in styled components, but shouldn't matter I guess):

```
const StyledDefaultButton = styled(DefaultButton)`
  background-color: ${getTheme().palette.neutralLight};
  & :hover {
    background-color: ${getTheme().palette.neutralQuaternaryAlt};
  }
`;
``` 

But the result is the same:
image

Any idea what could cause this?
I'm not sure if this is related to UI fabric or something other could be the problem.
However I have no idea what it could be...I'm hoping someone can point me in the right direction.

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #9786 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Insert first `style` element after a placeholder or as first child of the `head` element.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9816)

### CODE REVIEW

File: packages/merge-styles/src/Stylesheet.ts [hunk 1]
```diff
@@ -292,12 +293,30 @@ export class Stylesheet {
       }
     }
     if (this._lastStyleElement && this._lastStyleElement.nextElementSibling) {
```
Comment (dzearing) [inline packages/merge-styles/src/Stylesheet.ts]: I think this logic needs to be tweaked.

```tsx
const appendAfter = (elementToAppend, target) => {
  if (target.nextElementSibling) {
    target.insertBefore(elementToAppend, target.nextElementSibling);
  else {
    target.appendChild(elementToAppend);
  }
}

if (this._lastStyleElement) {
  appendAfter(styleElement, this._lastStyleElement);
} else {
  if (head.childNodes[0]) {
    head.insertBefore(...);
  else {
    head.appendChild(...);
  }
}
```
