### PR TITLE
Fixing aria details for dropdown

### LINKED ISSUE #1076: [Accessibility] [DropDown] Aria check fail for aria-required-children
The drop down component fails accessibility validation for aria-required-children.

Details:
https://dequeuniversity.com/rules/axe/2.1/aria-required-children

Error displayed:
image

### PR DESCRIPTION
**Pull request by prmittal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1076 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Added role textbox to span and moved aria-readonly there.
Check for aria-owns component since it will not be available if dropdown is not expanded.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -148,6 +147,8 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
             }
             key={ selectedIndex }
             aria-atomic={ true }
+            role='textbox'
+            aria-readonly='true'
           >
```
Comment (prmittal) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Aria guidelines for Combobox state:

The first element within the combobox is an input text field and is responsible for managing the keyboard focus between the text field and the list as well as displaying the list. The text field is in the tab order. If you create a text field without using a standard HTML text field form control then ensure that it is in the tab order.

If the text field is not editable it must have have aria-readonly = true.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -148,6 +147,8 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
             }
             key={ selectedIndex }
             aria-atomic={ true }
+            role='textbox'
+            aria-readonly='true'
```
Comment (prmittal) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Aria guidelines for Combobox state:

The first element within the combobox is an input text field and is responsible for managing the keyboard focus between the text field and the list as well as displaying the list. The text field is in the tab order. If you create a text field without using a standard HTML text field form control then ensure that it is in the tab order.

If the text field is not editable it must have have aria-readonly = true.

Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: @jspurlin Still think we will be adding confusion by not just making Dropdown editable. Just letting you know about this line here, because if we did make dropdown editable, then we'd need to pipe that into this aria tag.

Comment (jspurlin) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: If we want to overhaul dropdown then we can to allow it to be editable (allowFreeform) as well as autoComplete then we can do that. We'd also need to think about how to handle the fact that there's no placeholder for combobox and onRenderTitle/onRenderPlaceholder introduce broken concepts for the comboBox
