### PR TITLE
Stack: Modifying StackItem so that it can render multiple children

### LINKED ISSUE #7901: Stack.Item doesn't allow for conditional rendering with logical &&
### Environment Information 
 
- __Package version(s): @uifabric/experiments 6.54.2 (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
```jsx
<Stack>
   <Stack.Item>
      { false && <DefaultButton>hello</DefaultButton> }
   </Stack.Item>
</Stack>
```
Produces this error:
```
Type 'false' is not assignable to type 'string | ReactElement<IStackItemProps> | (string | ReactElement<IStackItemProps>)[] | (string & {}) | (string & ReactElement<any>) | (string & ReactNodeArray) | (string & ReactPortal) | ... 14 more ... | undefined'.ts(2322)
StackItem.types.d.ts(21, 5): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & IStackItemProps & { children?: ReactNode; }'
```
   

 
#### Expected behavior:
I expected `<Stack.Item>` to be able to hold all children items that react allows for.
It seems the `children` property definition on `IStackItemProps` is too strict: `children?: (React.ReactElement<IStackItemProps> | string)[] | React.ReactElement<IStackItemProps> | string;`

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? If I knew what the correct fix was, sure.
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7901 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

An array wrapped by `StackItem` was only rendering one child. This PR changes this so that `StackItem` can render multiple children. As part of this, the representation of the `StackItem` `root` slot has been changed from a `span` to a `div` and the tests have been updated.

The exposed `children` property in `StackItem` has also been deleted since we can now use the `children` property inherited from `IComponent`.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7908)

### CODE REVIEW

File: packages/experiments/src/components/Stack/StackItem/StackItem.tsx [hunk 1]
```diff
@@ -5,17 +5,18 @@ import { IStackItemComponent, IStackItemProps, IStackItemSlots } from './StackIt
 import { styles } from './StackItem.styles';
 
 const view: IStackItemComponent['view'] = props => {
-  const childNodes: React.ReactElement<{}>[] = React.Children.toArray(props.children) as React.ReactElement<{}>[];
+  const { children } = props;
+  const childNodes: React.ReactElement<{}>[] = React.Children.toArray(children) as React.ReactElement<{}>[];
   const first = childNodes[0];
   if (!first) {
     return null;
   }
```
Comment (JasonGore) [inline packages/experiments/src/components/Stack/StackItem/StackItem.tsx]: I know it's not directly part of this PR, but I'm not sure I understand what lines 9-13 are doing, particularly since I don't see `childNodes` being used anywhere else. Could this instead simply be: 

```tsx
if (React.Children.count(children) < 1) {
    return null;
}
```

File: packages/experiments/src/components/Stack/StackItem/StackItem.types.ts [hunk 2]
```diff
@@ -23,11 +23,6 @@ export interface IStackItemProps extends IStackItemSlots, IStyleableComponentPro
    */
   className?: string;
 
-  /**
-   * @internal Internal use only - gives the Stack component a handle on the children of its Stack.Items
-   */
-  children?: (React.ReactElement<IStackItemProps> | string)[] | React.ReactElement<IStackItemProps> | string;
-
```
Comment (JasonGore) [inline packages/experiments/src/components/Stack/StackItem/StackItem.types.ts]: Nice! Thanks for recognizing and using the inherited typing.

Comment (JasonGore) [reply packages/experiments/src/components/Stack/StackItem/StackItem.types.ts]: (And I'm glad to see it's permissive enough to fix this issue. 😄 )

File: packages/experiments/src/components/Stack/StackItem/StackItem.tsx (hunk 1 above)
Comment (khmakoto) [reply packages/experiments/src/components/Stack/StackItem/StackItem.tsx]: Yeah, we should probably just do that.

**Comment by kkjeer** [comment]
@dzearing if I recall correctly, the fact that StackItem only renders one child was a design decision made early on in its development. I'm slightly concerned about removing this behavior - what are your thoughts?

**Comment by khmakoto** [comment]
@kkjeer 

I discussed this with @dzearing when I was going to get started on this PR and this is what he said:

>On `Stack.Item`, if they give an array, we should pass through especially because `Stack.Item` renders a `div` wrapper, and not just render the first child.
>The reason we originally did only the first child was because we didn't have a `div` wrapper to stick a classname on, and we needed to inject classname onto something, so we cloned first child with the extra classname.
>Now that everything is in a `div` wrapper we can just render the children, but, if we ever do the classname injection "optimization" to avoid the extra element, then we need to reconsider.

File: packages/experiments/src/components/Stack/StackItem/StackItem.tsx [hunk 3]
```diff
@@ -5,17 +5,16 @@ import { IStackItemComponent, IStackItemProps, IStackItemSlots } from './StackIt
 import { styles } from './StackItem.styles';
 
 const view: IStackItemComponent['view'] = props => {
-  const childNodes: React.ReactElement<{}>[] = React.Children.toArray(props.children) as React.ReactElement<{}>[];
-  const first = childNodes[0];
-  if (!first) {
+  const { children } = props;
+  if (React.Children.count(children) < 1) {
```
Comment (KevinTCoughlin) [inline packages/experiments/src/components/Stack/StackItem/StackItem.tsx]: Nice change! Can `props.children` ever be negative? If not, perhaps this conditional could be:

```suggestion
  if (React.Children.count(children) === 0) {
```

Comment (JasonGore) [reply packages/experiments/src/components/Stack/StackItem/StackItem.tsx]: Since the only valid values we want to allow are `> 1` I tend to prefer being defensive and excluding all unnecessary scenarios, even if `React.Children.count` *currently* returns 0. Probably a pretty minor concern in this specific example, but assuming there isn't a perf difference, I like being more defensive and it's why I suggested `< 1`.

**Comment by dzearing** [comment]
It drives me nuts when I can't reply directly to a comment! But yes @kkjeer as @khmakoto mentioned, it was due to when we didn't have the div wrapper. If we ever optimize that out again, we'd have to reconsider how the style applies to each child.
