### PR TITLE
withViewport: use ResizeObserver if available

### LINKED ISSUE #5019: Changing css display on element containing detailsview causes detailsview not to render
### Bug Report

- __Package version(s)__: 5.90.0
- __Browser and OS versions__: chrome macOs

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

DetailView does not render content if it is in a div which had display: none and is changed to display: block. 

#### Actual behavior:

DetailView does not render content

#### Expected behavior:

DetailView shouldrender content

### If applicable, please provide a codepen repro:

press toggle display (nothing will be rendered) then resize window to force render

https://codepen.io/anon/pen/gKOjQQ

### PR DESCRIPTION
**Pull request by billytrend**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5019
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Changes event listener from window size detection to viewport size detection

#### Focus areas to test

https://codepen.io/anon/pen/gKOjQQ (as explained in issue)

### CODE REVIEW

**Comment by billytrend** [comment]
This changes uses ResizeObserver which appears to be not particularly compatible accross browsers. How should this be handled. Would it be best to add a polyfill?

**Comment by christiango** [comment]
Unfortunately resize observer isn't ready for prime time yet due to limited browser support. I'd have concerns over how the polyfills for the API would perform as well. Instead of relying on resize observer to be available, can you leverage it when it exists and fall back to the previous behavior when it does not?

**Comment by billytrend** [comment]
@christiango , Made the change conditional on compatibility now. Is this the sort of thing you meant?

**Comment by christiango** [comment]
Yup, but I'm not super familiar with the usages of this decorator, so we should probably have other eyes on this as well.

File: packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx [hunk 1]
```diff
@@ -48,7 +48,12 @@ export function withViewport<TProps extends { viewport?: IViewport }, TState>(Co
           leading: false
         });
 
-      this._events.on(window, 'resize', this._onAsyncResize);
+      if (window.ResizeObserver) {
+        new window.ResizeObserver(this._onAsyncResize).observe(this.state.viewport);
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx]: This never gets unobserved.

File: packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx [hunk 2]
```diff
@@ -42,8 +42,16 @@ export function withViewport<TProps extends { viewport?: IViewport }, TState>(
         leading: false
       });
 
-      this._events.on(window, 'resize', this._onAsyncResize);
-      const { skipViewportMeasures } = this.props as IWithViewportProps;
+      if (window.ResizeObserver) {
+        new window.ResizeObserver(this._onAsyncResize).observe(this.state.viewport);
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx]: this observe is never unobserved.

**Comment by billytrend** [comment]
I would absolutely get these changes done however, I noticed that the travis build fails because window.ResizeObserver is disallowed. Would that make this approach impossible? (without changes in the PR checks)

image

**Comment by dzearing** [comment]
Nope; I believe you just need to case window as something that has resizeobserver typings.

```tsx
interface IWindowWithResizeObserver {
  ResizeObserver: {
    observe: ...
    unobserve: ...
  }
}

(window as IWindowWithResizeObserver).ResizeObserver.observe(...)
```

File: packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx [hunk 3]
```diff
@@ -42,8 +42,16 @@ export function withViewport<TProps extends { viewport?: IViewport }, TState>(
         leading: false
       });
 
-      this._events.on(window, 'resize', this._onAsyncResize);
-      const { skipViewportMeasures } = this.props as IWithViewportProps;
+      if (window.ResizeObserver) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx]: I would recommend calling `getWindow` api from `../../Utilities`. There are cases where window might not be available.

Comment (dzearing) [reply packages/office-ui-fabric-react/src/utilities/decorators/withViewport.tsx]: (perhaps less of a concern since you're doing this in `componentDidMount`, but good for consistency.

**Comment by dzearing** [comment]
Ping. @billytrend

**Comment by dzearing** [comment]
Thanks @billytrend !
