### PR TITLE
Image: Add prop to maximize frame to parent element

### LINKED ISSUE #767: Image: Cover style not computed when props change
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: N/A

#### Describe the issue:

When the image component receives props, it checks for the presence of the `width` and `height` props before computing a new cover style. The problem is that PR #712 introduced a feature where the image frame can be measured in the DOM, rather than looking at the props. In this case the cover style should still be calculated.

#### Actual behavior:

When changing the image to one that has different proportions, a new cover style (portrait or landscape) is not calculated.

#### Expected behavior:

The cover style should always be calculated, even if the `width` and `height` props are not provided.

### PR DESCRIPTION
**Pull request by mikewheaton**
#### Pull request checklist

- [x] Addresses an existing issue: #767
- [x] Include a change request file if publishing
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests

#### Description of changes

Adds a new prop, `maximizeFrame`, that causes the Image frame to fill its parent container. This makes it easy to have an image that adapts to a changing layout, where the exact dimensions are unknown.

This also fixes #767 by calling `_computeCoverStyle()` whenever new props are received, even if `width` and `height` aren't provided. This fixes a bug where the cover style wasn't computed for images that have their width and height set to percentages or other values based on the parent element.

#### Focus areas to test

Use an ImageFit of 'cover' or 'contain'. Resize the image's container while using `shouldMaximizeFrame` and confirm that the correct cover style is applied.

### CODE REVIEW

**Comment by mikewheaton** [comment]
I'll see if I can get a test working to validate this change.

File: packages/office-ui-fabric-react/src/components/Image/Image.tsx [hunk 1]
```diff
@@ -61,13 +61,9 @@ export class Image extends BaseComponent<IImageProps, IImageState> {
   }
 
   public componentWillReceiveProps(nextProps: IImageProps) {
+    // If the image is not loaded, recompute the cover style.
     if (this.state.loadState === ImageLoadState.loaded) {
```
Comment (mikewheaton) [inline packages/office-ui-fabric-react/src/components/Image/Image.tsx]: Does this if condition make sense? It seems like we should be checking if the image's source has changed to determine whether we need to computer the cover style.

File: packages/office-ui-fabric-react/src/components/Image/Image.Props.ts [hunk 2]
```diff
@@ -22,6 +22,11 @@ export interface IImageProps extends React.HTMLProps<HTMLImageElement>  {
    * Image source to display if an error occurs loading the image indicated by src.
    */
   errorSrc?: string;
+
+  /**
+   * If true, the image frame will expand to fill its parent container.
+   */
+  shouldMaximizeFrame?: boolean;
```
Comment (mikewheaton) [inline packages/office-ui-fabric-react/src/components/Image/Image.Props.ts]: Naming is hard. Does this make sense?

Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Image/Image.Props.ts]: I think that this should really be another enum. So I would add stretch to the ImageFit enum. Additionally there is already some css that does height: 100% and width: 100% in 
```
.ms-Image-image--scaleWidthHeight {
  height: 100%;
  width: 100%;
}
```

So you might be able to leverage that or rename it to stretch. I'm not sure about renaming it though.

File: packages/office-ui-fabric-react/src/components/Image/Image.tsx (hunk 1 above)
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Image/Image.tsx]: It looks like computeCoverStyle looks at imageFit, width, and height. So we should only re-evalutate if one of those changes and the image is loaded.

File: packages/office-ui-fabric-react/src/components/Image/Image.Props.ts (hunk 2 above)
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Image/Image.Props.ts]: oh! Ignore this, I think I misunderstood.

File: packages/office-ui-fabric-react/src/components/Image/Image.tsx (hunk 1 above)
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Image/Image.tsx]: I just needed to read the bug to understand this, your solution is correct.

File: packages/office-ui-fabric-react/src/components/Image/Image.Props.ts (hunk 2 above)
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Image/Image.Props.ts]: Okay, just name this maximizeFrame. Other than that I think it's all good!

Comment (mikewheaton) [inline packages/office-ui-fabric-react/src/components/Image/Image.Props.ts]: Sounds good! Yeah, I know the props and classes are getting confusing as sometimes we're talking about the "frame" and sometimes the "image".
