### PR TITLE
Picker Fixes: fixed suggestionsHeaderText bug and backspace bug.

### LINKED ISSUE #2613: [PeoplePicker] "Delete" keypress event is not stopped from propagating
### Bug Report

- __Package version(s)__: 4.30.0
- __Browser and OS versions__: Affects all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: ODSP

#### Describe the issue:

When a user deletes a selected person in the `PeoplePicker`, the "delete" key is not stopped from propagating, like other keys in the picker are. Is this by design or an oversight when it was added?

Offending code:
https://github.com/OfficeDev/office-ui-fabric-react/blob/c3dcef2f6aaa12705dec55b9fd60476daf6dbb31/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L423-L433

#### Actual behavior:

"Delete" keypress event propagates and user is prompted to delete the file or folder that they have selected in ODSP.

#### Expected behavior:

"Delete" keypress event doesn't get propagated, and only the selected item is deleted from the picker.

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #2613 #2754 
- [ ] Include a change request file using `$ npm run change`

#### Description of changes
 Fixed a bug where suggestionsHeaderText would not display, also fixed backspace event propagating even when it was handled.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx [hunk 1]
```diff
@@ -91,8 +92,10 @@ export class Suggestions<T> extends BaseComponent<ISuggestionsProps<T>, {}> {
           { noResultsFoundText }
         </div> : null;
     };
-
-    let headerText = isMostRecentlyUsedVisible && mostRecentlyUsedHeaderText ? mostRecentlyUsedHeaderText : null;
+    // MostRecently Used text should supercede the header text if it's there and available.
+    let headerText = isMostRecentlyUsedVisible && mostRecentlyUsedHeaderText ?
+      mostRecentlyUsedHeaderText :
+      suggestionsHeaderText ? suggestionsHeaderText : null;
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: can this be improved? it's hard for me to read this logic.

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: Done.
