### PR TITLE
Checkbox: support for aria attributes

### LINKED ISSUE #2410: Cannot pass aria-label into Checkbox component
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Planner

#### Describe the issue:

I am trying to get the screen reader to read more information than we show in the label text by passign in an aria label, but I cannot figure out how.  The inputProps object will not accept ariaLabel as a parameter.

### PR DESCRIPTION
**Pull request by mdahamiwal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2410 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
Checkbox doesn't allow passing aria attributes. Adding attributes to checkbox props.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx [hunk 1]
```diff
@@ -115,8 +118,11 @@ export class Checkbox extends BaseComponent<ICheckboxProps, ICheckboxState> impl
         onBlur={ this._onBlur }
         aria-checked={ isChecked }
         aria-disabled={ disabled }
+        aria-label={ ariaLabel }
+        aria-labelledby={ ariaLabelledBy }
+        aria-describedby={ ariaDescribedBy }
       >
-        <label className={ this._classNames.label } htmlFor={ this._id } >
+        <label className={ this._classNames.label } htmlFor={ ariaLabelledBy || ariaLabel ? undefined : this._id } >
```
Comment (whykushal93) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx]: Could you explain this part of the code for me please ?

Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx]: I'm a bit unsure what the intent is here.

As a customer, if I provide `ariaLabelledBy` pointing to my customized label element, why do i want the Checkbox's label element to have htmlFor pointing to that customized label element? Is this correct?

**Comment by mdahamiwal** [comment]
That's right, if in case customer wants to point to another label using `ariaLabelledby` or `ariaLabel`, we should avoid attaching htmlFor as that links the label with button element. Its rarely the case but we should have the flexibility :)

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts [hunk 2]
```diff
@@ -75,6 +75,21 @@ export interface ICheckboxProps extends React.ButtonHTMLAttributes<HTMLElement |
   theme?: ITheme;
 
   /**
+   * Accessibile label for the checkbox.
+   */
+  ariaLabel?: string;
+
+  /**
+   * ID for element that contains label information for the checkbox. By default, passed-in 'label' property with be used.
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: "with" -> "will"?
This description is still confusing, I would just leave off the second sentence.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts [hunk 3]
```diff
@@ -75,6 +75,21 @@ export interface ICheckboxProps extends React.ButtonHTMLAttributes<HTMLElement |
   theme?: ITheme;
 
   /**
+   * Accessibile label for the checkbox.
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: spelling

Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: might want to indicate that by default the text for the label that's passed in will be used to label the control, so we're not implying that you're not meeting accessibility standards by not using this prop

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx (hunk 1 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.tsx]: Okay, looks like setting it to `undefined` would regress click behavior. If we set explicit `aria-label` the browser overrides the `htmlFor` binding and solves the confusion. Thanks for the review :)

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 2 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: Thanks for catching this !!

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 3 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: Sure, that make sense.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts [hunk 4]
```diff
@@ -75,6 +75,22 @@ export interface ICheckboxProps extends React.ButtonHTMLAttributes<HTMLElement |
   theme?: ITheme;
 
   /**
+   * Accessible label for the checkbox. Defaults to 'label' property value.
+   */
+  ariaLabel?: string;
+
+  /**
+   * ID for element that contains label information for the checkbox.
+   * Defaults to 'label' property value.
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: Defaults to point to the label.

File: packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.Basic.Example.tsx [hunk 5]
```diff
@@ -42,7 +42,9 @@ export class CheckboxBasicExample extends React.Component<{}, ICheckboxBasicExam
             onBlur: () => { console.log('Uncontrolled checkbox is blured'); }
           } }
           styles={ styles }
+          ariaDescribedBy={ 'descriptionID' }
         />
+        <label id='descriptionID' className='screenReaderOnly'>Uncontroller checkbox description</label>
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/examples/Checkbox.Basic.Example.tsx]: you need to generate a dynamic id here so multiple instances don't get the same id

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts [hunk 6]
```diff
@@ -75,6 +75,22 @@ export interface ICheckboxProps extends React.ButtonHTMLAttributes<HTMLElement |
   theme?: ITheme;
 
   /**
+   * Accessible label for the checkbox. Defaults to 'label' property value.
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: I don't see code that assigns the label's value to this property by default?

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 4 above)
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: Also I'm not seeing the behavior described here in code...

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 6 above)
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: Are these props necessary? Aren't they part of ButtonHTMLAttributes?

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: and I agree with the default question.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 4 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: we are not pointing, instead its linked using `htmlFor` on the label.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 6 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: > Are these props necessary?

Yes, ButtonHTMLAttributes doesn't have definition of `aria-*` attributes. Another way would be to have an interface inherited from ButtonHTMLAttributes and that contains additional `aria-*`. I like the `aria-attributes` to be at control level to make them more visible.

> I don't see code that assigns the label's value to this property by default?

`htmlFor` on the label takes care of linking the label with control.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 4 above)
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: No, what I mean is this property has no default value set in code, yet the comment here implies that it does. Additionally, if it DOES have a default value, its value should be the ID of the label, not the contents of the label.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 6 above)
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: There is no code that assigns a default value to the ariaLabel property defined here, contrary to what the comment states.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 4 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: @phkuo, I see your point but as I said `htmlFor` automatically makes sure that label for control is assigned for accessibility purpose. I really want to be descriptive to users to avoid confusion here. How about : "By default, label prop provides the label information" ? Does that sound okay ?

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 6 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: @phkuo, should we say "By default, 'label' property value is used"?

Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: No, because there is no default. By default this has no value and does not appear on the control.

File: packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts (hunk 4 above)
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: I would prefer we leave out any mention of default behavior here. It's unnecessary and potentially confusing. The default behavior is that everything just works without further intervention from the user.

Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.Props.ts]: cool, I've removed all "default" statements. Its ready for another look.
