### PR TITLE
Fixing deletion of disabled tags in tagpicker

### LINKED ISSUE #2831: TagPicker component - tags can be deleted with keyboard even when component is in disabled state
### Bug Report

- __Package version(s)__:  4.44
- __Browser and OS versions__: Chrome, Edge on Windows 10

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low): Normal 

#### Describe the issue:
When the tagPicker control is in disabled state, user can click on a tag and delete it. 
Disabled state should work as read only mode.

#### Actual behavior:

TagPicker Component is in disabled state, click on a tag and press delete/backspace
- Tag gets deleted

#### Expected behavior:

TagPicker Component is in disabled state, click on a tag and press delete/backspace
- Tag should not get deleted.

### PR DESCRIPTION
**Pull request by techninja24**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2831 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

When the control is disabled delete and backspace should not delete tags

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -431,7 +433,7 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
           }
           this.suggestionStore.removeSuggestion(this.suggestionStore.currentIndex);
           this.forceUpdate();
-        } else {
+        } else if(!this.props.disabled) {
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: shouldn't we just skip this entire if statement if it is disabled? Is there a situation where a disabled picker would need to remove a suggestion?

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: I agree, this should be first.

Comment (techninja24) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: That makes sense. My bad I missed it. 
Floated a new iteration.
