### PR TITLE
Breadcrumb resizegroup refactor

### LINKED ISSUE #1824: Breadcrumb - Issue with styling
Repro steps:

1) Browse to http://codepen.io/nikhilexe/pen/GmXoqZ?editors=0110
2) You can see one breadcrumb item
3) Now apply css on this
.my-custom-class {
display: inline-block;
}

Now with this, sometime it doesn't show the item itself or if you zoom in further then it vanishes.

Ideally it should always show one item. Not sure what display css causing issue.

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1824
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Remove resizing logic from breadcrumb, and move it into a resize group. Also exposed onReduceData to allow users to remove reducing function

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@christiango adding you to this PR as someone who's worked with resizeGroup a bit. I took advantage of being able to override the onReduceData, and what happens when you return undefined to the function.

We COULD expose it as a Boolean, and set onReduceData to () => undefined when true, but this gives a bit more flexibility if someone wants to change the reduction logic.

File: packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx [hunk 1]
```diff
@@ -3,76 +3,83 @@ import {
...
-      this._updateRenderedItems();
+  @autobind
+  private _onReduceData(data: IBreadCrumbData): IBreadCrumbData {
+    let { renderedItems, renderedOverflowItems } = data;
+    let movedItem = renderedItems[renderedItems.length - 1];
+
+    if (movedItem !== undefined) {
+      return assign({}, data, {
+        renderedItems: renderedItems.slice(0, -1),
+        renderedOverflowItems: renderedOverflowItems.concat(movedItem),
```
Comment (christiango) [inline packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx]: nit: I'd use array spread here: [...renderedOverflowItems, movedItem]

File: packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx [hunk 2]
```diff
@@ -3,76 +3,83 @@ import {
...
-    if (!this._breadcrumbItemWidths) {
-      this._updateItemMeasurements();
-      this._updateRenderedItems();
+  @autobind
+  private _onReduceData(data: IBreadCrumbData): IBreadCrumbData {
+    let { renderedItems, renderedOverflowItems } = data;
+    let movedItem = renderedItems[renderedItems.length - 1];
+
+    if (movedItem !== undefined) {
+      return assign({}, data, {
```
Comment (christiango) [inline packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx]: I'd also use object spread here instead of assign.

File: packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx [hunk 3]
```diff
@@ -3,76 +3,83 @@ import {
...
+      />
+    );
   }
 
-  public componentDidUpdate(prevProps: IBreadcrumbProps, prevStates: IBreadcrumbState) {
-    if (!this._breadcrumbItemWidths) {
-      this._updateItemMeasurements();
-      this._updateRenderedItems();
+  @autobind
+  private _onReduceData(data: IBreadCrumbData): IBreadCrumbData {
```
Comment (christiango) [inline packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx]: Technically this returns IBreadCrumbData | undefined.
