### PR TITLE
A variety of picker fixes

### LINKED ISSUE #5915: People picker selects first item when keyboard user tabbing through
### Bug Report 
 
- __Package version(s)__: current as of 8/12/2018
- __Browser and OS versions__: any
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  Normal, but potential a11y impact
 
Products/sites affected: (if applicable) Unknown
 
#### Describe the issue:

Go to people picker page here: https://developer.microsoft.com/en-us/fabric#/components/peoplepicker

Tab to the people picker. 
 
#### Actual behavior:

When the people picker receives focus, a popup appears with the initial item selected.
Hitting tab will end up selecting this item, and dismissing the popup
It is only when tab is hit again that focus moves to the next control.

 
#### Expected behavior:
 
A keyboard user should be able to tab through and shift-tab backwards though any control without having unexpected side-effects. If a keyboard user is tabbing from some control before the people picker to some control after, in tabbing through, they can end up inadvertently selecting an additional item.

To avoid this, the user may have to reverse tab and delete the extra item; or when tabbing forwards, use ESC to dismiss the popup before moving onwards. This is not always easy or obvious when rapidly tabbing around a page. 

Perhaps the ideal situation here is that the popup should initially appear with no item selected; and in this no-selection state, tab should dismiss it and move focus to the next control. Tab then only selects the current item if the user has use the arrow keys or typed in text to trigger an intentional selection.

### If applicable, please provide a codepen repro:
 
See repro above on Fabric components page.

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5915 #5286 #5042 #1012 #3860 #4040
- [x] Include a change request file using `$ npm run change`

#### Description of changes

1. Fixes the first element not being read off.
2. Fixes tabbing through the picker and having the first item automatically suggestions
3. Fixes problem where a user couldn't tell what items were already selected.
4. Fixes an issue where scan mode wouldn't correctly navigate to the list element.
5. Fixes the suggestion classname props not being passed all the way through.
6. Fixes the pickers so it is now correctly labeled as a combobox.

Also, removes the wait time for the loading icon to appear, it will now appear immediately instead of first waiting a few miliseconds. This makes it appear to work more cleanly.

Things that should already work: 
1. Being able to add an aria-label to the input element will fix an issue when instructions are not read out. Add the aria-label to input props.
2. It will announce when results are found.

Things that this doesn't fix:
It still doesn't announce when a user is removed or selected.
It doesn't announce when the list is updated if there is no loading.

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by JasonGore** [comment]
Do you think this PR fixes #4817 too?

**Comment by betrue-final-final** [comment]
I'm finding some color changes I'd like to sync with you on.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -26,6 +26,12 @@ export interface IBasePickerState {
   selectedIndices?: number[];
 }
 
+export const enum PickerAriaIdEnum {
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: >PickerAriaIdEnum [](start = 18, length = 16)

Just squinting at the code, why does this need to be exported?

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 2]
```diff
@@ -37,14 +43,21 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
...
+  protected _ariaMap: { [key: number]: string };
+  private _id: string;
 
   constructor(basePickerProps: P) {
     super(basePickerProps);
 
     const items: T[] = basePickerProps.selectedItems || basePickerProps.defaultSelectedItems || [];
 
+    this._id = getId();
+    this._ariaMap = {
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: >_ariaMap [](start = 9, length = 8)

Why not just have an interface for Aria map and avoid the use of enum entirely (again, based on my squinting and getting the impression this enum is entirely internal)

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts [hunk 3]
```diff
@@ -162,11 +162,11 @@ export interface IBasePickerSuggestionsProps {
    */
   noResultsFoundText?: string;
   /**
-   * ClassName for the picker.
+   * Suggestions root Class Name.
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.types.ts]: >Class Name [](start = 22, length = 10)

nit: weird casing

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts [hunk 4]
```diff
@@ -54,9 +54,13 @@ export interface ISuggestionsProps<T> extends React.Props<any> {
...
   createGenericItem?: () => void;
   /**
-   * The CSS classname of the suggestions list.
+   * The CSS classname of the suggestions root.
    */
   className?: string;
+  /**
+   * The CSS classname of the suggestionslist
+   */
+  suggestionsClassName?: string;
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts]: >suggestionsClassName [](start = 2, length = 20)

Kind of an anti-pattern by this point in time with the direction most other Fabric component is moving (towards `styled`/merge-styles)...

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx (hunk 1 above)
Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: For anything that want's to subclass.

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts (hunk 4 above)
Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts]: This has been expected to be there, and just not used.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx (hunk 2 above)
Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: I waffled about this. I think I chose wrong, I'll go back and make it an interface.

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts (hunk 4 above)
Comment (cliffkoh) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts]: Right, I understand that reasoning for existing hooks but to be adding more is kind of moving in the opposite direction..

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx (hunk 1 above)
Comment (cliffkoh) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: I'm still confused - how are the sub classes using this? 

It still seems you could still also avoid the enum entirely (it has bundle size impact). If really using an enum, you should give each enum property an explicit value (e.g. = 0, = 1, etc.)

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts (hunk 4 above)
Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.types.ts]: No this isn't adding more, my point is that this is an existing hook. It's already given as an option in the IBasePickersuggetsionsProps, it just never got anywhere.

**Comment by joschect** [comment]
@JasonGore per my description this does not fix #4817

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 5]
```diff
@@ -26,10 +26,10 @@ export interface IBasePickerState {
   selectedIndices?: number[];
 }
 
-export const enum PickerAriaIdEnum {
-  selectedSuggestionAlert,
-  selectedItems,
-  suggestionList
+export interface IPickerAriaIds {
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Would a type literal be more appropriate, given that as far as I can tell this is internally defined and not passed in? 

Also since you're exporting it, please add JSDoc :) To the properties but also to the interface or type
