### PR TITLE
Grouped list aria label

### LINKED ISSUE #5113: In Grouped List chevron icon aria label is not defined
**Bug Report**
**Describe the issue:**
**Grouped List chevron aria label is not defined:**
I have used the Grouped List , its ariaLabel is not defined which is causing Keros bug saying "button must have described text"

**Issue Details:**
Used Grouped List and its causing keros bug saying "button must have described text"

Actual behavior:
Keros Bug is visible using grouped list.
Expected behavior:
Keros tool should not show any bug when using grouped list.

### PR DESCRIPTION
**Pull request by natalieethell**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #5113 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

GroupedList: add expandCollapseButtonProps prop to GroupHeader so an aria-label can be included.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx [hunk 1]
```diff
@@ -16,6 +16,10 @@ export interface IGroupHeaderState {
 }
 
 export class GroupHeader extends BaseComponent<IGroupDividerProps, IGroupHeaderState> {
+  public static defaultProps: IGroupDividerProps = {
+    expandCollapseButtonProps: { 'aria-label': 'expand collapse group' }
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: Hmm, since I don't know for sure, is our de facto standard to have default English values instead of none?

File: common/changes/office-ui-fabric-react/groupedListAriaLabel_2018-06-18-20-59.json [hunk 2]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "office-ui-fabric-react",
+      "comment": "GroupedList: add expandCollapseButtonProps to GroupHeader so an aria-label can be included\"",
+      "type": "patch"
```
Comment (JasonGore) [inline common/changes/office-ui-fabric-react/groupedListAriaLabel_2018-06-18-20-59.json]: Should probably be minor since API changed

File: packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx (hunk 1 above)
Comment (natalieethell) [reply packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: Just spoke with @micahgodbolt . I recently made a [change in SearchBox](https://github.com/OfficeDev/office-ui-fabric-react/pull/5180) that also uses a default English value for its ariaLabel. It seems that it's okay for now and in the future we'll move towards a language file.

File: packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.types.ts [hunk 3]
```diff
@@ -262,4 +262,7 @@ export interface IGroupDividerProps {
 
   /** Override which allows the caller to provider a custom title. */
   onRenderTitle?: IRenderFunction<IGroupDividerProps>;
+
+  /** Props for expand/collapse button */
+  expandCollapseButtonProps?: React.HTMLAttributes<HTMLButtonElement>;
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.types.ts]: it appears that we're calling this the "showAll" , right? If that's correct, can we use that as the type name?

File: packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx [hunk 4]
```diff
@@ -94,6 +99,7 @@ export class GroupHeader extends BaseComponent<IGroupDividerProps, IGroupHeaderS
             type="button"
             className={css('ms-GroupHeader-expand', styles.expand)}
             onClick={this._onToggleCollapse}
+            {...expandCollapseButtonProps}
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: small nit, but might as well match the terminology here. expandButtonProps instead of expandCollapseButtonProps

File: packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx (hunk 1 above)
Comment (ThomasMichon) [inline packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: We don't want default values since we don't support localization in this repo. We'll need to take it as a prop to the component.

Comment (ThomasMichon) [reply packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: We don't want default values since we don't support localization in this repo. We'll need to take it as a prop to the component.

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: I'm talking to david about the need for moving these strings to a resjson file. Having easy to opt into default strings will fix a lot of accessibility issues, but I agree that our final answer shouldn't be putting those English strings into props.

@ThomasMichon any objection to merging this as is and adding this string to the list needed for the resjson file?

Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.tsx]: I also tended to think we shouldn't have any localization in Fabric, but when I see PRs like Coachmark embedding custom accessibility navigation behavior that requires some amount of instruction to the user I think some kind of default is a good idea.
