### PR TITLE
Ios overlay scroll

### LINKED ISSUE #5621: Safari iOS: Page still scrolls under a surface component.
### Bug Report 
 
- __Package version(s)__: 6.30.0
- __Browser and OS versions__: iOS Safari 
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Microsoft Sway
 
#### Describe the issue:
 
When we have a dialog, blocking or non-blocking, the page still scrolls underneath. I saw this on mobile Safari on a real device and the iOS simulator.
 
#### Actual behavior:

Content is scrollable when a surface component, like a dialog, is on screen.
 
#### Expected behavior:
 
Nothing scrolls when a surface component, like a dialog, is on screen.

I saw that there was a fix for all browsers last year: https://github.com/OfficeDev/office-ui-fabric-react/pull/1306
However, it doesn't seem to be working on iOS Safari anymore.

### PR DESCRIPTION
**Pull request by kkjeer**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5621 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Update the disableBodyScroll and enableBodyScroll utility functions to disable and enable body scrolling on ios, using the ontouchmove handler. The Overlay component uses disableBodyScroll and enableBodyScroll, and the Modal component uses Overlay.

Add an allowScrollOnElement function that allows the user to scroll within an element while still preventing body scrolling. Modal and Panel use this function to allow themselves to be scrolled, while preventing the user from scrolling the body while a Modal or Panel is open.

#### Focus areas to test

1. The body should not be scrollable while a Modal or Panel is open
2. The body should become scrollable again when the Modal or Panel is closed
3. Modals and Panels should be scrollable

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Panel/Panel.tsx [hunk 1]
```diff
@@ -238,6 +244,13 @@ export class Panel extends BaseComponent<IPanelProps, IPanelState> implements IP
     }
   };
 
+  // Allow the user to scroll within the panel but not on the body
+  private _allowScrollOnPanel(elt: HTMLDivElement | null): void {
+    if (elt) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: Per discussion; make sure to clean up event handlers in the 2 cases:

1. component unmounts
2. ref changes to null

File: packages/office-ui-fabric-react/src/components/Panel/Panel.tsx [hunk 2]
```diff
@@ -191,13 +192,18 @@ export class Panel extends BaseComponent<IPanelProps, IPanelState> implements IP
...
               }
             >
-              <div className={css('ms-Panel-commands')} data-is-visible={true}>
-                {onRenderNavigation(this.props, this._onRenderNavigation)}
-              </div>
-              <div className={css('ms-Panel-contentInner', styles.contentInner)}>
-                {header}
-                {onRenderBody(this.props, this._onRenderBody)}
-                {onRenderFooter(this.props, this._onRenderFooter)}
+              <div
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: can you make sure we have a snapshot test covering this one

File: packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx [hunk 3]
```diff
@@ -39,6 +40,7 @@ export class ModalBase extends BaseComponent<IModalProps, IDialogState> implemen
       isOpen: props.isOpen,
       isVisible: props.isOpen
     };
+    this._allowScrollOnModal = this._allowScrollOnModal.bind(this);
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx]: shouldn't this just be a lambda in the definition?

File: packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx [hunk 4]
```diff
@@ -76,6 +78,10 @@ export class ModalBase extends BaseComponent<IModalProps, IDialogState> implemen
     }
   }
 
+  public componentWillUnmount() {
+    this._events.dispose();
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx]: This is automatically done by BaseComponent! :)

File: packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx [hunk 5]
```diff
@@ -150,6 +156,17 @@ export class ModalBase extends BaseComponent<IModalProps, IDialogState> implemen
     }
   }
 
+  // Allow the user to scroll within the modal but not on the body
+  private _allowScrollOnModal(elt: HTMLDivElement | null): void {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx]: if you make this a lambda you can get rid of the earlier bind.

File: packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx [hunk 6]
```diff
@@ -150,6 +156,17 @@ export class ModalBase extends BaseComponent<IModalProps, IDialogState> implemen
...
+    if (elt) {
+      this._scrollableContent = elt;
+      allowScrollOnElement(this._scrollableContent, this._events);
+    } else {
+      this._events.off(this._scrollableContent);
+      this._scrollableContent = null;
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx]: you can move this line down below the if to reduce repetition. (assign scrollableContent = elt)

**Comment by dzearing** [comment]
just have some minor nits.
