### PR TITLE
Fixing accessibility issue: #4295

### LINKED ISSUE #4295: Promise based TextField error message is not read by firefox + NVDA
### Bug Report

- __Package version(s)__: https://codepen.io/anon/pen/LdRVZQ
- __Browser and OS versions__: Firefox 58.0.2 on windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: visualstudio.com

#### Describe the issue:

When error message is delayed and user moves to next item, error message is not announced by NVDA.

#### Actual behavior:

Error message is not announced even though in live region.

#### Expected behavior:

Error message should be announced.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/LdRVZQ
Steps: 
-> Open above link in Firefox and turn NVDA ON.
-> Type "123" in first text field and immediately press tab
-> Wait till error message appears
This error message should have been announced but NVDA doesn't announce anything.

### PR DESCRIPTION
**Pull request by b-priyank**
Promise based TextField error message is not read by firefox + NVDA

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4295
- [x] Include a change request file using `$ npm run change`

#### Description of changes

aria-live="assertive" attribute should be defined on a statically available element. Error message may be loaded dynamically inside that element. For TextField, this attribute was added to DOM dynamically. In order to announce message in live region, Assistive Technology (NVDA) need to detect some element with aria-live defined. Then it announces any message loaded dynamically inside it.

#### Focus areas to test
All error message combinations for TextField with:
EDGE + Narrator
FireFox + NVDA

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx [hunk 1]
```diff
@@ -192,17 +192,17 @@ export class TextField extends BaseComponent<ITextFieldProps, ITextFieldState> i
         { this._isDescriptionAvailable &&
           <span id={ this._descriptionId }>
             { description && <span className={ css('ms-TextField-description', styles.description) }>{ description }</span> }
+            <div aria-live='assertive'>
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: shouldn't this move into the `errrorMessage` condition block? Otherwise we just add a div there with no content unnecessarily.

Also changes need a change file. Try running `npm run change` from the root to generate one.

Comment (b-priyank) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: It was not working with NVDA old version. However, I updated to latest version `2018.1` and it is working fine. So, moved div into `errorMessage` condition block. Updated change file as well. Verified on firefox + NVDA and EDGE + narrator. Thanks.!

File: packages/office-ui-fabric-react/src/components/TextField/TextField.tsx [hunk 2]
```diff
@@ -193,12 +193,12 @@ export class TextField extends BaseComponent<ITextFieldProps, ITextFieldState> i
           <span id={ this._descriptionId }>
             { description && <span className={ css('ms-TextField-description', styles.description) }>{ description }</span> }
             { errorMessage &&
-              <div>
+              <div aria-live='assertive'>
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: @cschlechty is this reasonable?

Comment (cschlechty) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.tsx]: Yep
