### PR TITLE
Fix minor accessibility bugs in DetailsList

### LINKED ISSUE #4142: [Accessibility] Non-actionable column headers in details are being read out as disabled by narrator, giving a wrong impression about the entire column
### Bug Report

- __Package version(s)__: 5.55.1001
- __Browser and OS versions__: Windows 10 Fall Update and Microsoft Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Visual Studio Team Services

#### Describe the issue:

Let us have a DetailsList with a column having columnActionsMode set to disabled
When using Narrator with Edge, on reaching the header of this column (say, the header name is Header 1), the narrator reads "Column Header Header1 disabled" 

#### Actual behavior:

The fact that narrator is reading out the term disabled is giving an impression that the entire column is disabled

#### Expected behavior:

If the column header is actionable, we can specify so. But we should not announce disable if the column header is not actionable

### If applicable, please provide a codepen repro:
I found an existing codepen for grouped DetailsList (link below) from the dzearing's library. Please set columnActionsMode to 0 on any column and observe the issue, that I am referring to. 
https://codepen.io/dzearing/pen/LbORXM

### PR DESCRIPTION
**Pull request by ThomasMichon**
Adjusted the contrast of the Check component.
Removed `aria-disabled` from column headers.

This fixes #4142, #4269, and #5076.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx [hunk 1]
```diff
@@ -219,7 +219,6 @@ export class DetailsHeader extends BaseComponent<IDetailsHeaderProps, IDetailsHe
               key={column.key}
               role="columnheader"
               aria-sort={column.isSorted ? (column.isSortedDescending ? 'descending' : 'ascending') : 'none'}
-              aria-disabled={column.columnActionsMode === ColumnActionsMode.disabled}
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx]: Don't completely understand the background. Do you know who added this and why?

**Comment by natalieethell** [comment]
Hey it looks like DetailsList was recently refactored in a [PR merged 4 hours ago](https://github.com/OfficeDev/office-ui-fabric-react/pull/4857) and there is now a new file, [DetailsColumn.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.tsx). These changes may need to be made in there instead?
