### PR TITLE
Object/getId: Fix it so it correctly returns a string instead of a number.

### LINKED ISSUE #1176: [Accessibility][Button]Default Button has invalid ARIA attribute value
Package Version: Current - Component Library Demo Site
Browser: Chrome

This issue is based on automated testing with the aXe extension for Chrome.

## Issue Description
URL: https://dev.office.com/fabric#/components/button

Default Button has invalid ARIA attribute value: e.g. aria-labelledby="Button68"  There is no id="Button68". This is a critical accessibility issue according to WCAG 2.0 A standards.

##How to Reproduce
Go to https://dev.office.com/fabric#/components/button and run [aXe](http://www.deque.com/axe).
Look for the "ARIA attributes must conform to valid values" issues.

## Current Behavior
There are 6 occurrences of aria-labelledby and/or aria-describedby being set to a non-existent value. Assistive Technologies (like screen readers) cannot find the necessary information.

  ## Expected behavior
The value of each aria-labelledby and aria-describedby must be a value of an id that is currently set on the page.

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1176 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Object/getId: Fix it so it correctly returns a string instead of a number.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/utilities/src/object.ts [hunk 1]
```diff
@@ -87,7 +88,7 @@ export function filteredAssign(isAllowed: (propName: string) => boolean, target:
 export function getId(prefix?: string): string {
   let index = _global[CURRENT_ID_PROPERTY]++;
 
-  return (prefix || '') + index;
+  return (prefix || DEFAULT_ID_STRING) + index;
```
Comment (MLoughry) [inline packages/utilities/src/object.ts]: If you don't want to change the intended output, you could rewrite it as:
```ts
return `${prefix || ''}${index}`;
```

Comment (joschect) [reply packages/utilities/src/object.ts]: It's already technically returning a string. The problem was that in HTML 4 an ID was required to start with a letter. So Really I need to change the default string to be something like `id__`. 

The alternative is to not let prefix be undefined. Ideally the prefix should be a unique and descriptive identifier. However that is a breaking change.

See this [stackoverflow](https://stackoverflow.com/questions/5672903/can-i-have-a-div-with-id-as-number) for more.

image

**Comment by dzearing** [comment]
Resetting the PR to pick up the screener fix.
