### PR TITLE
Website: Fixing Card API reference tables not appearing on the component docs page

### LINKED ISSUE #11843: Card API docs missing from website
Noticed while trying to show someone the Card docs that the API reference tables are missing. (I can potentially help with this, mainly logging issue as reminder.) 
https://developer.microsoft.com/en-us/fabric#/controls/web/card

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11843
- [x] Include a change request file using `$ yarn change`

#### Description of changes

The API reference tables for the `Card` component weren't appearing on the website because it was looking only at pages generated from the `office-ui-fabric-react` package whereas the `Card` component is in the `@uifabric/react-cards` package. This PR fixes this issue by making the website look in both places for components.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11844)

### CODE REVIEW

File: apps/fabric-website/src/pages/Controls/ControlsAreaPage.tsx [hunk 1]
```diff
@@ -6,16 +6,21 @@ import { IPageJson } from 'office-ui-fabric-react/lib/common/DocPage.types';
 
 export interface IControlsPageProps extends IPageProps<Platforms> {}
 
-const apiRequireContext = require.context('@uifabric/api-docs/lib/pages/office-ui-fabric-react');
+const apiRequireContext = [
+  require.context('@uifabric/api-docs/lib/pages/office-ui-fabric-react'),
```
Comment (ecraig12345) [inline apps/fabric-website/src/pages/Controls/ControlsAreaPage.tsx]: Oh actually, I have another idea which will scale better: go back to a single context and use negative lookahead! (I confirmed it works in all browsers.) 
`require.context('@uifabric/api-docs/lib/pages/', true, /^(?!references).*/)`

require.context reference: https://webpack.js.org/api/module-methods/#requirecontext
