### PR TITLE
TextField: fix focused bottom border mis-alignment when errorMessage is set

### LINKED ISSUE #11714: TextField: focused bottom border is misplaced when errorMessage is set
### Environment Information

- **Package version(s)**: v7.82.1
- **Browser and OS versions**: all

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/janjachacz/pen/bGNjOLG

#### Actual behavior:

image

#### Expected behavior:

Bottom border is placed correctly when TextField is active.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: PowerApps / AI Builder

### PR DESCRIPTION
**Pull request by v-jajach**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11714
- [x] Include a change request file using `$ yarn change`

#### Description of changes

Updated `getInputFocusStyle` method parameter `borderPosition` to use an object instead of just a number so we have a better control on border's position.

#### Before
image

#### After
image

#### Focus areas to test

- Undertlined TextField focused / blured 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11715)

### CODE REVIEW

File: packages/styling/src/styles/getFocusStyle.ts [hunk 1]
```diff
@@ -139,26 +139,26 @@ export function getFocusOutlineStyle(theme: ITheme, inset: number = 0, width: nu
...
+ * @param borderPosition - Position of the border relative to the input element (default to { top: -1, right: -1, bottom: -1, left: -1 }
  * as it's the most common border width of the input element)
  * @returns The style object.
  */
 export const getInputFocusStyle = (
   borderColor: string,
   borderRadius: string | number,
   borderType: 'border' | 'borderBottom' = 'border',
-  borderPosition: number = -1
+  borderPosition: { top: number; right: number; bottom: number; left: number } = { top: -1, right: -1, bottom: -1, left: -1 }
```
Comment (xugao) [inline packages/styling/src/styles/getFocusStyle.ts]: Thanks for catching the mis-alignment issue here. Instead of this change here is what I purpose:
we should not set  left / right to 0 if there is no left / right border
```
export const getInputFocusStyle = (
  borderColor: string,
  borderRadius: string | number,
  borderType: 'border' | 'borderBottom' = 'border',
  borderPosition: number = -1
): IRawStyle => {
  const isBorderBottom = borderType === 'borderBottom';

  return {
    borderColor,
    selectors: {
      ':after': {
        pointerEvents: 'none',
        content: "''",
        position: 'absolute',
        left: isBorderBottom ? 0 : borderPosition,
        top: borderPosition,
        bottom: borderPosition,
        right: isBorderBottom ? 0 : borderPosition,
        [borderType]: `2px solid ${borderColor}`,
        borderRadius,
        width: isBorderBottom ? '100%' : undefined,
        selectors: {
          [HighContrastSelector]: {
            [borderType === 'border' ? 'borderColor' : 'borderBottomColor']: 'Highlight'
          }
        }
      }
    }
  };
};
```

File: change/@uifabric-experiments-2020-01-15-16-19-24-users-v-jajach-fixed-issue-11714.json [hunk 2]
```diff
@@ -0,0 +1,8 @@
+{
+  "type": "patch",
+  "comment": "Fixed #11714",
```
Comment (xugao) [inline change/@uifabric-experiments-2020-01-15-16-19-24-users-v-jajach-fixed-issue-11714.json]: pls make the comment more detailed, suggestion:
TextField: fix focused bottom border mis-alignment when errorMessage is set

File: change/office-ui-fabric-react-2020-01-15-15-51-17-users-v-jajach-fixed-issue-11714.json [hunk 3]
```diff
@@ -0,0 +1,8 @@
+{
+  "type": "patch",
+  "comment": "Fixed #11714",
```
Comment (xugao) [inline change/office-ui-fabric-react-2020-01-15-15-51-17-users-v-jajach-fixed-issue-11714.json]: pls make the comment more detailed, suggestion:
TextField: fix focused bottom border mis-alignment when errorMessage is set

File: packages/styling/src/styles/getFocusStyle.ts (hunk 1 above)
Comment (v-jajach) [reply packages/styling/src/styles/getFocusStyle.ts]: Yeap, seems a better approach. 
Thank you

File: packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx [hunk 4]
```diff
@@ -153,12 +153,17 @@ export function getStyles(props: ITextFieldStyleProps): ITextFieldStyles {
...
+        focused && [
+          {
+            position: 'relative'
+          },
           getInputFocusStyle(
             !hasErrorMessage ? semanticColors.inputFocusBorderAlt : semanticColors.errorText,
             effects.roundedCorner2,
-            'borderBottom'
+            'borderBottom',
+            -2
```
Comment (xugao) [inline packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx]: should not need to pass & set to `-2` here? (`-1` should be correct)

Comment (v-jajach) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx]: Since we set `borderRadius` to `effects.roundedCorner2`, I assumed we want to see the `borderRadius`. If I remove the param (or set it to the default -1) we are loosing it since the pseudo element `:after` overlays the border set by `.ms-TextField-wrapper`.

#### Please see example with border color set to light green to see the overlaps:
image

#### borderPosition set to -1 or undefined
image

#### borderPosition set to -2
image

Comment (xugao) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx]: @betrue-final-final could you confirm which behavior is expected? should we have `border-radius` if there is only border bottom?

Comment (xugao) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx]: Nvm Ben. I checked the [design doc](https://www.figma.com/file/BAfsTrZ9ehIYZ0oYuyskUN2R/Web-Fluent?node-id=0%3A2741). it should be no radius:
image

Comment (xugao) [reply packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx]: @v-jajach - please update the PR accordingly ^
