### PR TITLE
Invalid ARIA attributes: Fix empty values

### LINKED ISSUE #4985: Checkbox accepting null ariaDescribedBy and creating an attribute without value
#### Describe the issue:
When we pass ariaDescribedBy as null in Checkbox, the renderer renders aria-describedby attr without any value causing Keros failure (Accessibility)

#### Actual behavior:
The renderer renders aria-describedby attr without any value causing Keros failure (Accessibility)

#### Expected behavior:
Control should handle that null pass of ariaDescribedBy should not even create an attr.

### If applicable, please provide a codepen repro:

https://codepen.io/AkshanshSrivastava03/pen/wmdEVJ

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4985
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Prevent ARIA attributes from appearing with invalid empty values when there are no associated values to display.

Starting with #4985 highlighting an issue with invalid ARIA attributes in Checkbox, I found this to be a pattern affecting multiple components: BaseButton, Checkbox, ComboBox, ContextualMenuSplitButton, Dropdown, KeytipData. This PR fixes them. Also consistently default to `undefined` instead of `null` in some instances. Created a new utility helper to merge ARIA attributes. 

#### Focus areas to test

Added unit tests for new utility function. Updated snapshots to reflect new behavior.

### CODE REVIEW

File: packages/utilities/src/aria.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
+/**
+ * ARIA helper to concatenate attributes, returning undefined if all attributes
+ * are undefined. (Empty strings are not a valid ARIA attribute value.)
+ *
+ * NOTE: This function will NOT insert whitespace between provided attributes.
+ *
+ * @param ariaAttributes ARIA attributes to merge
+ */
+export function mergeAriaAttributes(...ariaAttributes: (string | undefined)[]): string | undefined {
+  let mergedAttribute = '';
```
Comment (kenotron) [inline packages/utilities/src/aria.ts]: ```return ariaAttributes.filter(arg => arg !== undefined && arg !== null).join('');``` maybe?

File: packages/utilities/src/aria.ts [hunk 2]
```diff
@@ -0,0 +1,18 @@
+/**
+ * ARIA helper to concatenate attributes, returning undefined if all attributes
+ * are undefined. (Empty strings are not a valid ARIA attribute value.)
+ *
+ * NOTE: This function will NOT insert whitespace between provided attributes.
```
[the remark this answers is not in the document]
Comment (JasonGore) [reply packages/utilities/src/aria.ts]: Because all of the uses present in the codebase were already inserting spaces. This is a helper primarily to return undefined when all values are undefined, as opposed to `'undefined'` string value or `''`.

File: packages/utilities/src/aria.ts (hunk 1 above)
Comment (JasonGore) [reply packages/utilities/src/aria.ts]: Sure. I like your idea of `mergeAriaValues` too, I think that would be more clear.
