### PR TITLE
Fix persona image so it does not cause DOM reflow

### LINKED ISSUE #2002: Performance issues from synchronous reflows
Opening issue from ongoing e-mail thread
=============

Hey guys -
 
After adding personas, we have hit a a couple persona-related performance issues.
 
1) There is a reflow happening for every persona because of the code below. On my fast machine each one is about 60ms which x 25 =  1500ms on a fast computer for only 25 personas. On user scroll, we add 25 personas per page so it slows down really quick. This is seriously regressing our perf.
 
```  
Image.prototype._computeCoverStyle = function (props) {
  var imageFit = props.imageFit, width = props.width, height = props.height;
  if (imageFit === Image_Props_1.ImageFit.cover || imageFit === Image_Props_1.ImageFit.contain) {
      if (this._imageElement) {
          // Determine the desired ratio using the width and height props.
          // If those props aren't available, measure measure the frame.
         var desiredRatio = void 0;
          if (!!width && !!height) {
              desiredRatio = width / height;
         }
         else {
             desiredRatio = **this._frameElement.clientWidth / this._frameElement.clientHeight**;
          }
          // Examine the source image to determine its original ratio.
          var naturalRatio = this._imageElement.naturalWidth / this._imageElement.naturalHeight;
          // Should we crop from the top or the sides?
          if (naturalRatio > desiredRatio) {
             this._coverStyle = CoverStyle.landscape;
          }
          else {
             this._coverStyle = CoverStyle.portrait;
          }
      }
  }
};
  ```

2) Another issue is the complexity of the persona component. It is 4 divs deep. So again for 25 personas that is 75 extra divs on the page and even more as user scrolls down and more personas appear! This adds a lot of DOM complexity and severely impacts our FPS. 
  
To be able to use this component, we really need these 2 issues fixed ASAP. This is supposed to be one of our differentiating features in our upcoming release so it is critical. Please advise!

### PR DESCRIPTION
**Pull request by lindach167**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #2002
- [ ] Include a change request file using `$ npm run change`

{
  "changes": [
    {
      "packageName": "office-ui-fabric-react",
      "comment": "Fix persona image reflow",
      "type": "patch"
    }
  ],
  "packageName": "office-ui-fabric-react",
  "email": "lindach@microsoft.com"
}

#### Description of changes

Add an optional parameter to Image control so it takes in a cover style which it will use if specified, If not specified it will fallback to measuring. Long term, we should make the Image control (and all controls) not reflow by default, but this is a quicker fix to unblock OWA perf issues.

I had considered passing down the dimensions of the persona down to Image control, but this felt like a lot of overhead when the persona control should never conditionally get landscape or portrait cover, because it is always a square. In order to pass down the dimensions, we would need to maintain the sizes and keep them in sync with the persona sizes we use in the css, and in the end it is not really needed because it doesn't matter whether it gets landscape or portrait as either one will work. So I pass down ImageCoverStyle.portrait to Image control from Persona control.

#### Focus areas to test

Persona control
Image control

### CODE REVIEW

**Comment by MLoughry** [comment]
You should include the actual change file generated by the rush change tool as part of the commit

File: packages/office-ui-fabric-react/src/components/Image/Image.tsx [hunk 1]
```diff
@@ -80,7 +75,7 @@ export class Image extends BaseComponent<IImageProps, IImageState> {
     let imageProps = getNativeProps(this.props, imageProperties, ['width', 'height']);
     let { src, alt, width, height, shouldFadeIn, className, imageFit, role, maximizeFrame } = this.props;
     let { loadState } = this.state;
-    let coverStyle = this._coverStyle;
+    let coverStyle = this.props.coverStyle || this._coverStyle;
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Image/Image.tsx]: This should probably be 

```ts
this.props.coverStyle === undefined ? this._coverStyle : this.props.coverStyle
```
I think the intent is that if the caller passes in a cover style, we use that. But I think the behavior is, if they pass in landscape (value 0), use `_coverStyle`.

Comment (lindach167) [inline packages/office-ui-fabric-react/src/components/Image/Image.tsx]: Good catch! Will fix
