### PR TITLE
Suggestions Component bug fix: Slice suggestions based on selected suggestion        

### LINKED ISSUE #8282: Selected Suggestions items not visible after scrolling down
Background:

I am a software developer at Bloomberg. We use this library for some of our web products. I discovered a small bug in the Suggestions component. 

If the suggestions parameter has a list of suggestions that is greater than the resultsMaximumNumber parameter, users can not scroll through the list of suggestions. This can cause potential accesibility issues.

I have already created a draft PR to fix the issue. I searched through the existing PRs and Issues to make sure this issue wasn't reported before. 

Instructions to replicate:

suggestions param: list of N SuggestionsItem where N is more than the resultsMaximumNumber param.
When scrolling down the list of suggestions, if the selection index goes beyond resultsMaximumNumber, the selected item will not be visible. (See screenshots)

This can cause accesibility issues because the user can not access all the options using just the keyboard.
https://github.com/OfficeDev/office-ui-fabric-react/pull/8275

### Environment Information 
 
- __Package version(s)__: office-ui-fabric-react 6.155.0 (latest)
- __Browser and OS versions__: Irrelevant

#### Actual behavior:
 
Selection is on index 0
image

Selection is on index 3.
image
The suggestions to display are sliced based on index 0 and resultsMaximumNumber, rather than the selected suggestion index

 
#### Expected behavior:

With the fix, the suggestions to display are sliced based on the current selected index:
image

This visually creates the impression of scrolling.
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? 

**Yes.** The draft PR has already been created: https://github.com/OfficeDev/office-ui-fabric-react/pull/8275
Once I have access to my dev machine I can finish the final step (npm run change) and make a PR.
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by PratikDeshpande**
**Bug:**
User can not scroll down list of suggestions with keyboard.

**How to replicate:**
suggestions param: list of N SuggestionsItem where N is more than the resultsMaximumNumber param. 
When scrolling down the list of suggestions, if the selection index goes beyond resultsMaximumNumber, the selected item will not be visible. (See screenshots)

This can cause accesibility issues because the user can not access all the options using just the keyboard.

Selection is on index 0
image

Selection is on index 4.
image
The suggestions to display are sliced based on index 0 and resultsMaximumNumber, rather than the selected suggestion index

With the fix, the suggestions to display are sliced based on the current selected index:
image

This visually creates the impression of scrolling.

#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8282
- [x] Include a change request file using `$ npm run change`

#### Description of changes

(give an overview)

When displaying SuggestionItems, this component slices the list of suggestions based between index 0 and resultsMaximumNumber.

I modified this logic to
1. find the selected index
2. slice the suggestions array so that the selected suggestion will always be displayed. 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx [hunk 1]
```diff
@@ -321,8 +321,12 @@ export class Suggestions<T> extends BaseComponent<ISuggestionsProps<T>, ISuggest
...
     );
 
+    const selectedIndex = suggestions.findIndex(suggestion => suggestion.selected);
     if (resultsMaximumNumber) {
-      suggestions = suggestions.slice(0, resultsMaximumNumber);
+      suggestions =
+        selectedIndex >= resultsMaximumNumber
+          ? suggestions.slice(selectedIndex - resultsMaximumNumber + 1, selectedIndex + 1)
+          : suggestions.slice(0, resultsMaximumNumber);
     }
```
Comment (PratikDeshpande) [inline packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: The output of findIndex()
is bound by the size of the suggestions array. If there is no selected suggestion, it will return -1
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex

I was thinking about bounds checking, but the slice() function's 'end index' parameter can be greater than the size of the array.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

**Comment by PratikDeshpande** [comment]
To give a bit of a background: I'm a software developer at Bloomberg. We use this library for some of our web products. I discovered a small bug in the Suggestions component. I reported it here after validating that this issue wasn't reported before: https://github.com/OfficeDev/office-ui-fabric-react/issues/8282

**Comment by joschect** [comment]
Hey @PratikDeshpande Thanks a bunch for submitting this pr!

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx [hunk 2]
```diff
@@ -321,8 +321,12 @@ export class Suggestions<T> extends BaseComponent<ISuggestionsProps<T>, ISuggest
       }
     );
 
+    const selectedIndex = suggestions.findIndex(suggestion => suggestion.selected);
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: Unfortunately, `findIndex` is not supported by IE and so it can't be used just yet.

Something like 
```
    let selectedIndex = -1;
    suggestions.some((element, index) => {
      if (element.selected) {
        selectedIndex = index;
        return true;
      }
      return false;
    });
```

Should be able to work as a substitute!

Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: @joschect why the `selectedIndex` is even incremented when we have a `resultsMaximumNumber` prop set. Shouldn't the Search for more link be next accessible by the keyboard?

**Comment by PratikDeshpande** [comment]
@joschect done.

**Comment by PratikDeshpande** [comment]
The Travis CI build failed because the change file is missing. I'll add one as soon as I get the chance.

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx (hunk 2 above)
Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: I would assume if `resultsMaximumNumber` prop is set then we need to make sure somewhere higher in the code hierarchy that on clicking the down keyboard arrow will not increment the index of the selected suggestion. Instead, the user would have to either tab to reach the searchForMore link and activate it. @joschect am I missing some important design implementation and the author is actually submitting the correct fix in here?

Comment (PratikDeshpande) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: That would solve our issue as well (if the focus went straight to 'Search more matches' after scrolling down).

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: @Vitalius1 I think you're correct. I'll take another look. I think that this behavior is appropriate if there is no "Search more matches" button but if there is then you're correct that it should get focused.

Comment (PratikDeshpande) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: @joschect @Vitalius1 I'll investigate if I can make that change

 (if scrolling past resultsMaximumNumber, focus should shift to 'searchForMore', otherwise continue scrolling)

Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: @joschect what is SearchForMore doing when clicked? Is it replacing the results with a new set of suggestions? Or it just adds them to the existing ones? How is `resultsMaximumNumber` playing a role in that case?

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: It triggers a callback which makes it's way out to the consuming component. It's up the consuming component how those results are returned, it might return all the current suggestions plus a few more, or it could return a completely different set.

It's related to the resultsMaximumNumber because one of it's uses is to allow the user to search for different results if not all of them are present.

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx (hunk 1 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: Specifically:

>If end is greater than the length of the sequence, slice extracts through to the end of the sequence (arr.length).

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx (hunk 2 above)
Comment (PratikDeshpande) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: I have some other sprint stuff at the moment. But next week I can modify this PR so that instead of scrolling down the list of suggestions, the focus will shift to 'searchForMore' component (if present).

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: I've done a bit of digging and I'm pretty sure there's a bug somewhere in the tryHandleKeyDown function. I believe that it needs to check to see if it's reached the maximum of items and there's a searchForMore button then it should change the action to SuggestionActionType.searchMore. There's some other stuff missing and it looks like it can get focus if the parent were to implement a few things. However we should probably try to handle it automatically somehow.

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: I think for now this PR is probably a step in the right direction and likely we should get this merged, and then investigate focusing the searchForMore button properly. I suspect it will be a bit larger of a change. @dzearing  or @cliffkoh  do you have any opinions about leaving something like that for a later pr?

**Comment by natalieethell** [comment]
Hey @PratikDeshpande when you get a chance, could you manually merge your branch with the latest version of master? We made some changes to the API files and want to ensure that these updates are reflected in your branch before merging the PR.

Thanks!

**Comment by natalieethell** [comment]
Also @joschect do you want to take another look at @PratikDeshpande's changes?

File: packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx [hunk 3]
```diff
@@ -321,8 +321,20 @@ export class Suggestions<T> extends BaseComponent<ISuggestionsProps<T>, ISuggest
       }
     );
 
+    let selectedIndex = -1;
+    suggestions.some((element, index) => {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx]: why some and not forEach

**Comment by dzearing** [comment]
@joschect waiting on you.

**Comment by joschect** [comment]
@natalieethell  and @dzearing  yeah! This looks good to go. Sorry for my slow response!

**Comment by PratikDeshpande** [comment]
> Hey @PratikDeshpande when you get a chance, could you manually merge your branch with the latest version of master? We made some changes to the API files and want to ensure that these updates are reflected in your branch before merging the PR.
> 
> Thanks!
> 
> Edit: I'd be happy to help out with this if you select "Allow edits from maintainers" on the right sidebar of your PR.

I'm sorry for the late response. I was traveling. It looks like it has already been merged.

**Comment by natalieethell** [comment]
@PratikDeshpande no problem! It looks like your final changes actually didn't touch the API surface, so we should be good here
