### PR TITLE
FocusZone: Adding tab handle for DomOrder direction

### LINKED ISSUE #11336: FocusZoneDirection.domOrder will break handleTabKey
In the FocusZone component I can use handleTabKey to get it to also control tab key actions. There is also direction attribute to control the direction of the arrow keys. These don't seem to affect each other with one exception: If I set direction={FocusZoneDirection.domOrder}, the arrow keys will follow the dom order int he same way as tab would usually do. But tab will no longer navigate inside the FocusZone.

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/svartn/pen/pooMZzE

#### Actual behavior:

Tab will not move between the list items when direction={FocusZoneDirection.domOrder}

#### Expected behavior:

Tab will not move between the list items in the same way as arrowign does.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11336
- [x] Include a change request file using `$ yarn change`

#### Description of changes

An issue recently came that specified that the `handleTabKey` prop was not working when `FocusZoneDirection.domOrder` was specified. This PR fixes this issue and adds a test so it doesn't regress in the future.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11469)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx [hunk 1]
```diff
@@ -581,7 +581,7 @@ export class FocusZone extends React.Component<IFocusZoneProps> implements IFocu
               !this._shouldWrapFocus(this._activeElement as HTMLElement, NO_HORIZONTAL_WRAP)
             ) {
               focusChanged = ev.shiftKey ? this._moveFocusUp() : this._moveFocusDown();
-            } else if (direction === FocusZoneDirection.horizontal || direction === FocusZoneDirection.bidirectional) {
+            } else {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx]: is there a missing test case?

Comment (khmakoto) [reply packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx]: @dzearing just added it.

**Comment by khmakoto** [comment]
I think the screener issues are unrelated to this change.
