### PR TITLE
Breadcrumb: added tooltip for truncated items

### LINKED ISSUE #2034: BreadCrumb: doesn't have tooltip when item is trimmed and ellipsized. No way to know full text.
### Bug Report

- __Package version(s)__: 2.20.2
- __Browser and OS versions__: All browsers, windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: VSOnline 

#### Describe the issue:

Default max-width of breadcrumb item is 160px. After that it shows ellipsis.
There is no tooltip or other means to know full text of the ellipsized breadcrumb item.

#### Actual behavior:

Default max-width of breadcrumb item is 160px. After that it shows ellipsis.
There is no tooltip or other means to know full text of the ellipsized breadcrumb item.

#### Expected behavior:

There should be some means to know full text of the ellipsized tooltip item.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/bRWyRB

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2034
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Removed a redundant on Render function and added a tooltip around the text that only shows when the parent is smaller than the text (i.e. truncated). 

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx [hunk 1]
```diff
@@ -12,6 +12,7 @@ import { IconButton } from '../../Button';
 import { IBreadcrumbProps, IBreadcrumbItem } from './Breadcrumb.Props';
 import { DirectionalHint } from '../../common/DirectionalHint';
 import { ResizeGroup } from '../../ResizeGroup';
+import { TooltipHost, TooltipOverflowMode } from '../../Tooltip';
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx]: This adds tooltip to breadcrumb graph, increasing the weight of it. It makes me nervous. We really need a build system which spits out the bundle differences here, so that you can be nervous too. For example, if you make a bundle that just bundles the Breadcrumb, you would see that this probably adds 5k of stuff. Then we could ask how we reduce that or defer it, because tooltips are not needed at glass render.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.tsx]: I was less worried about the size as the contextual menu is already included, which has layer etc.
