### PR TITLE
Button pass ondismiss

### LINKED ISSUE #3140: Allow clicking commandbar context menu item without dismissing the menu
### Bug Report

- __Package version(s)__: 5.0.1
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)
Owa mail command bar Move to menu

#### Describe the issue:

Overriding onDismiss for a context menu item of command bar should allow an option to not dismiss the menu. Right now it calls onDismiss callback but still dismisses the menu by calling setState.
We have a requirement to add menu items in owa mail command bar's Move to menu for -
1) New Folder - Clicking this will replace the menu item with a text box where user can enter new folder name. On enter it should dismiss the menu.
2) More Folders - Clicking on this menu item should not dismiss the Move to menu. It will replace the folder list with full folder list in the same menu (not open a submenu).

    CommandBar.prototype._onContextMenuDismiss = function (ev) {
        if (!ev || !ev.relatedTarget || !this.refs.commandSurface.contains(ev.relatedTarget)) {
            var contextualMenuProps = this.state.contextualMenuProps;
            if (contextualMenuProps && contextualMenuProps.onDismiss) {
                this.state.contextualMenuProps.onDismiss(ev);
            }
            this.setState({
                expandedMenuItemKey: undefined,
                contextualMenuProps: undefined,
                contextualMenuTarget: undefined
            });
        }
        else {
            ev.stopPropagation();
            ev.preventDefault();
        }
    };

#### Actual behavior:

Clicking on an item always dismisses the context menu

#### Expected behavior:

Do not dismiss the menu onDismiss callback

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3140
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Previously onDismiss was overwritten by the button's _onToggleMenu function.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -358,7 +360,7 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
         className={ 'ms-BaseButton-menuhost ' + menuProps.className }
         target={ this._isSplitButton ? this._splitButtonContainer : this._buttonElement }
         labelElementId={ this._labelId }
-        onDismiss={ this._onToggleMenu }
+        onDismiss={ onDismiss }
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Hmm. You would now be skipping the logic in onToggleMenu. Are you sure that is desired?

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Sorry, I was going to add a little bit to this. PR incoming.

Comment (avnikp) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: This will still not address the issue to not dismiss onClick -

image

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: @avnikp correct, which is why I made #3225

Comment (avnikp) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: ah, thanks! I'll take a look.
