### PR TITLE
getGlobalClassNames now returns the correct thing even when theme mutates.

### LINKED ISSUE #6551: getGlobalClassNames can be more resilient to suboptimal code from consumers
### Please provide a reproduction of the bug in a codepen:

If a consuming app writes code like this:

image

This causes the memorization presently in `getGlobalClassNames` (https://github.com/OfficeDev/office-ui-fabric-react/blob/dc8006f130300a6dee7831e3e0166a4da8ff84a8/packages/styling/src/styles/getGlobalClassNames.ts#L17) to fail because on each render pass, the "`disableGlobalClassNames` method in the screenshot above is invoked to create a new theme object.

One improvement that can be made while preserving backwards compatibility is to memorize `theme.disableGlobalClassNames` in `getGlobalClassNames` instead of the entire `theme` object which will make it more resilient to such errors in the future.

(Fabric Tactical members - for more details, look for email titled "Memoization bug" in Fabric Tactical)
 

### Bug Report 
 
 
- __Package version(s)__: 6.76.0

 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: LPC

### PR DESCRIPTION
**Pull request by dzearing**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6551
- [X] Include a change request file using `$ npm run change`

#### Description of changes

getGlobalClassNames was assuming the theme object is immutable. It isn't. But the boolean inside it is. So pull that out and pass that into a memoized function.

### CODE REVIEW

File: packages/styling/src/styles/getGlobalClassNames.ts [hunk 1]
```diff
@@ -1,32 +1,18 @@
...
-    classNames: GlobalClassNames<T>,
-    theme: ITheme,
-    disableGlobalClassNames?: boolean
-  ): Partial<GlobalClassNames<T>> => {
+const _getGlobalClassNames = memoizeFunction(
+  <T>(classNames: GlobalClassNames<T>, disableGlobalClassNames?: boolean): Partial<GlobalClassNames<T>> => {
     const styleSheet = Stylesheet.getInstance();
 
-    if (disableGlobalClassNames || (disableGlobalClassNames === undefined && theme.disableGlobalClassNames)) {
+    if (disableGlobalClassNames || (disableGlobalClassNames === undefined && disableGlobalClassNames)) {
```
Comment (VincentBailly) [inline packages/styling/src/styles/getGlobalClassNames.ts]: Can be simplified
