### PR TITLE
Fix nav section behavior

### LINKED ISSUE #8999: Component dropdown links won't collapse after navigation on the documentation site.
Component dropdowns on the side navigation panel remain frozen after clicking the link to a specific component. 

Steps to reproduce:

1. Go to: [https://developer.microsoft.com/en-us/fabric#/controls/web](https://developer.microsoft.com/en-us/fabric#/controls/web)
2. Expand "Basic Inputs" on the right side navigation bar.
3. Click "Button," navigating to the documentation page for the button component.
4. "Basic Inputs" remains expanded post rendering. Clicking the carrot won't collapse the basic inputs menu.

I'm using Chrome Version 74.0.3729.131 (Official Build) (32-bit) on Windows 10.

### PR DESCRIPTION
**Pull request by jordandrako**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8999 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

`CollapsibleSection` is more mature now than when I implemented it in the website's left nav. It's no longer required to implement custom `collapsed` logic, just `defaultCollapsed`.

#### Testing

Test by navigating from page to page and opening/closing sections: http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/9078/merge/fabric-website/dist/index.html?devhost#/controls/web/button

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9078)

### CODE REVIEW

File: apps/fabric-website/src/components/Nav/Nav.tsx [hunk 1]
```diff
@@ -184,30 +180,14 @@ export class Nav extends React.Component<INavProps, INavState> {
...
       return (
         <li key={key} className={css(styles.section, hasActiveChild(page) && styles.hasActiveChild)}>
-          <CollapsibleSection
-            collapsed={!(this.state.collapsedSections[key] || hasActiveChild(page))}
-            title={{
-              text: page.title,
-              onClick: () => this._handleSectionClick(key)
-            }}
-          >
+          <CollapsibleSection defaultCollapsed={!hasActiveChild(page)} title={page.title}>
```
Comment (ecraig12345) [inline apps/fabric-website/src/components/Nav/Nav.tsx]: Do you know if the Nav is destroyed and re-created when the active page changes? If so, this logic should work. If not, it probably won't work (provided CollapsibleSection is properly implementing controlled/uncontrolled behavior)--if the same CollapsibleSection instance is reused across renders, updates to the `defaultCollapsed` prop *should* be ignored.

Comment (jordandrako) [reply apps/fabric-website/src/components/Nav/Nav.tsx]: I'm pretty sure it is destroyed when the page changes. From my testing this works fine now, when it didn't before some of the updates Jason has made to `CollapsibleSection`.

Comment (jordandrako) [reply apps/fabric-website/src/components/Nav/Nav.tsx]: Feel free to test yourself as well: http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/9078/merge/fabric-website/dist/index.html?devhost#/controls/web/button

Comment (ecraig12345) [reply apps/fabric-website/src/components/Nav/Nav.tsx]: Sounds good then!
