### PR TITLE
Dropdown: Fix controlled multi-select dropdowns

### LINKED ISSUE #2971: DropDown does not render when updating selectedKeys with empty array.
### Bug Report

- __Package version(s)__: 5.0.1
- __Browser and OS versions__: Chrome 61.0.3163.100 - Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

I try to clear the selection in a multiselect DropDown list updating the variable (this.props.selectedGroups) in selectedKeys property as a empty array. 

```
            <Dropdown
              placeHolder="Custom placeholder"
              label="Custom example:"
              id="Customdrop1"
              ariaLabel="Custom dropdown example"
              onChanged={option => this.props.updateSelectedGroups(option.key)}
              selectedKeys={this.props.selectedGroups}
              multiSelect={true}
              multiSelectDelimiter=","
              options={this.props.groupItems}
            />
```

#### Actual behavior:

When updating selectedKeys there are no re-rendering of the DropDown component.

A **unqualified** guess gives DropDown.componentWillReceiveProps blocks the update since it's only validating newProps.selectedKey.

#### Expected behavior:

When providing an empty array of keys to selectedKeys i expect no selections in the DropDown component.

### LINKED ISSUE #3011: Dropdown controlled versions are not working
### Bug Report

- __Package version(s)__: Current examples at developer.microsoft.com/en-us/fabric#/components/dropdown
- __Browser and OS versions__: IE 11, Chrome 61.0.3163.100 - Win 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: https://developer.microsoft.com/en-us/fabric#/components/dropdown

#### Describe the issue:

Dropdown "controlled" versions are not working:

In IE 11 page is not loaded. May be this is a temporarily issue. 

In Chrome page is loaded, but the "Controlled" examples are not working: 
- "Controlled example" is working not at all (no selection possible). 
- "Multi-Select controlled example" seems to work, but does not really: F12 Developer Tools show following error: Uncaught TypeError: Cannot read property 'state' of undefined

#### Actual behavior:
- "Controlled" examples are not working resp. not working correctly. 
- Page is not loaded in IE 11

#### Expected behavior:
- No error messages in Developer Tools for controlled versions.
- Page is working in IE 11

### PR DESCRIPTION
**Pull request by MLoughry**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2971, Fixes #3011 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

To be blunt, I'm not sure who let the multi-select dropdown changes merge, but controlled multi-select dropdowns (and the example code using them) were fundamentally broken. I fixed up the logic in several places to properly branch based on the matrix of [{controlled, uncontrolled}, {single-select, multi-select}], and added at least a minimum test case to cover controlled multi-select dropdowns.

Additionally, clicking on an item in the controlled Dropdown example on the example page didn't work, as there was a TypeError thrown trying to dereference an undefined `this`. Fix was to apply @autobind to the offending method in the example code.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -98,17 +98,18 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
   public componentWillReceiveProps(newProps: IDropdownProps) {
     // In controlled component usage where selectedKey is provided, update the selectedIndex
     // state if the key or options change.
-    if (newProps.selectedKey !== undefined &&
+    if (this.props.multiSelect &&
+      newProps.selectedKeys !== undefined &&
+      (newProps.selectedKeys !== this.props.selectedKeys || newProps.options !== this.props.options)) {
+      this.setState({
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: there's a lot of redundancy here; possible to trip down? Destructure? Would it be better to just store a selectedIndexes state even in the single scenario?

Comment (MLoughry) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: I followed your suggestion, and added a truckload of new tests. However, there are two new ones (currently commented out) that seem to be failing due to some bug in the tests, as I've manually verified the scenarios. Not sure if you can help with the failing tests, or are willing to merge with what's passing.
