### PR TITLE
FocusTrapZone: Refactor trapping behavior

### LINKED ISSUE #4649: Modal focus trap gets broken by having an iframe as the last element in it
### Bug Report

- __Package version(s)__:
	- office-ui-fabric-react: "5.49.3"
	- react: "15.4.2"

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected:
- SP Home [Search](https://microsoft.sharepoint.com/_layouts/15/sharepoint.aspx?q=Fabric&v=search%2Ffiles) (Modal used for the preview that appears when clicking on a office file result)

#### Describe the issue:

I have a Modal with various click-targets inside it. With keyboard navigation I can tab between the different click/tab-targets. In the modal I also have an iframe, but this will not be included in the tab-order by default. If I set tabindex=”0” on the iframe, the iframe will be included in the tab-order. BUT this will break the FocusTrap on the Modal to also include tab targets in the browsers command bar. So, I can tab into the iframe and reach the tab targets there, but when tabbing out of the iframe the first tab-stop will be in the browser command-bar (“Tabs you’ve set aside” for Edge). This only happens if the iframe is the last tab-target in the Modal. If there are tab-targets after the iframe, the tabbing works fine and wraps around inside the modal.

#### Actual behavior:

Tabbing inside a Modal with an iframe as the last element will also include tab-targets of the browser command bar. 

#### Expected behavior:

Tabbing in a Modal should only cycle between tab-targets inside the Modal (even with an iframe at the end)

### LINKED ISSUE #5160: ChoiceGroup: focus is wrong when using ChoiceGroup inside of Panel
### Bug Report

OS: Windows 10 RS3
OS version: build 16299.371
Browser: Microsoft edge browser
Edge version: Microsoft Edge 41.16299.371.0
Firefox version: 59.0.2 (32-bit)
Version:20180413T115929

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
VSTS

Describe the issue:
Panel focus order is improper when choice group is rendered within the Panel.

Actual behavior:
Suppose you have choice group with options "a" and "b" in the panel.

The focus first goes to cross button of the panel, then the choice group option "a", then tabbing will make you focus the page title/window etc.

If you select option "b" my moving key down, then the focus will remain inside the Panel which is the expected behavior. But by default, as "a" is selected, the focus goes out of the Panel

Expected behavior:
Focus order should remain inside the panel only

### LINKED ISSUE #6526: [Utilities] getPreviousElement does not pass "tabbable" param to all places
### Reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/ePNjmo

### Bug Report 
- __Package version(s)__: 6.75.0
- __Browser and OS versions__: Chrome, Mac OS
 
#### Priorities and help requested: 
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal 
 
#### Describe the issue:
 
Used FocusTrapZone, few elements inside have ```tabindex="0"```, others ```tabindex="-1"```, also ```data-is-focusable="true"```. I used ```data-is-focusable="true"```, as I have FocusZone inside FocusZoneTrap
When tabbing through Focus Trap Zone, ```lastTabbableElement``` is defined incorrectly what leads to tab out from trap.
Please, look at the bug reproduction here https://codepen.io/anon/pen/ePNjmo

#### Actual behavior: 
It is possible to tab out from focus trap.
 
#### Expected behavior:
It is not possible to tab out from focus trap.

#### Fix
After investigating code, found out that ```getPreviousElement``` does not pass ```tabbable``` to all places, see https://github.com/OfficeDev/office-ui-fabric-react/blob/1b9405b3b64839975e16ee1fad04d7868d9e3b99/packages/utilities/src/focus.ts#L205

After trying to pass ```tabbable``` to that place, it fixed my issue.

### LINKED ISSUE #8055: FocusTrapZone: Refactor trapping behavior
### Environment Information 
 
- __Package version(s)__: 6.141.1
- __Browser and OS versions__: n/a

### Please provide a reproduction of the bug in a codepen:
 
CodePens in various linked issues below.
 
#### Actual behavior:
 
`FocusTrapZone` (FTZ) has issues with its trapping behavior for the following reasons:
1) Existing FTZ uses a key listener approach which does not capture all focus change events.
2) FTZ's key listener approach requires FTZ to parse all of its children to determine focusability, which leads to a lot of tricky edge cases and brittle functionality prone to regression.

The creation of this issue was triggered by #8053 in which recent workarounds were reverted since FTZ was identified as the root cause of issues being reported.
 
#### Expected behavior:
 
FTZ should really only care about when focus enters or leaves its boundaries, not what focus does within FTZ. A new approach should be taken that allows controls to behave according to their default behavior within FTZ and does not require FTZ to review its internal hierarchy for determining navigation behavior. FTZ should instead detect when focus enters or exits FTZ and then change focus behavior accordingly.

This issue should also not regress any recently closed FTZ issues and resolve open FTZ navigation / focus issues, including (but not limited to): #4191, #4649, #5160, #6526, #7679, #7839, #7891, #7992, #8011.

**Note:** Some of these issues were previously closed but were fixed or regressed with the merge of #8053. Therefore this issue **must** make sure these issues are also resolved and / or not regressed with the resolution for this issue.

#### Ideal outcome:

Ideally browsers should inherently support a CSS tag similar to `aria-modal` in which the browser handles trapping behavior. We should follow up or create another issue to track this discussion.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

### LINKED ISSUE #8136: [Accessibility] Focus is going out of the Calendar control while tabbing
### Environment Information 
 
- __Package version(s)__: 6.129.0 
- __Browser and OS versions__: Windows 10, EDGE / Chrome

### Repro steps
 
1. Goto https://developer.microsoft.com/en-us/fabric#/components/datepicker 
2.Tab till first date picker under Default DatePicker
3.Verify focus order after expanding the calendar control while pressing Tab

#### Actual behavior:
 
While tabbing inside the calendar the focus is going outside. Focus move to URL in the addressbar
 
#### Expected behavior:
 
The focus should move within the calendar until selection is done.​

#### User Impact:
 
Keyboard only users will find difficult while working through the application, if there are focus order issues​

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? ( No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8055, Fixes #4649, Fixes #6526, Fixes #5160, Fixes #8136 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The purpose of this PR is to refactor FocusTrapZone (FTZ) focus trapping behavior to resolve outstanding and recurring issues as described in #8055 and fixes multiple open issues. 

The refactor trapping behavior has been fixed from a key-handler based approach to a focus boundary approach. The fundamental difference is that now FTZ does not care how individual elements handle navigation within its boundaries. Now FTZ only cares when navigation attempts to leave FTZ boundaries. This fixes multiple issues regarding navigation issues with FTZ content. (There are some exceptions to this approach regarding nested FTZs and FocusZones.)

While refactoring trapping behavior, I also encountered the following issues / areas of improvement, which this PR also addresses:
- Focus utilities returning non-tabbable elements as tabbable.
- FTZ and focus utility unit test coverage.
- Broken FTZ examples.
- Broken FTZ behavior with 0 tabbable elements.
- No FTZ examples for 0 tabbable elements and embedded FocusZones.

This PR fixes multiple open FTZ navigation issues. I've also made sure recently fixed issues have not regressed. I've set up some CodePens running against an ngrok host (forgive me if these aren't working, I'll try to keep the server running. This has also made me realize it'd be nice to have PR bundles hosted for CodePens in general... #8217)

**EDIT**: It's really hard to keep these CodePens up and running because ngrok keeps timing out at some point. If you want to review them just let me know and I'll make sure they're running for a bit.

| Issue # | Example Running Against this PR | State |
|---------|---------------------------------|-------|
| #4191 | https://codepen.io/jasongore/pen/rPEamG | Still works. |
| #7679 | https://codepen.io/jasongore/pen/gqNEpG | Still works. |
| #4649 | https://codepen.io/jasongore/pen/qgzdbG | Fixed! |
| #5160 | https://codepen.io/jasongore/pen/pGXvEE | Fixed! (again) |
| #6526 | https://codepen.io/jasongore/pen/omrVbL | Fixed! |
| #7891 | https://codepen.io/jasongore/pen/bzPZyJ | Still works. |
| #7992, #8011 | https://codepen.io/jasongore/pen/PVrgEr | Still works. |
| #8136 | [DatePicker page](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/8216/merge/fabric-website-resources/dist/index.html#/examples/datepicker) | Fixed! |

#7839 still seems to be an issue but I think this is PR is a really good step and should be rereviewed in the context of #8055 later. (i.e. I need an FTZ break.)

#### Focus areas to test

Unit test coverage increased for FTZ and focus utilities.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8216)

### CODE REVIEW

File: packages/utilities/src/focus.ts [hunk 1]
```diff
@@ -56,17 +56,19 @@ export function getLastFocusable(
...
  * @param includeElementsInFocusZones - true if traversal should go into FocusZone descendants.
+ * @param checkNode - Include currentElement in search when true. Defaults to true.
  * @public
  */
 export function getFirstTabbable(
   rootElement: HTMLElement,
   currentElement: HTMLElement,
-  includeElementsInFocusZones?: boolean
+  includeElementsInFocusZones?: boolean,
+  checkNode: boolean = true
```
Comment (jdhuntington) [inline packages/utilities/src/focus.ts]: It would be nice to prevent this function from suffering a similar fate of `getNextElement` and having a difficult-to-parse list of booleans pile up in the parameter list.

Since you always call this with `false`, is there a semantically meaningful name that could be given to a new function that does what you want?

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx [hunk 2]
```diff
@@ -57,16 +60,23 @@ export class FocusTrapZone extends BaseComponent<IFocusTrapZoneProps, {}> implem
     const { className, ariaLabelledBy } = this.props;
     const divProps = getNativeProps(this.props, divProperties);
 
+    const bumperStyle: React.CSSProperties = {
+      pointerEvents: 'none'
+    };
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: @dzearing I could use your eyes on this on potential side effects / issues with this style. I tried various other methods:
> display: none

This breaks onFocus callbacks
> display: contents

This breaks onFocus callbacks
> position: absolute, left: -9999px, top: -9999px

This was causing weird browser scrolling issues when changing focus

File: packages/utilities/src/focus.ts (hunk 1 above)
Comment (JasonGore) [reply packages/utilities/src/focus.ts]: I don't think so. This is really a specialized version of `getNextElement` and `checkNode` has the same contextual meaning for both.

Comment (JasonGore) [reply packages/utilities/src/focus.ts]: I don't disagree with the comments regarding API surface but rather than refactor one method I'm going for consistency now. I think the API could be refactored as a whole as a separate effort, though.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx [hunk 3]
```diff
@@ -16,6 +15,10 @@ export class FocusTrapZone extends BaseComponent<IFocusTrapZoneProps, {}> implem
   private static _focusStack: FocusTrapZone[] = [];
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: @dagoff I saw this was added in #1111 which said it was added to prevent an infinite loop and I'm wondering if it's still needed. Was the infinite looping related to key handle? I did some brief experimentation of removing it with this new trapping behavior and I couldn't trigger an infinite loops.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx [hunk 4]
```diff
@@ -154,51 +227,25 @@ export class FocusTrapZone extends BaseComponent<IFocusTrapZoneProps, {}> implem
...
 
-  private _onKeyboardHandler = (ev: React.KeyboardEvent<HTMLDivElement>): void => {
-    if (this.props.onKeyDown) {
-      this.props.onKeyDown(ev);
-    }
-
-    // If the default has been prevented, do not process keyboard events.
-    if (ev.isDefaultPrevented()) {
-      return;
-    }
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: @jspurlin I see this was added in #4486, which basically allows consumers to block FTZ focus behavior. This PR will break this behavior, but I'm not sure how or why consumers would do this. What are valid use cases for this?

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx (hunk 3 above)
Comment (dagoff) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: The original trapping behavior (before I added focusStack) was that a FocusTrapZone would listen to all focus events, then if a focus event fired, the FocusTrapZone would check to see if the new focus target was inside the Zone. If it wasn't, the FocusTrapZone would forcibly focus something inside of it self. This would fire off another focus event, but the target would be in the Zone, so it wouldn't cause a loop if there was only one Zone. This worked fine when only 1 FocusTrapZone was on the page. With 2 or more, it was easy to end up in a state where they would fight for focus forever.

focusStack was an attempt to fix this. In short, each FocusTrapZone would push itself onto the stack at mount time and only the Zone on top of the stack is allowed to try to steal focus (or clicks).

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx (hunk 4 above)
Comment (jspurlin) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: There might be cases when a consumer might want to do something special in specific cases. For example, if TAB normally navigates linearly across focusable elements, but in some case(s) the consumer wants to move focus to a different element.

Removing this will break Office Online

Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: FocusTrapZone shouldn't be modifying or affecting focus behavior within it. It does not control focus within its contents anymore, so there's no longer any FTZ behavior to "stop" here.

If consumers of FTZ want to modify focus behavior, they can still do that. Nothing in FTZ is preventing key or focus handlers from working.

Comment (jspurlin) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: Yeah, after talking offline, getting on the same page, and since the divProps are still getting applied to the div _onKeyboardHandler isn't needed and things should continue to work
