### PR TITLE
List: Add a _notifyPageChanges function 

### LINKED ISSUE #3989: List: onPageAdded/Removed is not called if getPageHeight is provided as a prop
### Bug Report

- __Package version(s)__: :Latest

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  Normal

#### Describe the issue:
If the `getPageHeight` property is provided to List, the `onPageAdded` and `onPageRemoved` callbacks are never called.

This is because these callbacks are called within the `updatePageMeasurements` function, which does not need to be called if `getPageHeight` is provided.

The fix is to separate this logic into its own function

### PR DESCRIPTION
**Pull request by abettadapur**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3989 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

If the `getPageHeight` property is provided to List, the `onPageAdded` and `onPageRemoved` callbacks are never called.

This is because these callbacks are called within the `updatePageMeasurements` function, which does not need to be called if `getPageHeight` is provided.

The fix is to separate this logic into its own function, `_notifyPageChanges`, which is called in the `_updatePages` function

### CODE REVIEW

**Comment by cschleiden** [comment]
Can you add a change file?

File: packages/office-ui-fabric-react/src/components/List/List.tsx [hunk 1]
```diff
@@ -598,7 +600,51 @@ export class List extends BaseComponent<IListProps, IListState> implements IList
     });
   }
 
-  private _updatePageMeasurements(oldPages: IPage[], newPages: IPage[]) {
+  /**
+   * Notify consumers that the rendered pages have changed
+   * @param oldPages The old pages
+   * @param newPages The new pages
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/List/List.tsx]: add `props`?

File: packages/office-ui-fabric-react/src/components/List/List.tsx [hunk 2]
```diff
@@ -598,7 +600,51 @@ export class List extends BaseComponent<IListProps, IListState> implements IList
...
+      onPageAdded,
+      onPageRemoved
+    } = props;
+
+    if (onPageAdded || onPageRemoved) {
+      const renderedIndexes: {
+        [index: number]: IPage;
+      } = {};
+
+      for (let i = 0; i < oldPages.length; i++) {
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/List/List.tsx]: `for (const page of oldPages) {`?

File: packages/office-ui-fabric-react/src/components/List/List.tsx [hunk 3]
```diff
@@ -598,7 +600,51 @@ export class List extends BaseComponent<IListProps, IListState> implements IList
...
+        let page = oldPages[i];
+
+        if (page.items) {
+          renderedIndexes[page.startIndex] = page;
+        }
+      }
+
+      for (let i = 0; i < newPages.length; i++) {
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/List/List.tsx]: `for (const page of newPages) {`?

Comment (cschleiden) [reply packages/office-ui-fabric-react/src/components/List/List.tsx]: I see, just moved the code. Might be fine then.
