### PR TITLE
ComboBox: Check offsetParent exists before calling scrollIntoView

### LINKED ISSUE #3188: ComboBox throws null errors when shallow rendered using ReactTestUtils
### Bug Report

- __Package version(s)__: 4.51

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

When rendered using ReactTestUtils.renderIntoDocument (shallow rendering), ComboBox throws the following exception when the callout is opened.

```
BaseComponent.js:225 Exception in ComboBox.componentDidUpdate(): TypeError: Cannot read property 'scrollIntoView' of null
    at ComboBox._scrollIntoView (http://localhost:24426/Users/alebet/git/vso3/layout/L0/tfsjstestsclean/vssjstests/OfficeFabric/components/ComboBox/ComboBox.js:522:52)
    at ComboBox.componentDidUpdate (http://localhost:24426/Users/alebet/git/vso3/layout/L0/tfsjstestsclean/vssjstests/OfficeFabric/components/ComboBox/ComboBox.js:62:22)
```

The exception is because `this._selectedElement.offsetParent` is null because the selected element has not actually been rendered to the page.
See: https://stackoverflow.com/questions/306305/what-would-make-offsetparent-null

#### Expected behavior:
No exception should be thrown.

### PR DESCRIPTION
**Pull request by abettadapur**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3188
- [x] Include a change request file using `$ npm run change`

#### Description of changes
ComboBox used to call this._selectedElement.offsetParent.scrollIntoView without checking that offsetParent was defined. OffsetParent could be undefined in cases where the element was not yet rendered on the page, such as rendering via React shallow rendering.

Added null checks.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -920,7 +920,7 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
       onScrollToItem((currentPendingValueValidIndex >= 0 || currentPendingValue !== '') ? currentPendingValueValidIndex : selectedIndex);
     } else {
       // We are using refs, scroll the ref into view
-      if (this._selectedElement && scrollSelectedToTop) {
+      if (this._selectedElement && this._selectedElement.offsetParent && scrollSelectedToTop) {
```
Comment (jspurlin) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: I feel like these checks should be reworked so that we are only checking if selectedElement has an offsetParent once. It looks like every codepath requires that this offsetParent exists.

**Comment by abettadapur** [comment]
@jspurlin Updated the if checks
