### PR TITLE
Convert ContextualMenu to CSS in JS

### LINKED ISSUE #4169: Convert ContextualMenuItem to css-in-js
**Bug Report**
Describe the issue:
A few issues with the custom styles for IContextualMenuItem 

IContextualMenuItem accepts a style: React.CSSProperties but its seems like its never used in code, also the method provided for customStyling of `IContextualMenuItem`

```ts
getItemClassNames?: (theme: ITheme,
    disabled: boolean,
    expanded: boolean,
    checked: boolean,
    isAnchorLink: boolean,
    knownIcon: boolean,
    itemClassName?: string,
    dividerClassName?: string,
    iconClassName?: string,
    subMenuClassName?: string) => IMenuItemClassNames;
```

is not supportive either, to implement this method in consuming code your code needs to know lot about office-ui-fabric-code.

**Problems with implementing getItemClassNames in consuming repo.**
1.  `IMenuItemClassNames` type is required to implement this method which is non importable from package.
2.  To implement this method you need to copy paste `getContextualMenuClassNames` in `ContextualMenu.classNames.ts` and make changes to desirable properties.

**Suggestion:
style property should be of type `IContextualMenuStyles` which should be merged with default styles.**

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4169 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Completes the refactor of `ContextualMenu` to CSS in JS building off of #5356 and #5461. The last PR I opened (#5942) was flagged by size auditor and was less readable hence a reduced change-set.

- Marks `getClassName` and `style` props as `@deprecated` advocating the use of `mergeStyles` API.
- Uses `getGlobalClassNames` for `getStyle` method.

#### Focus areas to test

- `ContextualMenu` examples should render as they do in PROD / `master`.
- Check that the public API does not have any breaking change.
- Customize `ContextualMenu` and `ContextualMenuItem` via `styles` props.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 1]
```diff
@@ -39,57 +46,51 @@ export const getSplitButtonVerticalDividerClassNames = memoizeFunction(
   }
 );
 
-export const getContextualMenuClassNames = memoizeFunction(
```
Comment (KevinTCoughlin) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: Function is unused and incorrectly marked as `@default` for `IContextualMenuProps#getMenuClassNames`

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx [hunk 2]
```diff
@@ -204,7 +217,7 @@ export class ContextualMenuBase extends BaseComponent<IContextualMenuProps, ICon
       calloutProps,
       onRenderSubMenu = this._onRenderSubMenu,
       focusZoneProps,
-      getMenuClassNames
+      getMenuClassNames = getContextualMenuClassNames
```
Comment (KevinTCoughlin) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx]: This seems like a regression -- Its marked as the default classNames function for `getMenuClassNames`, but was no longer being set.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 3]
```diff
@@ -64,32 +71,51 @@ export const getContextualMenuClassNames = memoizeFunction(
...
-    checked: boolean,
-    isAnchorLink: boolean,
-    knownIcon: boolean,
-    itemClassName?: string,
-    dividerClassName?: string,
-    iconClassName?: string,
-    subMenuClassName?: string,
-    primaryDisabled?: boolean
-  ): IMenuItemClassNames => {
+  (props: IContextualMenuItemStyleProps): IContextualMenuItemStyles => {
```
Comment (KevinTCoughlin) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: Note to self: Looks like this may be a non-backwards compat change

**Comment by cliffkoh** [comment]
> import {

It's a little too late to maximise the benefit, but this file should really be ContextMenuItem.ts 

(alas we already lost most of the file history in ContextualMenu.base.ts)

---
Refers to: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.tsx:2 in ddb7c54. [](commit_id = ddb7c546efc5a32ac63024e7192f0b1e9d11f034, deletion_comment = False)

**Comment by KevinTCoughlin** [comment]
There's **one** remaining scenario to cover here.. that is for `IContextualMenuItemProps#styles` to work if provided. Its currently overlooked because the "Base" implementation uses `classNames` directly -- https://github.com/OfficeDev/office-ui-fabric-react/blob/0a8c7f53d2a89444c2cae0d722f64a5c54527f14/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.base.tsx#L8

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts [hunk 4]
```diff
@@ -202,7 +202,7 @@ export interface IContextualMenuProps extends IBaseProps<IContextualMenu>, IWith
   /**
    * Method to provide the classnames to style the contextual menu. Default value is the getMenuClassnames func
    * defined in ContextualMenu.classnames.
-   * @default getContextualMenuClassNames
+   * @deprecated Use `styles` prop of `IContextualMenuProps` to leverage mergeStyle API.
    */
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts]: :+1:

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts [hunk 5]
```diff
@@ -390,6 +389,7 @@ export interface IContextualMenuItem {
   /**
    * Additional styles to apply to the menu item
    * @defaultvalue undefined
+   * @deprecated in favor of mergeStyles API.
    */
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts]: would be good to further elaborate that this refers to the `styles` prop, since mergeStyles API might not be intuitive to people not that familiar with Fabric's codebase.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 6]
```diff
@@ -39,57 +46,51 @@ export const getSplitButtonVerticalDividerClassNames = memoizeFunction(
...
+  linkContent: 'ms-ContextualMenu-linkContent',
+  linkContentMenu: 'ms-ContextualMenu-linkContent',
+  icon: 'ms-ContextualMenu-icon',
+  checkmarkIcon: 'ms-ContextualMenu-checkmarkIcon',
+  subMenuIcon: 'ms-ContextualMenu-submenuIcon',
+  label: 'ms-ContextualMenu-itemText',
+  secondaryText: 'ms-ContextualMenu-secondaryText'
+};
 
 export const getItemClassNames = memoizeFunction(
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: >memoizeFunction [](start = 33, length = 15)

I think @dzearing had a specific scenario where memoizing the function causes undesirable side effects. I don't know the details of it but this is why the classNamesFunction method itself does not memoize (though that layer of indirection was precisely to add global memoization initially).

**Comment by cliffkoh** [comment]
>                 '.ms-Fabric--isFocusVisible &:focus, .ms-Fabric--isFocusVisible &:focus:hover': styles.rootFocused,

these things here are global classnames as well hmm. Can you import `IsFocusVisibleClassName` from utilities? (not 100% sure if it is importable)

---
Refers to: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts:100 in ddb7c54. [](commit_id = ddb7c546efc5a32ac63024e7192f0b1e9d11f034, deletion_comment = False)

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 7]
```diff
@@ -137,30 +139,32 @@ export const getItemClassNames = memoizeFunction(
...
         styles.icon,
         iconClassName,
-        disabled && ['is-disabled', styles.iconDisabled]
+        disabled && [classNames.isDisabled, styles.iconDisabled]
       ],
+      iconColor: styles.iconColor,
       checkmarkIcon: [
-        'ms-ContextualMenu-checkmarkIcon',
+        classNames.checkmarkIcon,
         knownIcon && 'ms-ContextualMenu-checkmarkIcon ' && styles.checkmarkIcon,
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: >ms-ContextualMenu-checkmarkIcon [](start = 22, length = 31)

Global Classname

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 8]
```diff
@@ -137,30 +139,32 @@ export const getItemClassNames = memoizeFunction(
...
+        classNames.linkContentMenu,
         styles.linkContent,
         {
           justifyContent: 'center'
         }
       ],
       icon: [
-        'ms-ContextualMenu-icon',
+        classNames.icon,
         knownIcon && 'ms-ContextualMenu-iconColor ' && styles.iconColor,
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: >ms-ContextualMenu-iconColor [](start = 22, length = 27)

Global Classname

Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: 👍

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts (hunk 7 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: 👍

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts (hunk 5 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts]: 👍

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts [hunk 9]
```diff
@@ -534,7 +544,7 @@ export interface IContextualMenuStyleProps {
   // Insert ContextualMenu style props below
 }
 
-export interface IContextualMenuStyles {
+export interface IContextualMenuStyles extends IButtonStyles {
```
Comment (KevinTCoughlin) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts]: fixing

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts (hunk 6 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: I'm open to addressing this just not sure what to look for. I kept it as-is to avoid changing more than necessary given what else I had to do throughout here.

**Comment by KevinTCoughlin** [comment]
Here's a diff to test the two methods of styling via mergeStyles that this PR provides:

- Customizing menu styling via `IContextualMenuProps#styles?`
- Customizing menu item styling via `IContextualMenuItem#styles?`

```diff
diff --git a/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx b/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx
index 2a4b26fec..4df6207b2 100644
--- a/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx
@@ -1,9 +1,29 @@
 // @codepen
 import * as React from 'react';
-import { ContextualMenuItemType } from 'office-ui-fabric-react/lib/ContextualMenu';
+import {
+  ContextualMenuItemType,
+import {
+  ContextualMenuItemType,
+  IContextualMenuStyles,
+  IContextualMenuItemStyles
+} from 'office-ui-fabric-react/lib/ContextualMenu';
 import { DefaultButton } from 'office-ui-fabric-react/lib/Button';
 import './ContextualMenuExample.scss';

+const getMenuStyles = (): Partial<IContextualMenuStyles> => {
+  return {
+    root: {
+      background: 'blue'
+    }
+  };
+};
+
+const getMenuItemStyles = (): Partial<IContextualMenuItemStyles> => {
+  return {
+    linkContent: {
+      color: 'white'
+    }
+  };
+};
+
 export class ContextualMenuBasicExample extends React.Component {
   constructor(props: {}) {
     super(props);
@@ -20,11 +40,13 @@ export class ContextualMenuBasicExample extends React.Component {
           text="Click for ContextualMenu"
           menuProps={{
             shouldFocusOnMount: true,
+            styles: getMenuStyles,
             items: [
               {
                 key: 'newItem',
                 text: 'New',
-                onClick: () => console.log('New clicked')
+                onClick: () => console.log('New clicked'),
+                styles: getMenuItemStyles
               },
```

There are also tests added to check that the API is backwards compatible w.r.t:

- `getItemClassNames?`
- `getMenuClassNames?`
- `style?`

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts [hunk 10]
```diff
@@ -389,6 +393,11 @@ export interface IContextualMenuItem {
     primaryDisabled?: boolean
   ) => IMenuItemClassNames;
 
+  /**
+   * Call to provide customized styling that will layer on top of the variant rules
+   */
+  styles?: IStyleFunctionOrObject<IContextualMenuItemStyleProps, IContextualMenuItemStyles>;
```
[the remark this answers is not in the document]
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts]: We spoke in-person -- I'm going to replace this `styles?` with the props bag `itemProps?: IContextualMenuItemProps` so that we don't have to change API signature in the future 👍. Posting iteration shortly.

[the remark this answers is not in the document]
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts]: Done in https://github.com/OfficeDev/office-ui-fabric-react/pull/6094/commits/8f98b2f50c8a9693b95223534dc2118686069f52

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts [hunk 11]
```diff
@@ -10,7 +10,7 @@ import {
 import { IContextualMenuStyles, IMenuItemStyles } from './ContextualMenu.types';
 import { memoizeFunction } from '../../Utilities';
 
-const ContextualMenuItemHeight = '32px';
+export const ContextualMenuItemHeight = '32px';
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.cnstyles.ts]: >ContextualMenuItemHeight [](start = 13, length = 24)

nit: as this is a symbolic const, it should use symbolic const notation (`CONTEXTUAL_MENU_ITEM_HEIGHT`)

**Comment by cliffkoh** [comment]
>                 '.ms-Fabric--isFocusVisible &:focus, .ms-Fabric--isFocusVisible &:focus:hover': styles.rootFocused,

This still seems to be a problem in Iteration 21

---
In reply to: [416382634](https://github.com/OfficeDev/office-ui-fabric-react/pull/6094#issuecomment-416382634) [](ancestors = 416382634)

---
Refers to: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts:100 in ddb7c54. [](commit_id = ddb7c546efc5a32ac63024e7192f0b1e9d11f034, deletion_comment = False)

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 12]
```diff
@@ -39,57 +46,54 @@ export const getSplitButtonVerticalDividerClassNames = memoizeFunction(
...
+  iconColor: 'ms-ContextualMenu-iconColor',
+  checkmarkIcon: 'ms-ContextualMenu-checkmarkIcon',
+  subMenuIcon: 'ms-ContextualMenu-submenuIcon',
+  label: 'ms-ContextualMenu-itemText',
+  secondaryText: 'ms-ContextualMenu-secondaryText'
+};
 
+// TODO: Audit perf. impact of and potentially remove memoizeFunction.
+//       https://github.com/OfficeDev/office-ui-fabric-react/issues/5534
 export const getItemClassNames = memoizeFunction(
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: I don't think memoize is going to work here. The input will constantly mutate, breaking the point.

Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: 👍 will remove in subsequent PR

Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: You called it #6738.
