### PR TITLE
Panel navigation layout

### LINKED ISSUE #3227: Close X is in the wrong place on Panel
Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Reproes in Edge and IE11, but not Chrome.

Products/sites affected: OneDrive, SharePoint, and anything that uses a panel

The close X is on the left, and should be on the right

image

This isn't even close to spec.
image

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #3227
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

CSS overrides were same specificity level, so sometimes would come 2nd, and position value wouldn't work. This is a cleaner approach using flexbox instead of absolute positioning. And moves button overrides into a styles attribute on the button.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Panel/Panel.tsx [hunk 1]
```diff
@@ -208,13 +208,28 @@ export class Panel extends BaseComponent<IPanelProps, IPanelState> implements IP
...
-          iconProps={ { iconName: 'Cancel' } }
-        />
+        <div className={ css('ms-Panel-navigation', styles.navigation) } >
+          <IconButton
+            styles={
+              {
+                root: {
+                  height: 'auto',
+                  width: '44px',
+                  color: ColorClassNames.neutralSecondary,
```
Comment (phkuo) [inline packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: not sure what colorclassnames does, but why not use Theme.palette.neutralSecondary?

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: Ahh, true true. I just grabbed the first color related thing I could find :) Grabbing from theme makes more sense.

**Comment by micahgodbolt** [comment]
@phkuo all good now?
