### PR TITLE
Dropdown: Fix _onDropdownKeyDown focusing on Header/Separator option

### LINKED ISSUE #1913: Dropdown: Can select group headers/separators using arrow keys
See https://dev.office.com/fabric#/components/dropdown

1. Focus the first dropdown
2. With the dropdown collapsed, you can use arrow keys to select "Actions" and "People"

You cannot do that with the dropdown expanded. 

image

image

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1913,  #1897
- [x] Include a change request file if publishing 
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Description of changes

- Fixes _onDropdownKeyDown to not focus on header/separator items
- Add key prop to render header method.
- Add prevent scroll check on keypress up/down to prevent event propagation if current index is not 0 or the length of items.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -385,14 +411,18 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
         break;
 
       case KeyCodes.up:
-        this.setSelectedIndex(this.state.selectedIndex - 1);
+        newIndex = this._moveIndex(this.state.selectedIndex - 1);
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: To simplify this logic, why not just do this:

```tsx
this._moveIndex(ev, -1);
return;
```
Then make move index do the work of moving in that direction;

```tsx
private _moveIndex(directionStep, ev) {
  let currentIndex = this.state.selectedIndex + directionStep;

  // Iterate to the next selectable thing.
  while (currentIndex >= 0 && currentIndex <= options.length && options[currentIndex].itemType !== Normal) {
    currentIndex += directionStep;
  }

  // If thing is different than state and selectable...
  if (currentIndex !== this.state.selectedIndex && currentIndex >= 0 && currentIndex < options.length && options[currentIndex].itemType === Normal) {

    this.setSelectedIndex(currentIndex);
    ev.stopPropagation();
    ev.preventDefault();
  }
}

Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Hey @dzearing, made some changes to the method.  I think this may be a better solution cause it solves keypress home/end as well, instead of changing the selectedIndex by 1 for just the up/down keypress.  What do you think? 

Also, we don't want to check against Normal type, since options won't show that unless defined explicitly.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -195,6 +195,32 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
     }
   }
 
+  // Find next valid dropdown option
+  private _moveIndex(index: number, selectedIndex: number): number {
+    // Return selectedIndex if nothing has changed
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: i'm confused. I reviewed this before. I suggested to rename this:

`_moveIndex(stepValue: number, ev: React.KeyboardEvent<HTMLElement>) { ... }`

**Comment by leddie24** [comment]
Fixed, can you take another look when you get a chance @dzearing ?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 3]
```diff
@@ -386,23 +420,31 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
         break;
 
       case KeyCodes.up:
-        this.setSelectedIndex(this.state.selectedIndex - 1);
+        newIndex = this._moveIndex(-1, selectedIndex - 1, selectedIndex);
+        preventScroll = newIndex !== selectedIndex;
+        this.setSelectedIndex(newIndex);
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: this part is duplicated 4 times, can we optimize that?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 4]
```diff
@@ -368,6 +398,10 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
 
   @autobind
   private _onDropdownKeyDown(ev: React.KeyboardEvent<HTMLElement>) {
+    let preventScroll = true;
+    let newIndex: number;
+    let { selectedIndex } = this.state;
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: `const`

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 5]
```diff
@@ -305,8 +333,10 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
 
   private _renderHeader(item: IDropdownOption): JSX.Element {
     let { onRenderOption = this._onRenderOption } = this.props;
+    let { key } = item;
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: `const`

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 6]
```diff
@@ -196,6 +196,34 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
     }
   }
 
+  // Find next valid dropdown option
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: can you use `/** jsdoc */` comments?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 7]
```diff
@@ -196,6 +196,34 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+  private _moveIndex(stepValue: number, index: number, selectedIndex: number): number {
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: can we add unit tests for this change?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 8]
```diff
@@ -196,6 +196,34 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+    } else {
+      // If current index is a header or divider, increment by step
+      while (options[index].itemType === DropdownMenuItemType.Header
+        || options[index].itemType === DropdownMenuItemType.Divider) {
+        // If index + stepValue is out of bounds, reverse step direction
+        if (index + stepValue < 0 || index + stepValue >= options.length) {
+          stepValue *= -1;
+        }
+        index = index + stepValue;
+      }
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: if for whatever reason I only have Headers in my list, wouldn't that result in an infinite loop?

Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Not entirely sure how to fix this, do you have a suggestion on how to take this into account?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 9]
```diff
@@ -196,6 +196,41 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+      return selectedIndex;
+    }
+
+    const { options } = this.props;
+    if (index < 0) {
+      // If index < 0, return first valid option
+      return this._moveIndex(stepValue, 0, selectedIndex);
+    } else if (index >= options.length) {
+      // If index > last option index, return last valid option
+      return this._moveIndex(stepValue, options.length - 1, selectedIndex);
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: This is recursive and can stack overflow in some conditions as we discussed.

Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Fixed in new commit

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 8 above)
Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Fixed. Added a step counter variable, if it exceeds the options' length, then it breaks out of the loop and returns the selectedIndex, which should be -1

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 10]
```diff
@@ -196,6 +196,49 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+    // Set starting index to last option index if greater than options.length
+    if (index >= options.length) {
+      index = options.length - 1;
+    }
+    // If current index is a header or divider, increment by step
+    while (options[index].itemType === DropdownMenuItemType.Header
+      || options[index].itemType === DropdownMenuItemType.Divider) {
+
+      // If stepCounter exceeds length of options, then return selectedIndex (-1)
+      if (stepCounter >= options.length) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: or <= 0 ?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 11]
```diff
@@ -196,6 +196,49 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+        return selectedIndex;
+      }
+      // If index + stepValue is out of bounds, reverse step direction
+      if (index + stepValue < 0 || index + stepValue >= options.length) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: This looks like danger zone here... maybe you should remove this. It is unclear why you would need to reverse the step.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 12]
```diff
@@ -196,6 +196,49 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+    // Set starting index to 0 if index is < 0
+    if (index < 0) {
+      index = 0;
+    }
+    // Set starting index to last option index if greater than options.length
+    if (index >= options.length) {
+      index = options.length - 1;
+    }
+    // If current index is a header or divider, increment by step
+    while (options[index].itemType === DropdownMenuItemType.Header
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Can this condition simply be itemType !== DropdownMenuItemType.Item or something

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 11 above)
Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Takes into account cases where a non Normal type is at the start or end of a Dropdown list.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 10 above)
Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Can you elaborate on this?  Not 100% sure I'm following your logic.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 12 above)
Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Fixed.  Not 100% sure if this is the proper way to do this (I set this in the constructor, looped through the options, if itemType is non-existent then set it to Normal.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 13]
```diff
@@ -196,6 +201,47 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+   * @param selectedIndex The selectedIndex Dropdown's state
+   * @returns The next valid dropdown option's index
+   */
+  private _moveIndex(stepValue: number, index: number, selectedIndex: number): number {
+    // Return selectedIndex if nothing has changed
+    if (selectedIndex === index) {
+      return selectedIndex;
+    }
+    const { options } = this.props;
+    let stepCounter = 0;
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: nit, declare close to where it's used?

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 14]
```diff
@@ -196,6 +201,47 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
...
+
+    // Set starting index to 0 if index is < 0
+    if (index < 0) {
+      index = 0;
+    }
+    // Set starting index to last option index if greater than options.length
+    if (index >= options.length) {
+      index = options.length - 1;
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: can there be a case when options.length is 0? Then we'd set the index to -1 and then try to index in line 228

Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Fixed in line 214

```
if (selectedIndex === index || options.length === 0) {
   return selectedIndex;
}
```

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 13 above)
Comment (leddie24) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: fixed
