### PR TITLE
Base Picker: check unmount state when updating suggestion list

### LINKED ISSUE #1202: BasePicker.updateValue does not check unmount flag in promise.then
### Bug Report

- __Package version(s)__: all
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes (I like this question 😄  )

Requested priority: Normal

#### Describe the issue:

We have a scenario that, the picker is only for *once*. It means that, user inputs something into the picker and select, we *immediately* unmount the picker.

However, in [`BasePicker.updateValue`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L190) method, the resolve logic is async and in some case, the last promise is resolved after user select the item and DOM unmounted. In such case, there is no unmount check in [promise.then](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L213) and cause runtime error.

#### Actual behavior:

Runtime error.

#### Expected behavior:

No error.

### If applicable, please provide a codepen repro:

(If I have time...)

### PR DESCRIPTION
**Pull request by MirandaGe**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1202 
- [x] Include a change request file using `$ npm run change`

### CODE REVIEW

**Comment by MirandaGe** [comment]
Hi @joschect, can you help review this PR?

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -306,9 +312,13 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
       }
     } else if (suggestionsPromiseLike && suggestionsPromiseLike.then) {
       if (!this.loadingTimer) {
-        this.loadingTimer = this._async.setTimeout(() => this.setState({
-          suggestionsLoading: true
-        }), 500);
+        this.loadingTimer = this._async.setTimeout(() => {
```
Comment (lijunle) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: The better way is to `clearTimeout(this.loadingTimer)` in `unmount`.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 2]
```diff
@@ -97,6 +99,10 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
     }
   }
 
+  public componentWillUnmount(): void {
+    this._isUnmounted = true;
```
Comment (lijunle) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: I suppose you need `super.componentWillUnmount()` here.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 3]
```diff
@@ -332,9 +342,11 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
             this.resolveNewValue(updatedValue, newSuggestions);
           } else {
             this.suggestionStore.updateSuggestions(newSuggestions);
-            this.setState({
-              suggestionsLoading: false
-            });
+            if (!this._isUnmounted) {
```
Comment (lijunle) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Another option is to set `this.currentPromise` to `undefined` in `unmount`. It does not need to introduce the `isUnmount` field.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 4]
```diff
@@ -44,6 +44,8 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
   protected loadingTimer: number | undefined;
   protected currentPromise: PromiseLike<any>;
 
+  private _isUnmounted: boolean = false;
```
Comment (lijunle) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: `isMount`/`isUnmount` is anti-pattern, we should try our best to avoid it.

> https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx (hunk 2 above)
Comment (MirandaGe) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Good catch! I will try avoid using _isUnmounted first.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx (hunk 1 above)
Comment (MirandaGe) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: I don't think it will work. There will always be a host element there, only the expanding card part will be mount and unmount.

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx (hunk 3 above)
Comment (MirandaGe) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Good suggestion! I would like to try it.

**Comment by joschect** [comment]
All of @lijunle 's comments are spot on.
