### PR TITLE
Changed DatePicker role to be more accurate for screen readers 

### LINKED ISSUE #2403: DatePicker Accessibility: When tabbing to the DatePicker text input, you are not informed how to open the calendar picker
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__: Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: http://tasks.office.com

#### Describe the issue:

Voice over doesn't explain how to open the date picker

#### Actual behavior:

You tab into the editable text element and it says "Select a date. Select a date, editing". 

#### Expected behavior:

For it to at least say "Select a date. Press enter to open calendar picker".or something to that effect.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/YxZWQg

### PR DESCRIPTION
**Pull request by rickyp-ms**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2403 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Since the focusable element is a input box, no indication that a menu is accessible is noted via Narrator. Setting it to menu or combobox also now voices if it is collapsed or expanded.

#### Focus areas to test

Datepicker accessibility

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx [hunk 1]
```diff
@@ -205,7 +205,9 @@ export class DatePicker extends BaseComponent<IDatePickerProps, IDatePickerState
             } }
             readOnly={ !allowTextInput }
             value={ formattedDate }
-            ref='textField' />
+            ref='textField'
+            role={ allowTextInput ? "combobox" : "menu" }
```
Comment (kristoferbrown) [inline packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: Using double quotes instead of single quotes here is upsetting tslint, please change them.

Comment (rickyp-ms) [inline packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: Should be resolved now.
