### PR TITLE
Calendar: make today configurable to support different timezone

### LINKED ISSUE #1683: Calendar: date of today should be configurable
### Bug Report
Calendar uses new Date() to show today. However today could be different than the client date with different timezone. For example, if current time in PST was 3 PM 5/2, it could be 5/3 in different timezone. 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Actual behavior:
Today is using client timezone

#### Expected behavior:
Today should be configurable to allow using user timezone

### PR DESCRIPTION
**Pull request by dolguji**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #1683
- [ ] Include a change request file if publishing 
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Description of changes

Currently Calendar component selects today based on client's timezone. In order to support different timezone, I made the value of today configurable. It's an optional parameter. If not specified, it falls back to the current behavior. One could pass a different date to set today based on user preferred timezone.

#### Focus areas to test

Ensure 'go to today' works as expected.

### CODE REVIEW

**Comment by dolguji** [comment]
I fixed #1594 as part of this change, but reverted the style change after seeing comment in the issue.

File: packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx [hunk 1]
```diff
@@ -67,7 +68,7 @@ export class Calendar extends BaseComponent<ICalendarProps, ICalendarState> impl
     }
 
     this.setState({
-      selectedDate: value || new Date()
+      selectedDate: value || (today || new Date())
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: isn't `|| today;` enough?

Comment (dolguji) [inline packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: This is in case null value was passed in since default param won't be used in such case.
