### PR TITLE
Addressing Issue #4305 - Input multiline inside Panel doesn't compatible with the auto spell check by Grammarly extension

### LINKED ISSUE #4305: Input multiline inside Panel doesn't compatible with the auto spell check by Grammarly extension
### Bug Report

- __Package version(s)__: office-ui-fabric-react v.5.41.2
- __Browser and OS versions__: Google Chorme v.64.0.3282.186

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: N/A

#### Describe the issue:

Step1: Install Grammarly extension. Restart Google Chorme browser .

Step2: Create a panel. Inside it, create an input multiline (text area).

Step3: Open that panel and fill any wrong word. Ex: contigiuration.

Step4:  Upon hovering the mouse on the wrong spelling words, it shows the correct word. Now click on the correct word twice to insert the word.

#### Actual behavior:

That word didn't change.

#### Expected behavior:

That word should change when click on the correct word

### If applicable, please provide a codepen repro:

https://codepen.io/write/input-inside-panel-doesn-t-compatible-with-the-auto-spell-check-by-grammarly-extension

image

### PR DESCRIPTION
**Pull request by oengusmacinog**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4305 #3333 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The initial issue referenced the fact that the popular Chrome extension Grammarly was not working in Fabric's Panel component.  After some investigation, I found that the FocusTrapZone was blocking all click events while the Panel was open.

This is solved by setting **FocusTrapZone**'s prop `isClickableOutsideFocusTrap` to true.  As far as I can tell this is meant to keep the focus on the component, but in the case of the Panel, there is an overlay over the rest of the app so there is no obvious reason for this to default to false and block click events outside the FocusTrapZone completely.

### CODE REVIEW

**Comment by mikewheaton** [comment]
Makes sense to me. The FocusTrapZone should still prevent keyboard tabbing outside of the Panel, but won't block the Grammarly buttons from receiving click events. I suppose this means Grammarly still can't be used by keyboard navigation, although I'm not sure how well it usually supports it.

File: packages/office-ui-fabric-react/src/components/Panel/Panel.tsx [hunk 1]
```diff
@@ -175,9 +175,7 @@ export class Panel extends BaseComponent<IPanelProps, IPanelState> implements IP
                 ) }
               style={ customWidthStyles }
               elementToFocusOnDismiss={ elementToFocusOnDismiss }
-              isClickableOutsideFocusTrap={
-                isLightDismiss || isHiddenOnDismiss || (focusTrapZoneProps && focusTrapZoneProps.isClickableOutsideFocusTrap)
-              }
+              isClickableOutsideFocusTrap={ true }
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: this seems like a sledgehammer solution. I'm not sure if this is correct. Perhaps someone from @antonlabunets team could help validate? (@zoarif or @srideshpande  maybe)

Comment (oengusmacinog) [reply packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: I agree it does seem like a 'sledgehammer' solution.  Obviously, if your app needs to allow these clicks you can set the implementation to true and be good.  However, this will block the usage of Grammarly and any third party extensions and such completely since they will be outside the focus zone.

The main thing is it seems unnecessary since there is an overlay blocking the rest of the page while the panel is open with default settings.  The only area I am unsure about is when you navigate the page using something other than a mouse - I didn't have any obvious issues that way but I'm not an expert on accessibility testing.

I'm open to ideas.

Comment (zoarif) [reply packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: Instead of changing the existing logic, may be add a prop in Panel for isClickableOutsideFocusTrap and set to true in your app?

Comment (zoarif) [reply packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: May be set the default to true and provide a prop if the app wants to set it to false?

File: packages/office-ui-fabric-react/src/components/Panel/Panel.tsx [hunk 2]
```diff
@@ -175,7 +175,7 @@ export class Panel extends BaseComponent<IPanelProps, IPanelState> implements IP
                 ) }
               style={ customWidthStyles }
               elementToFocusOnDismiss={ elementToFocusOnDismiss }
-              isClickableOutsideFocusTrap={ true }
+              isClickableOutsideFocusTrap={ focusTrapZoneProps && !focusTrapZoneProps.isClickableOutsideFocusTrap ? false : true }
```
Comment (zoarif) [inline packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: Is there a reason to remove isLightDismiss || isHiddenOnDismiss ?

Comment (oengusmacinog) [reply packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: superfluous now that we are switching the default to 'true'. If the props isLightDismiss or isHiddenOnDismiss were set to 'true' before it would set this to 'true' so clicks wouldn't be blocked.

Comment (zoarif) [reply packages/office-ui-fabric-react/src/components/Panel/Panel.tsx]: makes sense.
