### PR TITLE
GroupedList: Using level to determine nestingDepth when it is given

### LINKED ISSUE #9693: GroupedList incorrect value for parameter nestingDepth in onRenderCell
To compute the nestingDepth passed as argument to `onRenderCell`, the GroupedList component only traverses the first (leftmost) "branch" of the group tree and uses this value for every item (every call to `onRenderCell`).

There are 2 problems here:
* all items share same depth
* depth of the leftmost branch is used

Maybe this code should somehow use the `level` property declared on the IGroup interface.

Code is here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L247

### Environment Information 
 
- __Package version(s)__: office-ui-fabric-react 7.5.1
- __Browser and OS versions__: not relevant

### Please provide a reproduction of the bug in a codepen:
 
expand all groups and check left margin of items
both examples are identical, except for the ordering of the groups

https://codepen.io/anon/pen/BgVwjb
https://codepen.io/anon/pen/ydEzXO

 
#### Actual behavior:
 
item depth incorrect
 
#### Expected behavior:
 
items to have margin corresponding to their depth

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority:  Normal
 
Products/sites affected: ?

### PR DESCRIPTION
**Pull request by khmakoto**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9693
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The `groupNestingDepth` is being computed by travelling the leftmost branch of the `GroupedList` tree and using this value for every item. This PR makes it so that if the user specifies a `level` in the `IGroup` attributes the `groupNestingDepth` uses this instead.

Below is an example of how this is fixed (red lines are where the groups are and green lines are where they should be if it is different).

__Before:__

image

__After:__

image

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9811)

### CODE REVIEW

**Comment by khmakoto** [comment]
@KevinTCoughlin we could further improve this by passing a prop to `GroupListSection` which specifies the current `groupNestingDepth` but I think this change should still go in regardless.

File: packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx [hunk 1]
```diff
@@ -341,6 +341,8 @@ export class GroupedListSection extends BaseComponent<IGroupedListSectionProps,
       compact
     } = this.props;
 
+    const nestingDepth = (subGroup.level && subGroup.level + 1) || groupNestingDepth;
```
Comment (Vitalius1) [inline packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx]: NIT: Perhaps a ternary would be more readable.
```suggestion
    const nestingDepth = subGroup.level ? subGroup.level + 1 : groupNestingDepth;
```
