### PR TITLE
IStyleSet: Now uses a form that works better in TS 2.8 and does not require TS 3.0 to work.

### LINKED ISSUE #6615: [merge-styles] TypeScript error TS2349 when trying to invoke subComponentStyle members which are not defined as IStyleFunctionOrObject
### Bug Report 

- __Package version(s)__:
  - merge-styles: 6.9.4 (as a dependency of office-ui-fabric-react 6.81.0)
  - typescript: 3.0.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, if I find the cause of this issue.
 
Requested priority: High
 
#### Describe the issue:
 
**This is a regression.** The error did not occur with office-ui-fabric-react 6.58.0 / merge-styles 6.7.0

Given the following interface
```ts
export interface Styles {
	root: IStyle;

	subComponentStyles: {
		label: IStyleFunctionOrObject<ILabelStyleProps, ILabelStyles>;
		button: Partial<IButtonStyles>;
	};
}
```

applying the `IProcessedStyleSet` mapping type maps `button` to `never`:
```ts
type Processed = IProcessedStyleSet<Styles>;
type Label = Processed["label"]; // IStyleFunction<ILabelStyleProps, ILabelStyles>
type button = Processed["button"]; // never
```

 
#### Actual behavior:
 
Trying to call the button property causes TS to fail compilation with the mentioned error:
```
Error TS2349: Cannot invoke an expression whose type lacks a call signature.
Type 'never' has no compatible call signatures.
```
 
#### Expected behavior:
 
Calling the button property returns a `Partial<IButtonStyles>`

### PR DESCRIPTION
**Pull request by cliffkoh**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6615 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Addresses the issue in #6615 and fix the runtime bug where subComponentStyles were not processed when only 1 argument is passed into mergeStyleSets because we do not call concatStyleSets.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/merge-styles/src/mergeStyleSets.ts [hunk 1]
```diff
@@ -108,9 +106,7 @@ export function mergeStyleSets(
     // we have guarded against falsey values just above.
     styleSet!;
 
-  if (styleSets.length > 1) {
-    concatenatedStyleSet = concatStyleSets(...styleSets);
-  }
+  concatenatedStyleSet = concatStyleSets(...styleSets);
```
[the remark this answers is not in the document]
Comment (cliffkoh) [reply packages/merge-styles/src/mergeStyleSets.ts]: concatStyleSets works properly with a single argument. But before subComponentStyles was a thing, there wasn't much point to call concatStyleSets with only a single argument (even though it absolutely took in and handled 1 argument). 

When subComponentStyles was introduced, it is probably a bug/oversight that this length check was not removed...

File: packages/merge-styles/src/IStyleSet.ts [hunk 2]
```diff
@@ -5,18 +5,13 @@ export type Diff<T extends keyof any, U extends keyof any> = ({ [P in T]: P } &
...
-
 /**
  * Helper function whose role is supposed to express that regardless if T is a style object or style function,
  * it will always map to a style function.
  *
- * Note: the commmented segment is the right expression but it is buggy in 2.8.2. Once Fabric upgrades to Typescript 3,
- *  we should uncomment the commented segmment below as well as uncomment the test in mergeStyleSets.test.ts.
- *
- * See https://github.com/OfficeDev/office-ui-fabric-react/issues/6124.
+ * @author [Nimelrian](https://github.com/Nimelrian) in https://github.com/OfficeDev/office-ui-fabric-react/issues/6615
```
Comment (dzearing) [inline packages/merge-styles/src/IStyleSet.ts]: could you remove the @author tag here? I don't think there's value in doing that. We collectively own the code.

Comment (cliffkoh) [reply packages/merge-styles/src/IStyleSet.ts]: @dzearing  That's just to give credit to @Nimelrian. If I did not do this, it would look like I devised this clever way that works in TS 2.8 as well (the way I came up with is buggy in 2.8 that they fixed in subsequent Typescript releases.)

LMK if you still think I should remove it.

@Nimelrian feel free to chime in if you lean one way or the other on this issue too.

Comment (cliffkoh) [reply packages/merge-styles/src/IStyleSet.ts]: Just to be clear, this is not to say that @Nimelrian owns the code and he will be responsible for fixing all bugs - this is just proper attribution that this is a valued community contribution.

Comment (Nimelrian) [reply packages/merge-styles/src/IStyleSet.ts]: You're free to remove that author tag., I have no feelings either way about it. Open Source is a community effort. A mention in the release notes would be enough :)
