### PR TITLE
merge-styles Jest serializer no longer crashes with keyframes

### LINKED ISSUE #6149: jest-serializer-merge-styles: @keyframes breaks _serializeRules
### Please provide a reproduction of the bug in a codepen:
 
Not sure how to repro jest snapshot testing online. If there's an example you can point me to, I'll gladly try to repro the issue.

### Bug Report 
 
- __Package version(s)__:  "@uifabric/jest-serializer-merge-styles": "6.0.4" (latest)
- __Browser and OS versions__: Not relevant

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Possibly, as long as I can keep the scope of the fix to the keyframes issue I'm seeing (i.e. possibly not fixing other rules where this is breaking as well).
 
Requested priority: Normal. My team will need to disable `jest-serializer-merge-styles` for components that are using `keyframes`.
 
Products/sites affected: N/A
 
#### Describe the issue:

When using `jest-serializer-merge-styles`, there are certain CSS rules like `keyframes` (probably, haven't tested this with other rules) that cause the serializer to break. For example, with `keyframes`:

CSS:
```
@keyframes foo {
    from {opacity:0;}
    to {opacity:1;}
}
```

ruleSet in `jest-serializer-merge-styles`:
```
ruleSet
Array(2) ["keyframes", "from{opacity:0;}to{opacity:1;}"]
- length: 2
- __proto__: Array(0) [, …]
- 0: "keyframes"
- 1: "from{opacity:0;}to{opacity:1;}"
```

[So starting in L41 of the source](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/jest-serializer-merge-styles/src/index.ts#L41),  when the above is passed in, `insertedRules.split(';').sort` returns:

```
Array(3) ["from{opacity:0", "}", "}to{opacity:1"]
- length:3
- __proto__:Array(0) [, …]
- 0:"from{opacity:0"
- 1:"}"
- 2:"}to{opacity:1"
```

then *here's the actual bug/error that occurs:* in [line 53](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/jest-serializer-merge-styles/src/index.ts#L53), since one of the rules is "}", there is no `value` from [line 46](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/jest-serializer-merge-styles/src/index.ts#L46), hence I get the following stacktrace:

```
TypeError: Cannot read property 'split' of undefined
    at C:\repos\OfficeIdeas\node_modules\@uifabric\jest-serializer-merge-styles\src\index.ts:53:38
    at Array.forEach (<anonymous>)
    at _serializeRules (C:\repos\OfficeIdeas\node_modules\@uifabric\jest-serializer-merge-styles\src\index.ts:44:10)
    at Object.print (C:\repos\OfficeIdeas\node_modules\@uifabric\jest-serializer-merge-styles\src\index.ts:11:18)
    at printPlugin (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:194:108)
    at printer (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:228:12)
    at printObjectProperties (C:\repos\OfficeIdeas\node_modules\pretty-format\build\collections.js:140:21)
    at printComplexValue (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:187:169)
    at printer (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:236:10)
    at printListItems (C:\repos\OfficeIdeas\node_modules\pretty-format\build\collections.js:105:35)
... (more)
```

#### Actual behavior:

Doesn't serialize / serializer throws an exception.
 
#### Expected behavior:
 
Not sure how this should be serialized. For CSS like:

```
@keyframes foo {
    from {opacity:0;}
    to {opacity:1;}
}
```

Seems from what we're given the best we can serialize it to is something like:
```
@keyframes {
    from{opacity:0;}
    to{opacity:1;}
}
```
that is, we would just lose the animation name.
 
Again, I wouldn't mind implementing this specific fix (i.e. just for keyframes), but if you want something generic, then I wouldn't be able to provide that.

### PR DESCRIPTION
**Pull request by dzearing**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6149
- [X] Include a change request file using `$ npm run change`

#### Description of changes

Fixes a crash in the jest serializer when encountering keyframes registered.

### CODE REVIEW

**Comment by cliffkoh** [comment]
@kkjeer fyi

File: packages/jest-serializer-merge-styles/src/index.ts [hunk 1]
```diff
@@ -37,38 +37,42 @@ function _serializeRules(rules: string[], indent: (val: string) => string): stri
     const insertedRules = rules[i + 1];
```
Comment (cliffkoh) [inline packages/jest-serializer-merge-styles/src/index.ts]: It would be great to have some comments in this file, if not inline comments, then perhaps JSDoc for print() and test().

In particular for the function `test`, it would be great to have some inline comments describing the approach here.

**Comment by dzearing** [comment]
@kenotron may need help here. The "ts" and "jest" tasks typically run in parallel. In this case, I want them to run serially. Is there a clean way to do this, *just* for this project?

**Comment by kenotron** [comment]
The way to do this is probably add a new task (maybe called `build:merge-styles`) with its own flow within `scripts/just-task.js`, then modify the package.json to call `just.js build:merge-styles` or something

Otherwise, we would have to maintain `just-task.js` files inside each package.

**Comment by dzearing** [comment]
Just a quick update here, still working on the build issue.

File: packages/jest-serializer-merge-styles/src/index.ts (hunk 1 above)
Comment (dzearing) [reply packages/jest-serializer-merge-styles/src/index.ts]: Added!

**Comment by dzearing** [comment]
Thanks @kenotron! Done.

**Comment by dzearing** [comment]
Circular dependency. I'll weed it out.
