### PR TITLE
FocusTrapZone: Add new disabled prop and use in FocusTrapCallout

### LINKED ISSUE #8552: Modal's FocusTrapZone, with FocusTrapCallout child, not behaving as expected
Hi folks,

We have a `FocusTrapCallout` inside a `Modal`, similar to what's in the following codepen: https://codepen.io/namal-ms/pen/LvEOOb

As you can see, the `FocusTrapZone` of the `Modal` doesn't work as expected, and tab focus doesn't cycle through the couple buttons in the modal, and you can get to the background button.

Is this normal? The "Dialog nested in a Panel" example in the `FocusTrapZone` [documentation](https://developer.microsoft.com/en-us/fabric#/components/focustrapzone) leads me to believe it isn't expected, but I'm not sure.

When looking for workarounds, I noticed giving the `doNotLayer` prop to the `Callout` solves the issue. Could someone please explain the implications of setting `doNotLayer` to `true`? 🙂
I'm not well versed in the layering system of Fabric unfortunately.

Apologies if this isn't the right forum for this. If so, please let me know where I should send my questions (Microsoft employee, if that changes anything ^^)

## Codepen demonstrating the issue
https://codepen.io/namal-ms/pen/LvEOOb

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8552
- [x] Include a change request file using `$ npm run change`

#### Description of changes

#8552 highlighted a need to add a `disabled` prop to `FocusTrapZone` to allow `FocusTrapZone` to be present in the hierarchy in performant scenarios while being disabled. `FocusZone` already has a `disabled` prop so this also brings `FocusTrapZone` in parity.

Also modifies all `FocusTrapZone` examples to render all the time and make use of new `disabled` prop.

`FocusTrapCallout` was also modified to make use of this new prop and resolves #8552.

#### Focus areas to test

Add tests to test `disabled` scenarios.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8809)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx [hunk 1]
```diff
@@ -47,18 +47,22 @@ export class FocusTrapZone extends React.Component<IFocusTrapZoneProps, {}> impl
   public componentDidUpdate(prevProps: IFocusTrapZoneProps) {
     const prevForceFocusInsideTrap = prevProps.forceFocusInsideTrap !== undefined ? prevProps.forceFocusInsideTrap : true;
     const newForceFocusInsideTrap = this.props.forceFocusInsideTrap !== undefined ? this.props.forceFocusInsideTrap : true;
+    const prevDisabled = prevProps.disabled !== undefined ? prevProps.disabled : false;
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: Suggestion, deconstruct prev props and this.props so you don't have to keep doing this. and prevProps.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx [hunk 2]
```diff
@@ -47,18 +47,22 @@ export class FocusTrapZone extends React.Component<IFocusTrapZoneProps, {}> impl
...
+    const newDisabled = this.props.disabled !== undefined ? this.props.disabled : false;
 
-    if (!prevForceFocusInsideTrap && newForceFocusInsideTrap) {
+    if ((!prevForceFocusInsideTrap && newForceFocusInsideTrap) || (prevDisabled && !newDisabled)) {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: I feel like we should only bring focus into the zone if it currently has `forceFocusInsideTrap`. In the case where `forceFocusInsideTrap` is false we shouldn't move focus even if it had been disabled.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx (hunk 1 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: It's really only done on this line and consistent with other code. Generally if it's just one line, I don't deconstruct (since it's net less lines of code.)

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx (hunk 2 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: Good catch! Thanks.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx (hunk 1 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: (Also, I think `this` and `prevProps` context is important here.)

**Comment by JasonGore** [comment]
I wish I could request changes on my own PR. 😆 I have two bugs to fix before this should get merged.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx (hunk 2 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx]: Actually this gets called in `componentDidMount` regardless of `forceFocusInsideTrap`, and my testing has shown me why.  😆This will be needed to bring focus into FTZ once they are enabled, like they have just been mounted.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.test.tsx [hunk 3]
```diff
@@ -587,6 +600,16 @@ describe('FocusTrapZone', () => {
       expect(document.activeElement).toBe(buttonC);
     });
 
+    it('Does not focus on firstFocusableSelector on mount with disabled', async () => {
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.test.tsx]: Suggestion:

```suggestion
    it('Does not focus on firstFocusableSelector on mount while disabled', async () => {
```

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.types.ts [hunk 4]
```diff
@@ -22,6 +22,12 @@ export interface IFocusTrapZoneProps extends React.HTMLAttributes<HTMLDivElement
    */
   componentRef?: IRefObject<IFocusTrapZone>;
 
+  /**
+   * If set, the FocusTrapZone's focus trapping behavior will be disabled.
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.types.ts]: Suggestion based on the [wiki](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Commenting-conventions):

```suggestion
   * Disables the FocusTrapZone's focus trapping behavior if set.
```

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx [hunk 5]
```diff
@@ -16,51 +16,33 @@ export class FocusTrapZoneBoxClickExample extends React.Component<{}, IFocusTrap
...
-          componentRef={this._toggle}
-          checked={useTrapZone}
-          onChange={this._onFocusTrapZoneToggleChanged}
-          onText="On (toggle to exit)"
-          offText="Off"
-        />
-        <TextField label="Input inside trap zone" styles={{ root: { width: 300 } }} />
-        <Link href="https://bing.com">Hyperlink inside trap zone</Link>
-      </Stack>
+      <FocusTrapZone disabled={!useTrapZone} isClickableOutsideFocusTrap={true} forceFocusInsideTrap={false}>
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx]: Couldn't you just do `isClickableOutsideFocus` instead of `isClickableOutsideFocusTrap={true}`?

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx [hunk 6]
```diff
@@ -16,51 +16,33 @@ export class FocusTrapZoneBoxClickExample extends React.Component<{}, IFocusTrap
...
+        <Stack
+          horizontalAlign="start"
+          tokens={{ childrenGap: 15 }}
+          styles={{
+            root: { border: `2px dashed ${useTrapZone ? '#ababab' : 'transparent'}`, padding: 10 }
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx]: Suggestion: Can you move these styles/tokens to their own `consts`?

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Nested.Example.tsx [hunk 7]
```diff
@@ -86,6 +83,11 @@ export class FocusTrapZoneNestedExample extends React.Component<{}, IFocusTrapZo
     this.setState({ activeStates: { ...activeStates, [zoneNumber]: isActive } });
   };
 
+  // This randomize example is exposing a quirk in focus stack behavior.
+  // Since for the example components render from the bottom up, the most recently active item in the focusStack
+  // ends up being the highest parent, which is the reverse order focus trap zones would normally be put on the
+  // focusStack. That means children aren't capturing focus as one would normally expect when toggling the FTZ's
+  // individually. This would also be an issue if anyone ever rendered multiple FocusTrapZones simultaneously.
```
Comment (khmakoto) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Nested.Example.tsx]: Suggestion:

```suggestion
  // individually. This would also be an issue if anyone ever rendered multiple nested FocusTrapZones simultaneously.
```

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx (hunk 6 above)
Comment (ecraig12345) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx]: May be a difference of opinion, but I don't really see the need to use consts if the style is only used once

Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Click.Example.tsx]: I can see arguments for both sides. Examples should be self-contained, but it's good to show best practices as well. Props shouldn't be mutating unnecessarily either, and inline objects will mutate every time.

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx [hunk 8]
```diff
@@ -18,50 +19,42 @@ export class FocusTrapZoneBoxExample extends React.Component<{}, IFocusTrapZoneB
...
+
     return (
       <div>
-        {this.state.useTrapZone ? (
-          <FocusTrapZone>{this._internalContents()}</FocusTrapZone>
-        ) : (
-          // prettier-ignore
-          this._internalContents()
-        )}
+        <DefaultButton secondaryText="Focuses inside the FocusTrapZone" onClick={this._onButtonClickHandler} text="Sample Initiator" />
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx]: I removed the buttons in my recent PR to avoid having multiple UI elements which do the same thing--though in this case I can see how the toggle doesn't do *exactly* the same thing since it's inside the zone and the button isn't. Maybe in this case, it would be better to replace the toggle with a button that just disables the trap zone? (And the different border still makes it possible to see the enabled/disabled state even without the toggle.)

Also, I'm not sure about the text "Sample Initiator"--I'd prefer something more action-oriented like "Trap focus" (or remove the secondary text and just say "Focus inside FocusTrapZone")

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx [hunk 9]
```diff
@@ -20,51 +21,44 @@ export class FocusTrapZoneBoxCustomElementExample extends React.Component<{}, IF
...
+    const { useTrapZone } = this.state;
+
     return (
       <div>
-        {this.state.useTrapZone ? (
-          <FocusTrapZone firstFocusableSelector={_focusClassName}>{this._internalContents()}</FocusTrapZone>
-        ) : (
-          this._internalContents()
-        )}
+        <DefaultButton secondaryText="Focuses inside the FocusTrapZone" onClick={this._onButtonClickHandler} text="Focus Custom Element" />
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx]: Same comment here about maybe replacing the toggle with a second button

Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.FocusOnCustomElement.Example.tsx]: I think the Toggles keep them consistent with the other examples. The buttons are only needed in two cases to highlight features of the FocusTrapZone (returning focus to initiator and highlighting custom element.)

File: packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx (hunk 8 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx]: I also want to be clear this is demonstrating focus returning to initiator. How about this:

image

Comment (ecraig12345) [reply packages/office-ui-fabric-react/src/components/FocusTrapZone/examples/FocusTrapZone.Box.Example.tsx]: Maybe "Focus trap initiator"? Also might be good to have secondary text and/or separate explanatory text noting that if you enable the focus trap zone with this button (rather than the toggle), focus will return to the button when the zone is disabled.
