### PR TITLE
ComboBox: support non latin characters

### LINKED ISSUE #5834: Combobox doesn't autocomplete with non-english characters
### Bug Report

- __Package version(s)__: 6.39.2
- __Browser and OS versions__: latest Chrome, Windows Server 2016

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking) 

#### Describe the issue:

I have Combobox with options containing non-english (russian) words. 
`
<ComboBox
    allowFreeform={false}
    autoComplete="on"
    options={this.props.store!.budgetArticles.map(x => ({ key: x.Id, text: x.Title }))}
/>
`
By typing I can choose only options with english text. Russian text doesn't appears and options not selected.
#### Actual behavior:

Can't type russian characters and therefore select options with russian text

#### Expected behavior:

Can use any language for selection in combobox.

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #5834
- [ ] Include a change request file using `$ yarn change`

#### Description of changes

`String.fromCharCode(ev.which)` returns the latin character mapped to the given keycode, which means even with a Russian keyboard, you are always firing latin characters.

image

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11582)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -1849,14 +1849,6 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
           return;
         }
 
-        // If we are not allowing freeform and
-        // allowing autoComplete, handle the input here
-        // since we have marked the input as readonly
-        if (!allowFreeform && autoComplete === 'on') {
-          this._onInputChange(String.fromCharCode(ev.which));
```
Comment (jspurlin) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: >ev.which [](start = 50, length = 8)

why couldn't this be updated to `ev.key`?

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 2]
```diff
@@ -1896,6 +1888,15 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
       return;
     }
 
+    // If we are not allowing freeform and
+    // allowing autoComplete, handle the input here
+    // since we have marked the input as readonly
+
+    if (!allowFreeform && autoComplete === 'on') {
+      this._onInputChange(ev.key);
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: I'm not sure that ev.key can just be used like this. It looks like ev.key will map to things like `Enter`, `Escape` and other "named" keys like `F1`

See the console in this [codepen](https://codepen.io/slimemold/pen/zYxEPdX?editors=1111) for a demonstration, enter is the most obvious one. Also more info here on [mdn](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx [hunk 3]
```diff
@@ -231,6 +238,14 @@ describe('ComboBox', () => {
     expect(wrapper.find('input').props().value).toEqual('Foo');
   });
 
+  it('Can insert non latin text in uncontrolled case with autoComplete on and allowFreeform off', () => {
+    wrapper = mount(<ComboBox defaultSelectedKey="0" options={RUSSIAN_OPTIONS} autoComplete="on" allowFreeform={false} />);
+
+    wrapper.find('input').simulate('keyup', { key: 'п' });
+    wrapper.update();
+    expect(wrapper.find('input').props().value).toEqual('папа');
```
Comment (jdhuntington) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.test.tsx]: 👍

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx (hunk 2 above)
Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Here's the challenge. Take a look at these results using a Russian alphabet keyboard

image

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Also, the only valid keys when `!allowFreeform && autoComplete` are characters in the list items. Enter still enters, escape still escapes.

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: hmmm...for some reason i thought ev.key wasn't available on mouse down

Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: ok...reduced the change of this PR to simply using ev.key instead.

**Comment by micahgodbolt** [comment]
@jspurlin what do you feel about this change? Are there scenarios where you think this would not work?

**Comment by jspurlin** [comment]
@micahgodbolt, @joschect suggested that `event.key` needs to be investigated more before that's the solution we land on. Depending on what comes out from that investigation, assuming things look good, I'm good to sign off

**Comment by micahgodbolt** [comment]
@jspurlin is there any way to try this change out in the ribbon? want to make sure that "needs to be investigated" does not means "let the PR sit forever".

**Comment by jspurlin** [comment]
Sure, there's a way to try it out in the ribbon, but I think the concern was more from a technical standpoint if we could/should trust what `event.key` gives us in all cases (for example if a modifier key is pressed at the same time as a normal key comes to mind as a potentially interesting case). @joschect may have more concerns... If not, I'm good to sign off

**Comment by micahgodbolt** [comment]
This is only used in the autocomplete scenario, so we only add characters that match the string in the options. If user presses a random key, it won't match any option value, so won't have any effect.
