### PR TITLE
Dialog: Deprecate old props and move props into contentProps and modalProps

### LINKED ISSUE #1863: [Accessibility] Dialog cancel button missing aria-label
### Bug Report

- __Package version(s)__:  Latest
- __Browser and OS versions__: IE Edge, Windows 10 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)

#### Describe the issue:
The name of the cancel button at top of dialog in the "Inspect" tool is missing. 

#### Actual behavior:
Open the dialog on the Office fabric components in Edge browser.
Have the [Inspect tool](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318521(v=vs.85).aspx)  open.
Focus on the Cancel button at top of dialog. The name field is empty in the tool.

#### Expected behavior:

Name field should be populated as Cancel.

### If applicable, please provide a codepen repro:

accessibility - cancel button name

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1863
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Seems we originally had support for closeButtonAriaLabel (as it was mentioned a few times) but it was missing from props, and not passed from dialog into dialog content. 

In the process of adding the prop, I got tired of having to duplicate it in dialog and dialog content, so I deprecated all the original props are put the props into contentProps and modalProps that can be simply passed down to the child.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx [hunk 1]
```diff
@@ -79,21 +76,24 @@ export class Dialog extends BaseComponent<IDialogProps, IDialogState> {
         isClickableOutsideFocusTrap={ isClickableOutsideFocusTrap }
         isDarkOverlay={ isDarkOverlay }
         isOpen={ isOpen }
-        onDismiss={ onDismiss }
         onDismissed={ onDismissed }
         onLayerDidMount={ onLayerDidMount }
         responsiveMode={ responsiveMode }
+        { ...modalProps }
+        onDismiss={ onDismiss } // pull from contentProps.onDismiss once onDismiss is deprecated
```
Comment (MLoughry) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: I'm confused. Doesn't `onDismiss` come from `modalProps`?

File: packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx [hunk 2]
```diff
@@ -35,10 +35,11 @@ export class DialogContent extends BaseComponent<IDialogContentProps, IDialogCon
   public render() {
     let {
       showCloseButton,
-      closeButtonAriaLabel,
+      closeButtonAriaLabel = 'Close',
```
Comment (MLoughry) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx]: Is it standard practice to include default English strings?

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx]: I'm fine leaving this out if we want to keep it 100% language neutral, but user are obviously able to set it to their own string.

So I guess the question is what is worse, no label, or label in non-user language.

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx (hunk 1 above)
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: I wasn't quite sure how to tackle this one. I know that DialogContent.Props needs to accept onDismiss. Do we support both, and pass down either/or?

Comment (MLoughry) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: Why would DialogContent.Props need to have an onDismiss? It's not (necessarily) part of any sort of dismissable popup.

File: packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx (hunk 2 above)
Comment (MLoughry) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx]: If it's standard practice in Fabric now, that's fine; I haven't always kept up with the code base. I just don't want to do it some places and not others, leading to inconsistencies.

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx (hunk 1 above)
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: it's a callback that the content is able to call. I might have to leave it in and note that the prop is controlled by the component.

File: packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx (hunk 2 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx]: we should add it to defaultprops defined above instead of render() method that will keep all defaults at single place.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.tsx]: good point

File: packages/office-ui-fabric-react/src/components/Dialog/DialogContent.Props.ts [hunk 3]
```diff
@@ -0,0 +1,60 @@
+import * as React from 'react';
+import { DialogContent } from './DialogContent';
+import { IButtonProps } from '../Button/Button.Props';
+
+export interface IDialogContent {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.Props.ts]: Why is this here?

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts [hunk 4]
```diff
@@ -9,126 +10,103 @@ export interface IDialog {
...
    * A callback function for when the Dialog content is mounted on the overlay layer
+   * @deprecated Pass through via dialogModalProps instead
    */
   onLayerDidMount?: () => void;
 
   /**
-   * Deprecated at 0.81.2, use 'onLayerDidMount' instead.
-   * @deprecated
-   */
-  onLayerMounted?: () => void;
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: Even though this is deprecated, doesn't removing it constitute a breaking change?

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: good point. though, i'm sure we aren't going to major bump every time we remove a deprecated prop

File: packages/office-ui-fabric-react/src/components/Dialog/DialogContent.Props.ts (hunk 3 above)
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/DialogContent.Props.ts]: yeah true...i guess that idea was to connect it to a componentRef, but never did.

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts [hunk 5]
```diff
@@ -9,126 +10,103 @@ export interface IDialog {
...
-   * Optional callback to access the IDialog interface. Use this instead of ref for accessing
-   * the public methods and properties of the component.
-   */
-  componentRef?: (component: IDialog) => void;
+  onDismiss?: (ev?: React.MouseEvent<HTMLButtonElement>) => any;
 
   /**
   * Whether the dialog is displayed.
   * @default false
+  * @deprecated Pass through via dialogModalProps instead
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: I'm confused. You added `modalProps` but all of your comments say `dialogModalProps`.

The `isOpen` prop is rather important, and also poorly done.

The default behavior of a dialog, without props, is that it's *visible*, not hidden. Otherwise, a customer who tries out Dialog is very confused when they don't provide isOpen=true.

I would really like isOpen to be deprecated, in favor of something like `hidden`, which has a default of `false`, but by the comments alone, I'm really confused.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: updated. now i'm just trying to work out some weird failing tests.

**Comment by micahgodbolt** [comment]
Ok, good. It's passing now. Was having some local failures.

**Comment by micahgodbolt** [comment]
@dzearing I added a 'hidden' attribute, defaulting to false, and will use that value if isOpen is not passed in. Also went back to dialogContentProps for consistency.

**Comment by micahgodbolt** [comment]
Anything holding this back before I merge? Is this the pattern we want to use when creating composite components?

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx [hunk 6]
```diff
@@ -51,49 +56,49 @@ export class Dialog extends BaseComponent<IDialogProps, IDialogState> {
...
       title,
       type,
       contentClassName,
-      topButtonsProps
+      topButtonsProps,
+      dialogContentProps,
+      modalProps,
+      containerClassName,
+      hidden
     } = this.props;
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: please add warnings on deprecations

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx [hunk 7]
```diff
@@ -51,49 +56,49 @@ export class Dialog extends BaseComponent<IDialogProps, IDialogState> {
...
         elementToFocusOnDismiss={ elementToFocusOnDismiss }
         firstFocusableSelector={ firstFocusableSelector }
         forceFocusInsideTrap={ forceFocusInsideTrap }
         ignoreExternalFocusing={ ignoreExternalFocusing }
         isBlocking={ isBlocking }
         isClickableOutsideFocusTrap={ isClickableOutsideFocusTrap }
         isDarkOverlay={ isDarkOverlay }
-        isOpen={ isOpen }
-        onDismiss={ onDismiss }
+        isOpen={ isOpen ? isOpen : !hidden }
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: isOpen !== undefined

Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: this is buggy because if isOpen is false and hidden is undefined (which will be the case out of the box0, it will default to true.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: oh, another issue is that isOpen is set to false by default (or was in the past and should probably should continue to be). So I really should be checking to see if user specified hidden or not, and use that prop.

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx (hunk 6 above)
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx]: Done

**Comment by micahgodbolt** [comment]
@dzearing resolved your concerns, updated tests, lights are green, trap is clean.

**Comment by micahgodbolt** [comment]
@dzearing happy with these changes?

File: packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts (hunk 4 above)
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: Sorry why are you removing it? 

The whole semver principle is that minor and patch bumps do not break partners. Removing a deprecated prop breaks. We need to lock to a branching policy that accommodates this without immediately publishing a breaking change as a minor or patch bump. 

For example, we could make a 4.0 branch, which accumulates 4.0 updates, and make master the "next" branch. The policy would be that no major changes go into any place besides master. Then I'd have no problem accumulating a bunch of major breaks in master. When we publish, we hook up a specific branch to add "latest" tag, and master always has "beta" tag.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: I'm fine with this going out with a major release. I guess I was trying to do some cleanup of deprecated props that have been around for multiple major releases. In some cases, the removal made the new code I wrote easier to manage (as there wasn't the additional prop to support). 

I'm fine either way. If we want to put this into a 4.0 branch, or I can return the props and make sure to support them.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: I'll return any removed deprecated props...or at least see how feasible it is.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dialog/Dialog.Props.ts]: Ok, so funny story.  onLayerMounted was pulled in via `let { onLayerMounted } = this.props;` but it was never actually used in the code :)

Regardless, I put it back so that the signature didn't change, even if the prop was already removed from the component.

**Comment by micahgodbolt** [comment]
Ok, i've resolve the merge conflicts and spoken with David about this. Going to merge this in once the tests  pass.
