### PR TITLE
Modifying the combobox dropdown alignment to have the scrollbar align with the target element

### LINKED ISSUE #3400: combobox and dropdown alignment issue
### Bug Report

- __Package version(s)__: (5.21.2)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:
Dropdown control and combobox control use different mechanisms to set the width for their dropdown.
Dropdown renders a callout setting the calloutWidth by getting the target reference 
clientWdith calloutWidth={ dropdownWidth || this._dropDown.clientWidth }

Combobox is getting the width set using the similar mechanism where it's getting width from this._comboBoxWrapper.clientWidth - 2. However, this width is not set at the callout component level, it's setting inside the optionsContainerWrapper, which cause the scrollbar overflow the whole width.

#### Actual behavior:
Here's the codepen example https://codepen.io/caseyyu2/pen/BmZRQz
You can see the combobox's scrollbar position aligned differently than dropdown
#### Expected behavior:
Combobox position alignment should be the same as dropdown

### If applicable, please provide a codepen repro:
https://codepen.io/caseyyu2/pen/BmZRQz

### PR DESCRIPTION
**Pull request by Caseyyu2**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #3400 

#### Description of changes
Dropdown control and combobox control use different mechanisms to set the width for their dropdown.
Dropdown renders a callout setting the calloutWidth by getting the target reference
clientWdith calloutWidth={ dropdownWidth || this._dropDown.clientWidth }

Combobox is getting the width set using the similar mechanism where it's getting width from this._comboBoxWrapper.clientWidth - 2. However, this width is not set at the callout component level, it's setting inside the optionsContainerWrapper, which cause the scrollbar overflow the whole width.

So I updated the combobox dropdown to be the same as the dropdown mechanism

#### Focus areas to test

Click on combobox
Expected
the scrollbar should be aligned at the end of the target element.

Before alignment fix (it's between combobox and dropdown)
combobox dropdown

After fix combobox
combobox fixed1

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -25,6 +25,9 @@ import {
   getCaretDownButtonStyles
 } from './ComboBox.styles';
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Needs a change file. Can you please run `npm run change -- -b upstream/master` from the root?

**Comment by christiango** [comment]
Please update the title of this PR to something more descriptive

**Comment by christiango** [comment]
Can you provide some more details on the scenario here to help reviewers? Perhaps include some screenshots of the before and after?

**Comment by Caseyyu2** [comment]
@christiango I updated title, and the PR with more details. Also attached the gifs for the combobox behavior before vs. after fix.

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (Caseyyu2) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: @dzearing , change file created, let me know if there's anything else :)

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts [hunk 2]
```diff
@@ -209,6 +209,12 @@ export interface IComboBoxStyles {
    * Styles for a divider in the options.
    */
   divider: IStyle;
+
+  /**
+  * Custom width for dropdown. If value is 0, width of the input field is used.
+  * @default 0
+  */
+  dropdownWidth?: number;
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts]: This prop should probably be moved to IComboBoxProps. The styles interface is for IStyle type props (IStyle group css property/value pairs).  @dzearing  agree?

Comment (Caseyyu2) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts]: Makes sense. I moved the prop into combobox.props. Dropdown did the same way

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 3]
```diff
@@ -812,6 +814,7 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
         target={ this._comboBoxWrapper }
         onDismiss={ this._onDismiss }
         setInitialFocus={ false }
+        calloutWidth={ dropdownWidth || this._comboBoxWrapper.clientWidth + 2 }
       >
         <div className={ this._classNames.optionsContainerWrapper } ref={ this._resolveRef('_comboBoxMenu') }>
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: There's a bit of cleanup to do here with the optionsContainerWrapper, but we'll be doing a styling sweep in the near future and we'll be able to clean it up then. So don't worry about it. This is the correct way to set the callout width.

**Comment by micahgodbolt** [comment]
Hmm, looking at gifs, I'm wondering if we are doing something different in combobox vs dropdown to property support the scrollbar. I have no problem allowing for custom width anyway, but we dont' want to force people to set a width just to fix this bug.

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 4]
```diff
@@ -812,6 +814,7 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
         target={ this._comboBoxWrapper }
         onDismiss={ this._onDismiss }
         setInitialFocus={ false }
+        calloutWidth={ dropdownWidth || this._comboBoxWrapper.clientWidth + 2 }
```
Comment (christiango) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: The problem with this approach is that it will introduce another reflow from the measurement to get the clientWidth. Ideally, we'd only do a measurement once (inside the callout component) Where does the +2 come from?

Comment (christiango) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Though I guess there was already a reflow from line 255

Comment (Caseyyu2) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: @christiango, _comboBoxWrapper wil have its reference set after combobox loads. Without clicking the dropdown,  the callout is not rendered. Then when user click on the dropdown button, callout will try to render, and at this point, the ref has already been set, and it'll flow once to callout. Am I missing anything? The 2px is the reverse engineer on the setWidth setWidth = isOpen ? (this._comboBoxWrapper.clientWidth - 2) + 'px' : undefined; Otherwise, the width wouldn't cover the whole width of the target element.

Comment (christiango) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: So callout rendereing is already pretty slow. Since the callout is using _comboBoxWrapper as a target, it's bounds will be computed by the callout (forcing a reflow). The call to this_comboBoxWrapper.clientWidth seems like it would add a second reflow and make the frame for opening a callout even longer. This could be verified by looking at a perf trace in the browser dev tools before and after this change.

Comment (Caseyyu2) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Thanks for pointing out the reflow @christiango , I took a look at the calloutContent, which is the piece that has calculation and cause reflow. The way they are using calloutWidth is passing in through mergeStyles and use it as className on the container wrapping up the popup. 
 className={
            mergeStyles(
              'ms-Callout',
              styles.root,
              className,
              directionalClassName,
              !!calloutWidth && { width: calloutWidth }
            ) }
So I don't think by passing that prop in, it'll impacting the existing reflow paths. I also recorded the render time and methods of calloutContent
Render time without passing calloutWidth
image
Render time with passing calloutWidth
image

Comment (Caseyyu2) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Thanks for pointing out the reflow @christiango , I took a look at the calloutContent, which is the piece that has calculation and cause reflow. The way they are using calloutWidth is passing in through mergeStyles and use it as className on the container wrapping up the popup.
className={
mergeStyles(
'ms-Callout',
styles.root,
className,
directionalClassName,
!!calloutWidth && { width: calloutWidth }
) }
So I don't think by passing that prop in, it'll impacting the existing reflow paths. I also recorded the render time and methods of calloutContent
Render time without passing calloutWidth and path
image
Render time with passing calloutWidth and path
image

Comment (christiango) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Thanks for looking into it! I would expect the code you are adding to add a new reflow higher up in the callstack since I expect the the _comboBoxWrapper.clientWidth call would take place before the callout content gets rendered.
