### PR TITLE
DatePicker: Add Reset Function

### LINKED ISSUE #4599: DatePicker control state should be resetable
### Bug Report
- __Package version(s)__: 5.79.1(and master also)
#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? (Yes)
Requested priority: (Normal) 
#### Actual behavior:

- Create empty DatePicker control
- User enters an invalid value (say "aaa") and then focus'es away
- DatePicker displays an error message that the value is invalid & updates its state specifying that the error message should display. 
- Now user presses a separate "Reset fields" button that is suppose to reset all fields. The press causes the Form to remove the existing DatePicker and create a new empty one. However the error remains on the DatePicker. Even if re-rendering the component React thinks that it's the same component and preserves its state. 
The work-around is to delete the DatePicker, render the form, then add an empty DatePicker which will now have a blank state. Of course this will cause flickering so It's not an actual work-around.

#### Expected behavior:
There should be a way to reset the DatePicker control error status.

@lorejoh12 @sathi23

### PR DESCRIPTION
**Pull request by abettadapur**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4599 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
 * Create a reset function
* The reset function resets the state to the default
(give an overview)

#### Focus areas to test

(optional)

### CODE REVIEW

**Comment by abettadapur** [comment]
@lorejoh12 Could I get a review on this guy?

File: packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx [hunk 1]
```diff
@@ -281,6 +273,10 @@ export class DatePicker extends BaseComponent<IDatePickerProps, IDatePickerState
     }
   }
 
+  public reset(): void {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: can you add `implements IDatePicker` to ensure we actually implment it? :)

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.tsx]: fixed for you :)
