### PR TITLE
ContextualMenu has aria-labelledBy referencing element not in DOM

### LINKED ISSUE #4778: Invalid aria-labelledby for contexualmenu container
### Bug Report

- __Package version(s)__: (5.66.0)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: ( Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

For implemention of 
IconButton +  Contexualmenu

showing contexualmenu on click of button ( iconbutton/defaultbutton)
aria-labelledby attribute is being added to ContexualMenu Container div, and if there is no text associate to the button  then accessibility test  failing with Invalid ARIA Attribute value: aria-labelledby

you can also verify this here - https://developer.microsoft.com/en-us/fabric#/components/overflowset 

#### Actual behavior:
aria-labelled by of contexualmenu is referring to the id which not present in the DOM

#### Expected behavior:

if the text is not given for the button , then aria-labelled by should be undefined

### PR DESCRIPTION
**Pull request by rpsenski**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #4778
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

1. Factored out logic used to determine if there's text on the button that will launch the context menu
2. Used that logic to control whether an element with the text is created AND used it to determine if we need aria-labelledBy on the ContextMenu itself (achieved through labelElementId property in menuProps)
3. Also check that ariaLabel AND that labelElementId aren't explicitly set on menuProps before choosing to inherit from the button text

#### Focus areas to test

Easily tested using OverflowSet:

1. Given when there is no text on the button and the button is clicked, then there should be no aria-labelledBy on the ContextualMenu produced by clicking the button
2. Given when _onRenderOverflowButton callback prop sets ariaLabel on the menuProps it provides and the button does or doesn't have text, then the ContextualMenu should have an aria-label but no aria-labelledBy.
3. Given when _onRenderOverflowButton callback prop sets labelElementId on the menuProps to the id of some control A, and the button does or doesn't have text, then the ContextualMenu should have an aria-labelledBy equal to the id of control A, not the id of the text element on the button (if text was provided)

#### Reviewers:
@joschect 
@jspurlin

### CODE REVIEW

**Comment by JasonGore** [comment]
Hmm, this seems like a good candidate for a test with and without text to verify prop does and doesn't appear as expected

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -311,14 +311,12 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
...
     const {
-      text,
-      children,
       secondaryText = this.props.description,
       onRenderText = this._onRenderText,
       onRenderDescription = this._onRenderDescription
     } = this.props;
 
-    if (text || typeof (children) === 'string' || secondaryText) {
+    if (this._hasText() || secondaryText) {
```
Comment (rpsenski) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Wanted to point out that the refactor actually made this a stricter check. Before, if text was null and typeof (children) === 'string' evaluated to true, the if was true. Now, text must be undefined for typeof (children) check to make the if truthy. I think this was the original intention because falling back to string children for text is supposed to be for backward compatibility and assumes text property is not present, but it's still a change that I want scrutinized by reviewers.

**Comment by rpsenski** [comment]
Iteration 4

---
In reply to: [391440443](https://github.com/OfficeDev/office-ui-fabric-react/pull/4963#issuecomment-391440443) [](ancestors = 391440443)

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx (hunk 1 above)
Comment (jspurlin) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: While I agree that this seems safe, let's not change the logic because it may have a ripple effect for some consumers. Feel free to log a bug and list it in a comment inside of _hasText so that it can be addressed later

Comment (rpsenski) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Reverted to reduce risk

---
In reply to: [190656224](https://github.com/OfficeDev/office-ui-fabric-react/pull/4963#discussion_r190656224) [](ancestors = 190656224)
