### PR TITLE
Users/mipatera/details list count groups

### LINKED ISSUE #3815: DetailLists not considering GroupedLists for aria-rowcount
### Bug Report

- __Package version(s)__: 5.39.1001

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Low

#### Describe the issue:

When DetailList assigns its aria-rowcount value, it's just counting the raw number of items being passed in. However, for grouped data, the actual number created can (and often does) differ.

#### Actual behavior:

aria-rowcount should reflect the final number of rows it creates, accounting for GroupedLists in particular.

#### Expected behavior:

aria-rowcount only reflects the count of items passed in (plus the header, when applicable).

See [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/d2edbbc6c069f8cb8d2936a8d982aa50be0613e1/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx), line 310. That's the only time the aria-rowcount value is set.

### PR DESCRIPTION
**Pull request by paterasMSFT**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3815
- [x] Include a change request file using `$ npm run change`

#### Description of changes

DetailsList's aria-rowcount now considers groups as rows.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx [hunk 1]
```diff
@@ -314,7 +314,7 @@ export class DetailsList extends BaseComponent<IDetailsListProps, IDetailsListSt
         <div
           role='grid'
           aria-label={ ariaLabelForGrid }
-          aria-rowcount={ (isHeaderVisible ? 1 : 0) + (items ? items.length : 0) }
+          aria-rowcount={ (isHeaderVisible ? 1 : 0) + (groups ? groups.length : 0) + (items ? items.length : 0) }
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx]: what about nested groups?

File: packages/office-ui-fabric-react/src/utilities/groupedList/GroupedListUtility.test.tsx [hunk 2]
```diff
@@ -0,0 +1,58 @@
+import { IGroup } from '../../components/GroupedList';
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/utilities/groupedList/GroupedListUtility.test.tsx]: I think you should import from `/GroupedList.types` or `/index`

File: packages/office-ui-fabric-react/src/utilities/groupedList/GroupedListUtility.tsx [hunk 3]
```diff
@@ -0,0 +1,22 @@
+import { IGroup } from '../../components/GroupedList';
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/utilities/groupedList/GroupedListUtility.tsx]: I think you should import from `/GroupedList.types` or `/index`

File: packages/office-ui-fabric-react/src/utilities/groupedList/GroupedListUtility.tsx [hunk 4]
```diff
@@ -0,0 +1,22 @@
+import { IGroup } from '../../components/GroupedList';
+
+export const GetGroupCount = (groups: IGroup[] | undefined): number => {
```
Comment (cschleiden) [inline packages/office-ui-fabric-react/src/utilities/groupedList/GroupedListUtility.tsx]: Can you add jsdoc comments?
