### PR TITLE
Fix focus zone virtual parent focus restoration. Fixes #8366.

### LINKED ISSUE #8366: FocusZone doesn't restore focus correctly with virtual parents
### Environment Information 
 
- __Package version(s)__: 6.146.1

#### Actual behavior:
 
Start with FocusZone that contains a few buttons... If one of them opens a ContextualMenu, and it is closed after moving focus to it, the focus is not restored. This is because FocusZone keeps track of the `_lastIndexPath` where the focus should be restored. It saves this path if it detects that an elementContains the focusedElement. This is true for ContextualMenu because it is a valid parent (virtual) in React, but not in DOM. The result path is saved but since the element was never the actual DOM parent this path is not valid and restores the focus incorrectly.

### PR DESCRIPTION
**Pull request by Dalimil**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8366
- [x] Include a change request file using `$ npm run change`

#### Description of changes
Fixes the scenario when a control inside of a  focus zone has a contextual menu and the focus is not restored correctly when you close the menu.

This is because FocusZone keeps track of the _lastIndexPath where the focus should be restored. It saves this path if it detects that an elementContains the focusedElement. This is true for ContextualMenu because it is a valid parent (virtual) in React, but not in DOM. The result path is saved but since the element was never the actual DOM parent this path is not valid and restores the focus incorrectly.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8368)

### CODE REVIEW

**Comment by JasonGore** [comment]
Could you provide a CodePen (or similar) example here or in the issue? I think it would be good to codify the example in case there are regressions in the future. 

Are there any cases where we would want to focus an element through a virtual parent? What about nested FocusZones? Any other scenarios we can think of? (Might be good to add this to the CodePen to play with.)

Is it possible to add a unit test that fails before your change and passes after then change to help guard against regression here?

Thanks!

**Comment by chang47** [comment]
@jspurlin FYI

**Comment by Dalimil** [comment]
@JasonGore I commented on the original issue here: https://github.com/OfficeDev/office-ui-fabric-react/issues/8366

File: packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx [hunk 1]
```diff
@@ -268,7 +268,7 @@ export class FocusZone extends React.Component<IFocusZoneProps, {}> implements I
 
       // Only update the index path if we are not parked on the root.
       if (focusedElement !== root) {
-        const shouldRestoreFocus = elementContains(root, focusedElement);
+        const shouldRestoreFocus = elementContains(root, focusedElement, false);
```
Comment (jspurlin) [inline packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx]: >elementContains [](start = 35, length = 15)

Looking at your reduced repro, it look like focus is going to the the iframe (window ) when the menu is opened which seems like the incorrect part. Note this only happens when the menu is launched via mouse, it correectly puts focus on the first item when opening via keyboard. When opening via mouse it should put focus on the whole menu

**Comment by Dalimil** [comment]
So to summarize, this is not even something you could unit test, because the focus is always restored correctly - eventually. There is a few ms delay before this happens however, and in some specific scenarios this could cause visual effect where the focus jumps to a different place during those few ms, before it is restored correctly. This is a tiny bug. I might not be able to convince you that this is an issue that needs attention, because we can fix it in our app by forcing the focus to move to the right place immediately. But fundamentally, this is an issue inside the Fabric library.

Imagine you open a context menu inside a focus zone. Then you destroy/close the context menu and focus zone is updated. Two different components are trying to restore focus:
1. ContextualMenu - the menu stored it's parent component, and will try to restore focus there. Unfortunately, this is done async, with setTimeout(=> , 0). Nobody from the Fabric team I spoke to knows exactly why this is needed. It's this line:
https://github.com/OfficeDev/office-ui-fabric-react/blob/f476aa80a93b0a69dbe5066a858840e6fdfb0aca/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L173

2. The outer FocusZone - it called `componentDidUpdate()` and because after destroying the ContextualMenu and not restoring the focus immediately, the focus is now at document body. Which means the FocusZone will also try to restore the focus. It's this line:
https://github.com/OfficeDev/office-ui-fabric-react/blob/12513bd032a8ce7a6ef1e0257bd2ae99a0a00849/packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx#L147

Now if we were restoring the focus twice to the same place that would be fine. But FocusZone is trying to restore it to the wrong place in this case. It's keeping track of the DOM indexes it has to follow to reach the element that should be focused in `this._lastIndexPath` variable. However, as I tried to demonstrate with my CodePen, it often gets the indexes wrong, because even though the opened ContextualMenu is a child of the FocusZone in React's virtual DOM, it's not a child in the actual DOM (contextual menu is rendered outside the tree). So that's why the CodePen example had one of the `this._lastIndexPath` indexes set to `-1` - because it was traversing the DOM tree up and could never find the right element. Having invalid `this._lastIndexPath` indexes will cause the FocusZone focus restoration mess up (either not finding the element at all, or accidentally moving it to the wrong place in the DOM tree)
@KevinTCoughlin @JasonGore @jspurlin 
I recently mentioned the setTimeout issue in ContextualMenu to @dzearing too

File: packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx (hunk 1 above)
Comment (Dalimil) [reply packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx]: So the issue I'm trying to address is when the menu is destroyed.
