### PR TITLE
Calendar (bug fix): fixing scrollbar issue that occurs with Go to today button

### LINKED ISSUE #3255: DatePicker menu shouldn't have scrollbar
### Bug Report

- __Package version(s)__: https://developer.microsoft.com/en-us/fabric#/components/datepicker
- __Browser and OS versions__: Chrome Mac

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Calendar OWA

#### Describe the issue:

The window showing menu options for the date picker shows a scrollbar. This looks unprofessional. It may have something to do with the second window that appears. But still to the user this isn't good.

image

image

#### Actual behavior:

Scrollbar shows

#### Expected behavior:

No scrollbar

### PR DESCRIPTION
**Pull request by kellygorr**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3255
- [x] Include a change request file using `$ npm run change`

#### Description of changes

This issue occurs in the datepicker and calendar when the "go to today" button is used when the day picker and month picker calendars are overlayed.

Issue:

Issue In Date Picker:

Issue In IE:

Update:

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx [hunk 1]
```diff
@@ -123,6 +123,7 @@ export class Calendar extends BaseComponent<ICalendarProps, ICalendarState> impl
     let { selectedDate, navigatedDate, isMonthPickerVisible, isDayPickerVisible } = this.state;
     let onHeaderSelect = showMonthPickerAsOverlay ? this._onHeaderSelect : undefined;
     let monthPickerOnly = !showMonthPickerAsOverlay && !isDayPickerVisible;
+    let overlayedWithButton = showMonthPickerAsOverlay && showGoToToday;
```
Comment (johannao76) [inline packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: > let overlayedWithButton = showMonthPickerAsOverlay && showGoToToday; [](start = 3, length = 69)

Why does the style have to be different for this specific case? What if we wanted to not have month picker overlay but wanted the today button? We would still want the style to look good but it looks like we would still get the old behavior in that case?

Is this something that can be fixed in the date picker by setting the size of the container properly?

Comment (johannao76) [reply packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx]: Per comments offline, let's check this in to fix the immediate problem, would be good to come up with a better solution to avoid these one-off checks

---
In reply to: [157331043](https://github.com/OfficeDev/office-ui-fabric-react/pull/3531#discussion_r157331043) [](ancestors = 157331043)
