### PR TITLE
Ios panel footer

### LINKED ISSUE #5423: Panel: Footer bottom is cut on Safari / iOS
### Bug Report 
 
- __Package version(s)__: v6.25.0
- __Browser and OS versions__: Safari / iOS
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but I need guidance on the ideal solution.
 
Requested priority: Normal
 
Products/sites affected: All
 
#### Describe the issue:

On Safari / iOS, the area of the layer is bigger than the visible browser area, which renders the bottom of the Panel cut. Check out the [Panel - Footer](https://developer.microsoft.com/en-us/fabric#/components/panel) example on OF official website using an iPad Pro:

img_0004 3

In Safari, the viewport size (`height: 100vh`) is bigger than the actual visible part of the page. [This seems to be a problem ever since 2015. ](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html)

### PR DESCRIPTION
**Pull request by kkjeer**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5423 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

On iOS devices, set the height of the scrollableContent Panel element to `window.innerHeight`. This prevents the panel content from growing past the iOS bottom navigation bar, which prevents the footer content from being hidden.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/utilities/src/mobileDetector.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export const isIOS = (): boolean => {
```
Comment (cliffkoh) [inline packages/utilities/src/mobileDetector.ts]: unit test for this please, and js doc (even more impt than unit test)

**Comment by Jahnp** [comment]
@kkjeer , would you mind waiting to merge this until #5823 is merged? I'm working on wrapping up the conversion with your most recent changes from #5804 and should have it ready today.

File: packages/utilities/src/mobileDetector.test.ts [hunk 2]
```diff
@@ -0,0 +1,104 @@
+import { isIOS } from './mobileDetector';
+
+const mockNavigator = (agent: string): void => {
```
Comment (cliffkoh) [inline packages/utilities/src/mobileDetector.test.ts]: This is awesome :+1:
