### PR TITLE
CommandBar: Allow disabled anchor and text items

### LINKED ISSUE #3647: CommandBar: IContextualMenuItem is not disabled when href is used
### Bug Report

- __Package version(s)__: Lastest
- __Browser and OS versions__:  Chrome (latest), Edge,...

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
Requested priority: Normal

#### Describe the issue:
When you set the disabled property on a IContextualMenuItem and it uses the href property instead of the onClick, the item is not disabled, being clickable.

#### Expected behavior:

Every item with the disabled property set should be disabled and should not be clickable.

### If applicable, please provide a codepen repro:

https://codepen.io/Intnovaction/pen/ypbvyr

### PR DESCRIPTION
**Pull request by lambertwang**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3647
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Adding the disabled property to anchor and text commands in the command bar will disable them.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx [hunk 1]
```diff
@@ -211,12 +211,13 @@ export class CommandBar extends BaseComponent<ICommandBarProps, ICommandBarState
         </button>
       );
     } else if (item.href) {
+      // Allow the disabled property on anchor elements for commandbar
       command = (
         <a
-          { ...getNativeProps(item, anchorProperties) }
+          { ...getNativeProps(item, anchorProperties.concat(['disabled'])) }
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx]: if we want disabled to be a valid native prop, which it seems like it should be, then it should get added to properties.ts

**Comment by micahgodbolt** [comment]
CommandBar is going to be replaced in 6.0 (releasing this month) with the version currently in experiments. I'm fine pulling this in now, but we need to make sure the version in experiments supports this feature as well.

I believe it should be okay because we're using actual Button components for each link.

File: packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx (hunk 1 above)
Comment (lambertwang) [reply packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx]: I'm not sure that we want the disabled attribute to be added to anchor and div elements. The disabled attribute is not a native HTML attribute for those tags. I was intending for the attribute to be valid for command bar items only. I've added a comment to clarify.  
https://www.w3schools.com/tags/att_disabled.asp
