### PR TITLE
HoverCard: Adds a new card type plus some refactor

### LINKED ISSUE #6197: HoverCard's cardHeight props aren't typed broadly enough
### Reproduction in CodeSandbox (CodePen was giving me issues at the time):
[Edit Fabric-React HoverCard compact height type](https://codesandbox.io/s/mzqlyj3k6x)
### Bug Report 
 
 
- __Package version(s)__: 6.61.2
- __Browser and OS versions__: non-relevant
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? **Yes**
 
Requested priority: **Low**
 
 
#### Describe the issue:
 
The `IExpandingCardProps` has a property `compactCardHeight`, which is of type `number`, even though that in runtime it accepts anything that `IStyle['height']` accepts.
To word this differently - the type of `IExpandingCardProps[compactCardHeight]` (and `IExpandingCardProps[expandedCardHeight]`) should be `IStyle['height']` (which is really `string | number` in this case, but also contains other values that are acceptable).
This causes the height of the card to have a fixed height, and doesn't allow a dynamic one based on the height of the inner component.

This is also true for the width (fixed width), but the issues are unrelated, technically.

 
#### Actual behavior:
Card width can only be typed as a `number`
 

 
#### Expected behavior:
Card width can be typed as a `string | number`

### PR DESCRIPTION
**Pull request by Vitalius1**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #6197
- [X] Include a change request file using `$ npm run change`

#### Description of changes

1. Adds a new type of card which responds to content's size.
2. Adds an example of implementing the new type.
3. Refactors some mergeStyle API to bring it to the current standard.
4. Extract some common code used between 2 cards into a separate functional component and reorganize a little the folder structure.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/6411)

screen shot 2018-09-18 at 9 31 31 pm
screen shot 2018-09-18 at 9 31 55 pm

### CODE REVIEW

**Comment by Vitalius1** [comment]
Should also help the workarounds used in #6266 and #6247. @v-kanuli you might wanna use this instead of the hack in this PRs.

**Comment by micahgodbolt** [comment]
Can you add some screenshots of the new card?

**Comment by nulikartik** [comment]
> Should also help the workarounds used in #6266 and #6247. @v-kanuli you might wanna use this instead of the hack in this PRs.
Thanks for letting me know. Will update this after Ignite.

**Comment by Vitalius1** [comment]
@JasonGore would really value your feedback on this inheritance pattern I used in here in order to reuse bits of code.

File: packages/office-ui-fabric-react/src/components/HoverCard/Card.tsx [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+import { Callout } from '../../Callout';
+import { DirectionalHint } from '../../common/DirectionalHint';
+import { FocusTrapZone } from '../../FocusTrapZone';
+import { ICardProps, ICardStyles, ICardStyleProps } from './Card.types';
+
+/**
+ * Basic class for all types of hover cards providing the callout in which to render the content.
+ */
+export abstract class Card<
+  T,
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/HoverCard/Card.tsx]: What does T here signify? I don't think this name is descriptive enough...

File: packages/office-ui-fabric-react/src/components/HoverCard/Card.tsx [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+  };
+
+  protected _finalHeight: number;
+  protected _content: JSX.Element;
+  protected _classNames: { [key in keyof TStyles]: string };
+  protected _directionalHintFixed: boolean;
+
+  constructor(props: TProps) {
+    super(props);
+  }
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/HoverCard/Card.tsx]: Unnecessary constructor

File: packages/office-ui-fabric-react/src/components/HoverCard/Card.types.ts [hunk 3]
```diff
@@ -0,0 +1,98 @@
+import * as React from 'react';
+
+import { DirectionalHint } from '../../common/DirectionalHint';
+import { IRefObject, IStyleFunctionOrObject } from '../../Utilities';
+import { IStyle, ITheme } from '../../Styling';
+
+/**
+ * Card common props.
+ */
+export interface ICardProps<T, TStyles, TStyleProps> extends React.HTMLAttributes<HTMLDivElement> {
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/HoverCard/Card.types.ts]: Similar to other comment I don't think it's obvious what T should be as a type if I use this interface

**Comment by Vitalius1** [comment]
@atneik now ready for a review.
@JasonGore Addressed your feedback and switched to a compositional approach.

File: packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.doc.tsx [hunk 4]
```diff
@@ -1,39 +1,45 @@
...
       view: <HoverCardBasicExample />
     },
     {
-      title: 'Example 2: HoverCard using Target, DirectionalHint and custom HotKey',
+      title: 'Example 2: Expanding HoverCard using Target, DirectionalHint and custom HotKey',
       code: HoverCardTargetExampleCode,
       view: <HoverCardTargetExample />
+    },
+    {
+      title: 'Example 3: Basic HoverCard wrapping an element',
```
Comment (atneik) [inline packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.doc.tsx]: Plain instead of Basic in the file?

File: packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts [hunk 5]
```diff
@@ -58,46 +54,115 @@ export interface IHoverCardProps extends React.HTMLAttributes<HTMLDivElement | H
...
+   * HotKey used for opening the HoverCard when tabbed to target.
+   * @default 'KeyCodes.c'
    */
-  onCardVisible?: () => void;
+  openHotKey?: KeyCodes;
 
   /**
-   * Callback when card hides
+   * Additional PlainCard props to pass through HoverCard like renderers, target, gapSpace etc.
+   * Used along with 'type' prop set to HoverCardType.basic.
```
Comment (atneik) [inline packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts]: HoverCardType.plain?

File: packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts [hunk 6]
```diff
@@ -58,46 +54,115 @@ export interface IHoverCardProps extends React.HTMLAttributes<HTMLDivElement | H
...
+export enum HoverCardType {
+  /**
+   * Plain card consisting of one part responsive to the size of content.
+   */
+  plain = 'PlainCard',
+
+  /**
+   * File card consisting of two parts: compact and expanded. Has some default sizes if not specified.
+   */
+  expanding = 'ExpandingCard'
```
Comment (atneik) [inline packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts]: For some reason in documentation I only see first enum

Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts]: This is due to the documentation parser we have not playing well with enums having string values. If I would have used 1 and 2 as values it would show up both. I actually wanted to file an issue regarding this and a couple more things I noticed with the parser. Don't think we should change it to use numbers as it's more helpful through the intellisense as it is right now.

**Comment by mikewheaton** [comment]
The deploy isn't working, so I pulled down the branch and built it locally. Looks great!
