### PR TITLE
Dropdown: Adding htmlFor to dropdown labels

### LINKED ISSUE #1013: PeoplePicker: No screen alert about auto-suggestion after the suggestion list is shown up
### Bug Report

- __Package version(s)__: any
- __Browser and OS versions__: IE 11.0.9600.18538 (haven't tested other version)
- JAWS version: 18.0.2324 and 17.0.2619 (haven't tested other version)

#### Describe the issue:

1. enter some letter like 'a' into input area of PeoplePicker in demo page
2. the auto-suggestion list pop up and the string is resolved as the first people in the list

#### Actual behavior:

There is no screen alert for the suggestion list.

#### Expected behavior:

There should be screen alert for suggestion list.
I tried JAWS on chrome and it works. That's strange.

### If applicable, please provide a codepen repro:

I tried on Fabric React demo page: https://dev.office.com/fabric#/components/peoplepicker

### PR DESCRIPTION
**Pull request by kristoferbrown**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1013 and #1610
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Adding a for property to dropdown label elements, this reduces fixes issues where screen readers could get confused as to what label matched what element, such as issue #1013.

#### Focus areas to test
Dropdown

### CODE REVIEW

**Comment by micahgodbolt** [comment]
@kristoferbrown can you confirm with @MirandaGe that this solves the original issue?

**Comment by micahgodbolt** [comment]
otherwise aces

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -146,7 +146,7 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
     return (
       <div ref='root' className={ css('ms-Dropdown-container') }>
         { label && (
-          <Label className={ css('ms-Dropdown-label') } id={ id + '-label' } ref={ this._resolveRef('_dropdownLabel') } required={ required }>{ label }</Label>
+          <Label className={ css('ms-Dropdown-label') } id={ id + '-label' } htmlFor={ id } ref={ this._resolveRef('_dropdownLabel') } required={ required }>{ label }</Label>
```
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: this should happen only if `ariaLabel` option is not set, Also, with this change we don't need to set `aria-label = { label }` on main dropdown div as that will be redundant.
```
<Label htmlFor={ ariaLabel ? undefined: id } />
...
// Dropdown
<div 
   role='combobox'
   aria-label={ ariaLabel }
   .... />

Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: this should happen only if `ariaLabel` option is not set, Also, with this change we don't need to set `aria-label = { label }` on main dropdown div as that will be redundant.
```
<Label htmlFor={ ariaLabel ? undefined: id } />
...
// Dropdown
<div 
   role='combobox'
   aria-label={ ariaLabel }
   .... />

Comment (kristoferbrown) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: @mdahamiwal, `aria-label` doesn't indicate what the `<label>` element is labeling, so I would argue that this is still needed even if `aria-label` exists. 

I think we should only remove `aria-label` when the `label` prop exists, but always have `htmlFor` set on the `<label>` element prop if it is shown.

**Comment by kristoferbrown** [comment]
@mdahamiwal, take a look at the most recent update. It makes `aria-label` go away if `label` exists, but otherwise `label `and `htmlFor` win.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (MirandaGe) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: I tested using narrator on the dev-deploy link, the label is read out as expected.

But the first person in the list is focused by default and that person's information is still not read not, I suppose it should be added to this label. @ipip2005 , do you have other considerations?

Comment (kristoferbrown) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: This label is being added dropdowns to prevent the one on the people picker example page from mistakenly being read instead of the people picker elements, so the first list item shouldn't be added here.

I'll file a separate issue about the first item being skipped by the reader.

**Comment by kristoferbrown** [comment]
@MirandaGe, I filed issue #2536 to track  what you mention about the first suggestion not being read.

@mdahamiwal, can you take another look at this PR? It's still blocked by your review.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx (hunk 1 above)
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: this looks fine. Seems like removing `htmlFor` under certain conditions can change click focus behavior as well. So, good to keep it as it is.

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 2]
```diff
@@ -156,7 +156,7 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
           aria-expanded={ isOpen ? 'true' : 'false' }
           role='menu'
           aria-live={ disabled || isOpen ? 'off' : 'assertive' }
-          aria-label={ ariaLabel || label }
+          aria-label={ ariaLabel && !label ? ariaLabel : null }
```
Comment (mdahamiwal) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: This seems unnecessary, we should just keep it `aria-label={ ariaLabel }`. To clarify, if user provides both `label` and `ariaLabel`, the `ariaLabel` should win and setting it as is it will take of that.

Comment (kristoferbrown) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: @mdahamiwal, great suggestion. This has been changed in the most recent update.

**Comment by micahgodbolt** [comment]
@kristoferbrown if it seems everyone is happy with this, but you are just missing a review, I can push it through.

**Comment by kristoferbrown** [comment]
That would be helpful!
