### PR TITLE
[ColorRectangle, Sticky] Fixed null root refs

### LINKED ISSUE #4073: Sticky - this.root undefined
### Bug Report

- __Package version(s)__: 5.54.0
- __Browser and OS versions__:  Chrome, Windows

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

Sticky component does not work due to this.root being undefined, resulting in failing various function calls. Believe this is due to PR #4016 changing 'this.refs.root' to 'this._root' for resolving refs but function calls still using 'this.root' instead of 'this._root'. Looks like there are some other occurrences in that PR of adding a prefix of _ in the name but not updating where the variable is used such as ColorPicker/ColorRectangle.tsx.

#### Actual behavior:

this.root is undefined

#### Expected behavior:

this.root to resolve to the correct ref

### If applicable, please provide a codepen repro:

Using the ScrollablePane DetailsList Locked Header example:

https://codesandbox.io/s/62kpzv6l5n

### PR DESCRIPTION
**Pull request by lambertwang**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4073
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Fixed null root refs.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx [hunk 1]
```diff
@@ -130,7 +130,7 @@ export class Sticky extends BaseComponent<IStickyProps, IStickyState> {
     const isSticky = isStickyTop || isStickyBottom;
 
     return (
-      <div ref={ this._resolveRef('_root') }>
+      <div ref={ this._resolveRef('root') }>
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx]: Since this couldn't have possibly worked, let's keep it as _root and make the variable private.

**Comment by aappddeevv** [comment]
Can this go into a 5.55.3?
