### PR TITLE
Spin button/run validation on empty string

### LINKED ISSUE #5088: SpinButton doesn't validate on blur when text is cleared
### Bug Report

- __Package version(s)__: All (I believe). We're looking at 5.112.0
- __Browser and OS versions__: All
- __Microsoft Alias__: rpsenski

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Office online apps: (Word, PowerPoint, et al)

#### Describe the issue:

Clear the value in the input box associated with the SpinButton
Cause onBlur event (tab to next control, e.g.)

#### Actual behavior:

Control appears to accept the input

#### Expected behavior:

Revert to previous value

### PR DESCRIPTION
**Pull request by rpsenski**
#### Pull request checklist

- Addresses an existing issue: Fixes #5088
- Include a change request file using `$ npm run change`
- Microsoft Alias (if you have one): rpsenski

#### Description of changes

There is a check that the value in state is valid in the _validate function. If the check returns false, onValidate isn't called. The check returns false if state.value is empty string or pure whitespace. This update makes the check an explicit check for undefined so validation will run against empty and whitespace input.

To leverage this change, the _defaultValidation function needs to be updated to check for null, empty or pure whitespace input because the Number constructor with any of these as the argument gives a value of 0. 

Also updating the stateful example to also check for empty/whitespace for consistency.

#### Focus areas to test

SpinButton validation when the control loses focus

Specific scenario targeted with this fix is to clear the SpinButton value and then cause the control to lose focus. previously it did not validation. Now it invokes the onValidate function, which by default reverts the entry to the last valid input in the SpinButton control.

### CODE REVIEW

**Comment by rpsenski** [comment]
@jspurlin: want to help review this?

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 1]
```diff
@@ -310,7 +310,7 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
    * Validate function to use if one is not passed in
    */
   private _defaultOnValidate = (value: string) => {
-    if (isNaN(Number(value))) {
+    if (value === null || value.trim().length === 0 || isNaN(Number(value))) {
```
Comment (jspurlin) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Can you add a comment for this?
