### PR TITLE
Fix bug #5672 - `getGlobalClassNames` usage in JS styling is a bit of a ticking time bomb

### LINKED ISSUE #5672: `getGlobalClassNames` usage in JS styling is a bit of a ticking time bomb
#### Describe the issue:

There is widespread use of global classnames in selectors at the moment. The whole point of using `getGlobalClassNames` from `oufr/lib/Styling` is so that users can choose to turn off globalClassNames at a single point. This however would cause widespread breakage because the global classnames are used in many component's base JS styles in selectors (given we lack a better mechanism around this atm).
 
#### Expected fix:
 
One possible fix is that when `getGlobalClassNames` is turned off, we should not return an empty string but return a system generated string instead.

### PR DESCRIPTION
**Pull request by cliffkoh**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #5672 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

getGlobalClassNames - when disabled, now returns a unique classname (modularized) instead of empty string.

Also added a new optional third argument that takes priority.

#### Focus areas to test

I have tested to ensure it does not result in a severe perf degradation when we disable global classnames.

### CODE REVIEW

File: packages/styling/src/styles/getGlobalClassNames.ts [hunk 1]
```diff
@@ -1,17 +1,40 @@
...
+    disableGlobalClassNames?: boolean
+  ): Partial<GlobalClassNames<T>> => {
+    const styleSheet = Stylesheet.getInstance();
 
-  return classNames;
-}
+    if (disableGlobalClassNames || (disableGlobalClassNames === undefined && theme.disableGlobalClassNames)) {
+      // disable global classnames
+      return Object.keys(classNames).reduce((acc: {}, className: string) => {
+        acc[className] = styleSheet.getClassName('__global-class-name__');
```
Comment (dzearing) [inline packages/styling/src/styles/getGlobalClassNames.ts]: I have a suggestion here; rather than use a very undebuggable `__global-class-name`, why not provide the original value (e.g. `ms-Button`), which will then just append the counter to that. Then you retain the debuggability of the names, while ensuring uniqueness.

**Comment by dzearing** [comment]
Missing change file?

**Comment by cliffkoh** [comment]
Oh.. because of the unit test tweak I had to make 🤦‍♂️
