### PR TITLE
Fixing Picker suggestions RTL alignment

### LINKED ISSUE #2850: Picker - PeoplePicker: Right to Left Support
### Bug Report

- __Package version(s)__:  5.0
- __Browser and OS versions__: FF, Chrome, Safari, Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

#### Describe the issue:

The Picker and PeoplePicker components open their drop down on the left side instead of the right side in RTL.

#### Actual behavior:

screen shot 2017-09-14 at 2 07 06 pm

#### Expected behavior:

The drop down menu of the Pickers should be opened on the right side.

### PR DESCRIPTION
**Pull request by kristoferbrown**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #2850
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Just setting directionalHint based on getRTL wasn't working, so this PR sets directionalHint and directionalHintForRTL to put the suggestions in the right spot.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -230,7 +230,8 @@ export class BasePicker<T, P extends IBasePickerProps<T>> extends BaseComponent<
         gapSpace={ 5 }
         target={ this.input.inputElement }
         onDismiss={ this.dismissSuggestions }
-        directionalHint={ getRTL() ? DirectionalHint.bottomRightEdge : DirectionalHint.bottomLeftEdge }
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Remove the getRTL import.

Comment (kristoferbrown) [reply packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: Great catch. It's removed now.
