### PR TITLE
ComboBox: Fix so options update correctly (#2301)

### LINKED ISSUE #2301: ComboBox Doesn't Update Options on Re-Render
### Bug Report

- __Package version(s)__: office-ui-fabric-core: ^7.1.2, office-ui-fabric-react: ^4.21.1,
- __Browser and OS versions__: Slackware 14.2, Opera 45.0.2552.898

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

#### Describe the issue:

ComboBox s don't respect the options property the second time that they're rendered and every time there after.

#### Actual behavior:

If the options for a ComboBox  are set the first time it's rendered then they're visible.  If you only set them on the second render or any re render thereafter, then they're not updated.

#### Expected behavior:

A ComboBox should always render the supplied options.

### If applicable, please provide a codepen repro:

I've provided a github project which replicates the issue and demonstrates how a DropDown has the expected behavior here: https://github.com/Quiescent/replicate-combobox-issue/

(I wasn't aware of the preference to use codepen before I pushed up this project.)

### PR DESCRIPTION
**Pull request by jspurlin**
#### Pull request checklist

- [X] Addresses an existing issue: Fixes #2301 
- [X] Include a change request file using `$ npm run change`

#### Description of changes

If the selectedKey or value did not update when the options were updated, we did not correctly update the options.

This fix makes it so that any time new options are passed in the comboBox get the updated options

#### Focus areas to test

Verified the repro attached to the bug no longer repros. Sanity tested that getting the options; updating the options, value, and/or selectedKey all work as expected

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -145,10 +145,9 @@ export class ComboBox extends BaseComponent<IComboBoxProps, IComboBoxState> {
   }
 
   public componentWillReceiveProps(newProps: IComboBoxProps) {
-    // In controlled component usage where selectedKey or value is provided,
-    // update the selectedIndex and currentOptions state if the selectedKey or options have changed
-    if ((newProps.selectedKey || newProps.value) &&
-      (newProps.selectedKey !== this.props.selectedKey || newProps.options !== this.props.options)) {
+    // Update the selectedIndex and currentOptions state if the selectedKey or options have changed
+    if (((newProps.selectedKey || newProps.value) && newProps.selectedKey !== this.props.selectedKey) ||
+      newProps.options !== this.props.options) {
```
Comment (christiango) [inline packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: is the second half of this if statement sufficient (i.e. just checking if the props are different vs checking that they also are truthy)?

**Comment by christiango** [comment]
Are there any tests here we can add that would fail before this fix?

File: packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx (hunk 1 above)
Comment (jspurlin) [reply packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx]: Yes, I think it's sufficient, it is better to update the currentOptions when the objects are different as opposed to trying to do something smarter here and potentially missing a case.
