### PR TITLE
Fixed issue #9384: Fix context menu width with split button and overflow text

### LINKED ISSUE #9384: ContextMenu with split button and the width not automatic does not handle text wider than the dropdown well
### Environment Information 
 
- __Package version(s)__: 6.189.2 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
Repro by going to https://fabricweb.z5.web.core.windows.net/oufr/6.189.2/#/examples/contextmenu and on the ContextualMenu with checkable menu items and toggleable split button change the width of the ms-ContextualMenu to 223px (mimicking constrained with the useTargetWidth option) and you will see the last menu item is not correctly centered and the split button is not correct. If you delete an the ms-Icon-placeHolder from one of the menu items with the split (which will be how it is if you don't have icons) and make the text a fair bit longer you will see how it it runs off both sizes and pushes the split arrow off the side.

#### Actual behavior:

Text is cut off on both sides and the arrow on the right is pushed off the screen
 
#### Expected behavior:
 
Text is correctly pruned with the ellipsis as happens without the split menu.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Maybe, I haven't looked into the code closely on this issue yet.
 
Requested priority: (Blocking, High, Normal, Low) Normal. We are GA with the feature using this on June 13th, but it only affects long strings. Not sure how to workaround it yet, but it doesn't make the feature unusable, but it is a bad experience for the user if the text is too long.
 
Products/sites affected: (if applicable) www.microsoftpartnerconnect.com

### PR DESCRIPTION
**Pull request by jgage176**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9384 
- [x] Include a change request file using `$ npm run change`
[1906-fixDropdownSplitTextIssue_2019-06-11-06-38.txt](https://github.com/OfficeDev/office-ui-fabric-react/files/3275052/1906-fixDropdownSplitTextIssue_2019-06-11-06-38.txt)

#### Description of changes

Set context menu width when using a split button to calculation of total width minus the width of the split menu button

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9406)

### CODE REVIEW

**Comment by aneeshack4** [comment]
@jgage176 Please do `npm run change` and commit the change file - looks like that's what the build failed on.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 1]
```diff
@@ -37,6 +37,8 @@ export interface IMenuItemClassNames {
   linkContentMenu: string;
 }
 
+const CONTEXTUAL_SPLIT_MENU_WIDTH = '28px';
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: Nit, this should be CONTEXTUAL_SPLIT_MENU_MINWIDTH

Comment (jgage176) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: > @jgage176 Please do npm run change and commit the change file - looks like that's what the build failed on.

Ah, it said to run that in the instructions but I didn't know what to do with the file - I didn't realize we needed to commit it - I tried to attach it to the PR but it didn't allow me to ;)

**Comment by jgage176** [comment]
> Something went wrong with the git history and now it shows like the entire file is altered. This makes harder to spot what the real changes are. Can you revert the last commit and then redo the feedback with the change log step, please. See what the diff shows you when you redo things.

Not sure what happened - if you view it in GitHub it only shows the differences correctly. If you view it in CodeFlow and ignore whitespace it shows it correctly. I am also comparing whitespace and don't see any diffs. I tried going back to the old version but so far it doesn't seem to recognize there is any difference.

**Comment by jgage176** [comment]
Okay, did a full revert of the commit and redid the fix and it seems to have worked this time. Not sure what happened before.

---
In reply to: [501066214](https://github.com/OfficeDev/office-ui-fabric-react/pull/9406#issuecomment-501066214) [](ancestors = 501066214)

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts [hunk 2]
```diff
@@ -149,7 +154,7 @@ export const getItemClassNames = memoizeFunction(
         {
           flexBasis: '0',
           padding: '0 8px',
-          minWidth: 28
+          minWidth: CONTEXTUAL_SPLIT_MENU_MINWIDTH
```
Comment (Vitalius1) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: I wonder why we use `minWidth` in here? Can this split menu grow in size? Maybe it should be fixed because I think with the the new `width` style you are adding to the `splitPrimary` it might never grow beyond 28px.

Comment (Vitalius1) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: Thanks for fixing the git history issue 👍

Comment (jgage176) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: In reality I don't I'm hard coding the rest of the control to 100% - 28px, so the split button will always be 28px. I was just trying to have less code change than more, but I'm open to changing it to width instead.

**Comment by aneeshack4** [comment]
Just putting the do not merge label on for now so no PRs get merged while we're locked down finishing up fabric 7.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts (hunk 2 above)
Comment (joschect) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.classNames.ts]: The menu button should grow to fill the space available, I think. The width on the split primary seems to ensure that it will always try to an additional 28 pixels to fit the split menu button. Should there be a minimum width for the contextualmenu maybe? I don't know if we can assume that. This seems like a good middle ground.

**Comment by jgage176** [comment]
This is my first PR in office-ui-fabric, could someone help me understand why my build is failing? I have committed a change file but the build failed "check change" so it looks like I did something wrong with that file.

**Comment by aneeshack4** [comment]
Hmm this was passing a little while ago - we can try closing & reopening this PR to trigger the run again. If that doesn't work, can you try doing `npm run change` again to see if it prompts you to make changes to the change file and commit a new one?

**Comment by jgage176** [comment]
Okay, I'll try, it doesn't look like the build worked, but it says it was manually deleted or something, I wasn't able to see the record.

---
In reply to: [501402032](https://github.com/OfficeDev/office-ui-fabric-react/pull/9406#issuecomment-501402032) [](ancestors = 501402032)

**Comment by aneeshack4** [comment]
Looks like there's a visual regression but it's a bit strange because it's in DocumentCard which doesn't seem related contextual menu - were you expecting this change @jgage176? 
image

**Comment by jgage176** [comment]
Not at all. Why would a change to the split context menu have any effect here? That being said, I'm not sure that the left is better than the right. See other comment with pictures on current prod deployment taken from here: [https://developer.microsoft.com/en-us/fabric#/controls/web/documentcard](https://developer.microsoft.com/en-us/fabric#/controls/web/documentcard).

---
In reply to: [501437434](https://github.com/OfficeDev/office-ui-fabric-react/pull/9406#issuecomment-501437434) [](ancestors = 501437434)

**Comment by aneeshack4** [comment]
It looks like they're all passing now, including screener - must have been a fluke. Pinging @joschect for approval... we can't merge til the branch's unlocked (currently locked for fabric 7 release stuff).

**Comment by jgage176** [comment]
Since it is passing now and judging from the screenshots below, I'm guessing there is something slightly indeterministic about the test with the screenshot. Here is what it looks like in the current version in prod in Chrome:

image

Here is what it looks like if I extend the height to two roles as it is in the pictures:

image

Here is what is looks like if I extend the width to 330px (instead of 320px):

image

Here is what it looks like in Prod, whether space for two lines or one:

image

**Comment by jgage176** [comment]
In fact the first screenshot there looks like a bug since it really didn't have enough space for a second line.

---
In reply to: [501465209](https://github.com/OfficeDev/office-ui-fabric-react/pull/9406#issuecomment-501465209) [](ancestors = 501465209)

**Comment by aneeshack4** [comment]
pinging @joschect for code owner approval
