### PR TITLE
IconNames: Deprecate due to const enum usage

### LINKED ISSUE #7110: Ambient const enums are not allowed when the '--isolatedModules' flag is provided
Project created with create-react-app 2.1 with TS 3.1.6 is not compiling and falling with error:

> yarn build
> 
> yarn run v1.12.3
> $ react-scripts build
> Creating an optimized production build...
> Failed to compile.
> 
> .../node_modules/@uifabric/utilities/lib/KeyCodes.d.ts
> Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209
> 
>     4 |  * @public
>     5 |  */
>   > 6 | export declare const enum KeyCodes {
>       |                           ^
>     7 |     backspace = 8,
>     8 |     tab = 9,
>     9 |     enter = 13,

Project dependencies:

```
  "dependencies": {
    "@types/dagre": "^0.7.40",
    "@types/jest": "^23.3.9",
    "@types/node": "^10.12.5",
    "@types/react": "^16.7.3",
    "@types/react-dom": "^16.0.9",
    "dagre": "^0.8.2",
    "office-ui-fabric-react": "^6.102.0",
    "react": "^16.6.1",
    "react-dom": "^16.6.1",
    "react-redux": "^5.1.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.5",
    "redux-thunk": "^2.3.0",
    "typesafe-actions": "^2.0.4",
    "typescript": "^3.1.6"
  },
```

### LINKED ISSUE #8003: Ambient const enums are not allowed when the '--isolatedModules' flag is provided (Remove last const enum in IconNames.d.ts)
Hi Microsoft UI Fabric team,

This is a follow up to #7110 where @micahgodbolt mentioned opening a new issue to track the last use of const enums which is causing this error.  The bug seems to have fallen through the cracks and I hope opening this new issue will help to resurface it and get it fixed.

Based on other discussions around this topic, I can see that @kenotron and others have spent a lot of time and effort in removing all the const enums from the library - this issue is to track removing the last remaining usage within `IconNames.d.ts`

Thanks,
Bradley

### PR DESCRIPTION
**Pull request by JasonGore**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7110, Fixes #8003
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Per #7110 deprecate `IconNames` due to its usage of `const enum`.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8005)

### CODE REVIEW

File: packages/icons/src/IconNames.ts [hunk 1]
```diff
@@ -1675,4 +1678,8 @@ export const enum IconNames {
   SizeLegacy = 'SizeLegacy'
 }
 
+/**
+ * @deprecate IconNames is deprecated.
```
Comment (dzearing) [inline packages/icons/src/IconNames.ts]: Why is this deprecated?

**Comment by KevinTCoughlin** [comment]
Last I checked, SPFx was using string union type, but will double check. cc: @patmill

File: packages/icons/src/IconNames.ts (hunk 1 above)
Comment (JasonGore) [reply packages/icons/src/IconNames.ts]: Pulling in the type will pull in IconNames, which will result in the issue people are seeing in #7110, so that is why I also marked this deprecated. Does that make sense?

I will talk to Peter about the tool, thanks.

Comment (JasonGore) [reply packages/icons/src/IconNames.ts]: More simply put maybe I should have just said it's a deprecated type, since it's keying off a deprecated object. 😄

**Comment by JasonGore** [comment]
Spoke with @Jahnp and we may decide to close this PR and make another one from the upstream tool changes. I'll mark "Do not merge" for now and close/update within the next day or so.

File: packages/icons/src/IconNames.ts (hunk 1 above)
Comment (kenotron) [reply packages/icons/src/IconNames.ts]: The tool should be adjusted, agreed. We should probably file a bug there as well.

Comment (kenotron) [reply packages/icons/src/IconNames.ts]: @Jahnp - FYI

**Comment by Jahnp** [comment]
@JasonGore and I chatted some more offline. This works great for now--we'll go ahead and deprecate the `IconNames` enum and plan to remove it for 7.0. We'll keep `IconNamesInput`, and in 7.0 replace it with a plan vs inferred string union.

File: packages/icons/src/IconNames.ts (hunk 1 above)
Comment (dzearing) [reply packages/icons/src/IconNames.ts]: I believe @ThomasMichon added this. A better approach would be to keep the type, but just generate the type. adding this was a cheap way to get some type safety.

also, the tag should be `@deprecated`, not `@deprecate`.

Comment (JasonGore) [reply packages/icons/src/IconNames.ts]: I removed this change before the PR was merged.

**Comment by BTC-Bradley** [comment]
> we'll go ahead and deprecate the `IconNames` enum and plan to remove it for 7.0.

@Jahnp, is there a road-map w/ ETA for the 7.0 release?

**Comment by Jahnp** [comment]
@BTC-Bradley project planning for 7.0 is early but actively being worked on. We're hoping to have it out within the next few months, but that's pending some investigations. You can track progress here (project is being built up & managed by @jdhuntington): https://github.com/OfficeDev/office-ui-fabric-react/projects/29
