### PR TITLE
Bug fix: Dropdown - SelectedKey selects dropdown option with a different key

### LINKED ISSUE #2551: Dropdown: SelectedKey selects dropdown option with a different key
### Bug Report

- __Package version(s)__: v4.35.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes
Created pull request https://github.com/OfficeDev/office-ui-fabric-react/pull/2552

Requested priority: Blocking

Products/sites affected: OWA Calendar

#### Describe the issue:

The selectedKey property isn't setting the dropdown as expected.
The logic in the dropdown getSelectedIndex is missing parentheses, which creates a bug in the dropdown menu. 

#### Actual behavior:

When passing the selectedKey value through, it selects an item from the options with a different key than the selected key.

#### Expected behavior:

When passing the selectedKey value through, I expect it to select the dropdown option with the same key.

### If applicable, please provide a codepen repro:
Unable to repro in codepen but was able to repro on deployed branch here:
https://outlook-sdf.office.com/mail/calendar/?branch=Melinas-MacBook-Pro-melspa-bugQuickComposeDurationRegression#/calendar

Repro steps:
1. Press "+ New"
2. Type text in the text field to get the full page to display
3. Check the "All day" checkbox
4. Click the duration dropdown and select "2 days"
5. Increase the end date by one day

After step 5, the dropdown menu should display 3 days.

### PR DESCRIPTION
**Pull request by melvsparks**
#### Pull request checklist

Note: This is my first pull request

- [x] Addresses an existing issue: Fixes #2551
- [x] Include a change request file using `$ npm run change` 

#### Description of changes

The logic within the getSelectedKey method within the dropdown needed additional parenthesis so that the ordering of the logic executes correctly.

### CODE REVIEW

**Comment by melvsparks** [comment]
@micahgodbolt

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -542,7 +542,7 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Add a change file `rush change -b upstream`
