### PR TITLE
Dropdown: do not select disabled items on keydown

### LINKED ISSUE #4331: Dropdown - Can select disabled item using arrow keys
### Bug Report

- __Package version(s)__: office-ui-fabric-react@5.55.1004

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Blocking, High, Normal, Low)  High

#### Describe the issue:

In a dropdown, if you have a disabled item, then we are able to select that item using keys (up/down) on the closed dropdown. This can also be seen on the Office UI Fabric page of Dropdown too.

The disabled entity in the callout appears to be disabled. But once you close the callout, and on the textbox (dropdown selected entity), if you start pressing up/down key, the disabled entities also get picked up by the dropdown.

#### Actual behavior:
The disabled items are getting selected in the dropdown using keys (up/down)

#### Expected behavior:
The disabled items should never get selected either from mouse or keyboaqrd

### If applicable, please provide a codepen repro:
Check the office fabric page for Dropdown. It is easy to repro there too (Example 1)

### PR DESCRIPTION
**Pull request by aditima**
#### Pull request checklist

- [X ] Addresses an existing issue: Fixes #4331
- [X ] Include a change request file using `$ npm run change`

#### Description of changes

Skip disabled items when keyboarding to find the next item to select

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx [hunk 1]
```diff
@@ -301,8 +301,10 @@ export class Dropdown extends BaseComponent<IDropdownInternalProps, IDropdownSta
       index = options.length - 1;
     }
     let stepCounter = 0;
-    // If current index is a header or divider, increment by step
-    while (options[index].itemType === DropdownMenuItemType.Header || options[index].itemType === DropdownMenuItemType.Divider) {
+    // If current index is a header or divider, or disabled, increment by step
+    while (options[index].itemType === DropdownMenuItemType.Header ||
+      options[index].itemType === DropdownMenuItemType.Divider ||
+      options[index].disabled) {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: I believe that disabled items should still be selectable for accessibility reasons. If someone isn't sighted, how would they know there were disabled items?

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Good catch @joschect. @jspurlin for fyi!

Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx]: Not selectable, but focusable?
