### PR TITLE
ContextualMenu: Fix event is undefined when checkmark clicked in ContextualMenuItem

### LINKED ISSUE #7145: Click on contextual menu item checkmark causes an Uncaught TypeError
### Environment Information 
 
 
- __Package version(s)__: 6.99.0
- __Browser and OS versions__: Chrome 70.0.3538.102 on Windows 10 

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/avenezia/pen/pQWqEy

 
#### Actual behavior:
 
When clicking on the checkmark icon of a context menu item, the following exception is thrown

Uncaught TypeError: t.stopPropagation is not a function
    at t.o._onItemClickBase (tslib.es6.js:17)
    at t.o._onItemClick (tslib.es6.js:17)
    at onClick (tslib.es6.js:17)
    at HTMLUnknownElement.callCallback (react-dom.development.js:143)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:193)
    at invokeGuardedCallback (react-dom.development.js:250)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:264)
    at executeDispatch (react-dom.development.js:555)
    at executeDispatchesInOrder (react-dom.development.js:574)
    at executeDispatchesAndRelease (react-dom.development.js:674)

It seems due to the fact that the item parameter is bound in [ContextualMenuButton.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/e9b6ce9d465f3b9342e7b1d1af27a96fd8c8b922/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx#L89), 
but then the item object is passed again in the [onClick](https://github.com/OfficeDev/office-ui-fabric-react/blob/2ce6c5ac3ccf4e62d4866841317b4aa55b8fb541/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.base.tsx#L26) event handler.
 
#### Expected behavior:
 
Click on the checkmark should work without throwing the exception

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? I can, if needed
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: Power Query Online

### PR DESCRIPTION
**Pull request by KevinTCoughlin**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7145
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Removes what seem to be unnecessary binds in the `ContextualMenuItem` wrapper classes which result in `$event` being dropped in the `onItemClick` callback args. This is due to `bind` modifying the callback _context_ and _arguments list_.

#### Focus areas to test

Test this branch in https://codepen.io/avenezia/pen/pQWqEy by proxying localhost or modify the "Basic" example to match the Codepen.

When the check-mark is clicked it will no longer throw an error because the args list is not missing `event` (and target). **Note:** As you can see in the repro Codepen, the click target is _narrow_ to get this to occur.

I plan to add a unit test for this behavior prior to merging this PR.

**Edit:** Unit tests have been added.

### CODE REVIEW

**Comment by aneeshack4** [comment]
@joschect It looks like this PR needs code owner review - would you be able to sign off?

**Comment by KevinTCoughlin** [comment]
> 
> 
> @joschect It looks like this PR needs code owner review - would you be able to sign off?

FYI - I have unit tests in my local branch. Let me push them up once I get thru today's issue queue. I'll work to get this merged once that iteration is pushed.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx [hunk 1]
```diff
@@ -74,7 +74,7 @@ export class ContextualMenuAnchor extends ContextualMenuItemWrapper {
                 item={item}
                 classNames={classNames}
                 index={index}
-                onCheckmarkClick={hasCheckmarks && onItemClick ? onItemClick.bind(this, item) : undefined}
+                onCheckmarkClick={hasCheckmarks && onItemClick ? onItemClick : undefined}
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx]: We definitely can't do this, you have to pass the item through. Something like adding a lambda as a pass through in the base might work.

**Comment by KevinTCoughlin** [comment]
I've added unit tests covering the check-mark clicks. Here are the failures when the tests are run against `master` without these changes.

**ContextualMenuItemAnchor**

```tsx
 FAIL  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.test.tsx
  ● ContextualMenuButton › creates a normal button › invokes optional onItemClick on checkmark node "click"

    expect(object).toHaveProperty(path, value)

    Expected the object:
      {"key": "123"}
    To have a nested property:
      "foo"
    With a value of:
      "bar"

      68 |       expect(onClickMock.mock.calls[0][0]).toBe(menuItem);
    > 69 |       expect(onClickMock.mock.calls[0][1]).toHaveProperty('foo', 'bar');
         |                                            ^
      70 |       expect(onClickMock.mock.calls[1][0]).toBe(menuItem);
      71 |       expect(onClickMock.mock.calls[1][1]).toHaveProperty('foo', 'bar');

      at Object.<anonymous> (src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.test.tsx:69:44)
```

**ContextualMenuItemButton**

```tsx
 FAIL  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.test.tsx
  ● ContextualMenuButton › creates a normal button › invokes optional onItemClick on checkmark node "click"

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ObjectContaining {"foo": "bar"} as argument 2, but it was called with {"key": "123"}.
      undefined as argument 3, but it was called with {"_dispatchInstances": null, "_dispatchListeners": null, "_targetInst": {"_debugID": 60, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": null, "child": null, "childExpirationTime": 0, "effectTag": 0, "elementType": "i", "expirationTime": 0, "firstContextDependency": null, "firstEffect": null, "index": 0, "key": null, "lastEffect": null, "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": <i … />, "tag": 5, "treeBaseDuration": 0, "type": "i", "updateQueue": null}, "bubbles": undefined, "cancelable": undefined, "currentTarget": null, "defaultPrevented": undefined, "dispatchConfig": {"dependencies": [Array], "isInteractive": true, "phasedRegistrationNames": [Object]}, "eventPhase": undefined, "foo": "bar", "isDefaultPrevented": [Function functionThatReturnsFalse], "isPersistent": [Function functionThatReturnsTrue], "isPropagationStopped": [Function functionThatReturnsFalse], "isTrusted": undefined, "nativeEvent": {"target": <i … />, "type": "click"}, "target": <i aria-hidden="true" class="ms-Icon-placeHolder checkmarkIcon root-33" data-icon-name="" role="presentation" />, "timeStamp": 1542753696809, "type": "click"}.

      45 |
      46 |       expect(onClickMock).toHaveBeenCalledTimes(1);
    > 47 |       expect(onClickMock).toHaveBeenCalledWith(menuItem, expect.objectContaining(mockEvent));
         |                           ^
      48 |     });
      49 |   });
      50 | });
```

**ContextualMenuItemSplitButton**

```tsx
 FAIL  src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuSplitButton.test.tsx
  ● ContextualMenuSplitButton › creates a normal split button › invokes optional onItemClick on checkmark node "click"

    expect(jest.fn()).toHaveBeenCalledWith(expected)

    Expected mock function to have been called with:
      ObjectContaining {"foo": "bar"} as argument 2, but it was called with {"aria-hidden": true, "canCheck": undefined, "checked": undefined, "className": "splitPrimary", "data-is-focusable": false, "disabled": undefined, "iconProps": undefined, "isChecked": undefined, "key": "123", "name": undefined, "text": undefined}.
      undefined as argument 3, but it was called with {"_dispatchInstances": null, "_dispatchListeners": null, "_targetInst": {"_debugID": 63, "_debugIsCurrentlyTiming": false, "_debugOwner": [FiberNode], "_debugSource": null, "actualDuration": 0, "actualStartTime": -1, "alternate": null, "child": null, "childExpirationTime": 0, "effectTag": 0, "elementType": "i", "expirationTime": 0, "firstContextDependency": null, "firstEffect": null, "index": 0, "key": null, "lastEffect": null, "memoizedProps": [Object], "memoizedState": null, "mode": 0, "nextEffect": null, "pendingProps": [Object], "ref": null, "return": [FiberNode], "selfBaseDuration": 0, "sibling": null, "stateNode": <i … />, "tag": 5, "treeBaseDuration": 0, "type": "i", "updateQueue": null}, "bubbles": undefined, "cancelable": undefined, "currentTarget": null, "defaultPrevented": undefined, "dispatchConfig": {"dependencies": [Array], "isInteractive": true, "phasedRegistrationNames": [Object]}, "eventPhase": undefined, "foo": "bar", "isDefaultPrevented": [Function functionThatReturnsFalse], "isPersistent": [Function functionThatReturnsTrue], "isPropagationStopped": [Function functionThatReturnsFalse], "isTrusted": undefined, "nativeEvent": {"target": <i … />, "type": "click"}, "target": <i aria-hidden="true" class="ms-Icon-placeHolder checkmarkIcon root-36" data-icon-name="" role="presentation" />, "timeStamp": 1542754061485, "type": "click"}.

      45 |
      46 |       expect(onClickMock).toHaveBeenCalledTimes(1);
    > 47 |       expect(onClickMock).toHaveBeenCalledWith(menuItem, expect.objectContaining(mockEvent));
         |                           ^
      48 |     });
      49 |   });
      50 | });
```

Notice that prior to this change we are passing the `item` twice due to `.bind` augmenting the arguments list.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx (hunk 1 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx]: Are you sure? See https://github.com/OfficeDev/office-ui-fabric-react/pull/7147#issuecomment-440459693

Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx]: If its because we'd lose `this` within 

https://github.com/OfficeDev/office-ui-fabric-react/blob/92ba8325a3f01c050da0d9e50effb1c399e39663/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx#L97

I'm unsure if that's a concern since we aren't invoking that but rather the prop callback directly.

**Comment by joschect** [comment]
We looked into it, the renderer for the icon was already adding the item, which is why the bind isn't needed.

**Comment by KevinTCoughlin** [comment]
> We looked into it, the renderer for the icon was already adding the item, which is why the bind isn't needed.

For bookkeeping, this LoC:

https://github.com/OfficeDev/office-ui-fabric-react/blob/92ba8325a3f01c050da0d9e50effb1c399e39663/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.base.tsx#L26

Thanks @joschect!

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx (hunk 1 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuAnchor.tsx]: Resolved offline, see:

- https://github.com/OfficeDev/office-ui-fabric-react/pull/7147#issuecomment-440471589
- https://github.com/OfficeDev/office-ui-fabric-react/pull/7147#issuecomment-440473971
