### PR TITLE
[ContextualMenu] Fixes useTargetWidth property

### LINKED ISSUE #3433: ContextualMenu useTargetWidth prop renders a menu that is slightly wider than the target
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Office Online

#### Describe the issue:
When using the useTargetWidth prop of a contextual menu, it is expected that the width of the menu exactly matches the width of the element that is set as the target of the menu. Instead, it appears that the callout is rendered a bit wider than the menu. It looks like this might be due to the fact that we set the width styling properties on a child of the callout rather than on the callout directly in ContextualMenu.tsx.

#### Actual behavior:
Here's what the menu looks like. It appears that border is not being included in the width calculations and that the positioning is one pixel too far to the right.

image

#### Expected behavior:
The menu width should match that of the target element.

### PR DESCRIPTION
**Pull request by martellaj**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3433
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Instead of using `offsetWidth`, which rounds the actual width value to the nearest integer, I changed the behavior to get the target element's bounding rect and use that element's actual `width` property. So instead of rendering a `ContextualMenu` that is slightly wider than the target, it'll now render with the proper width.

### CODE REVIEW

**Comment by martellaj** [comment]
@joschect Hey, Jon - you're required on this one. It's a pretty small change - can you please take a look when you get a chance? This affects one of the main UX flows in OWA. Thanks!

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx [hunk 1]
```diff
@@ -247,7 +247,9 @@ export class ContextualMenu extends BaseComponent<IContextualMenuProps, IContext
     let contextMenuStyle;
     let targetAsHtmlElement = this._target as HTMLElement;
     if ((useTargetWidth || useTargetAsMinWidth) && targetAsHtmlElement && targetAsHtmlElement.offsetWidth) {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: you're checking offsetWidth, but calling getBoundingClientRect, while it's probably fine we should still change it to be consistent.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx [hunk 2]
```diff
@@ -247,7 +247,9 @@ export class ContextualMenu extends BaseComponent<IContextualMenuProps, IContext
...
-      let targetWidth = targetAsHtmlElement.offsetWidth;
+      const targetBoundingRect = targetAsHtmlElement.getBoundingClientRect();
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: This should never have been in the render function in the first place. Calling offsetWidth/getBoundingClientRect (and other stuff) can trigger a reflow which is bad for performance. Ideally we'll store this and not call it again, and when we do call it it should be async. Move all of this to a separate function that get's called asynchronously.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx (hunk 1 above)
Comment (martellaj) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: What's the appropriate check here then? I would've thought checking `offsetWidth` initially was unnecessary anyway.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx (hunk 2 above)
Comment (martellaj) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: Any guidance on this? There doesn't seem to be any `async`/`await` patterns that exist in OUFR.

Comment (martellaj) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: I'm not sure how to include an `async` function in the `render` function. Should the calculation be done in life-cycle method?

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: Take a look at `_updateAsyncPosition()`. It uses `requestAnimationFrame` which essentially bundles the measures/renders separately, so instead of there being dom changes then measuring then dom changes again and then re-measuring (and so on), it tells the browser to complete dom changes, then measures after reflows are complete.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx [hunk 3]
```diff
@@ -330,6 +332,23 @@ export class ContextualMenu extends BaseComponent<IContextualMenuProps, IContext
     }
   }
 
+  private _setTargetWidthAsync() {
```
Comment (martellaj) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: @joschect Here's the attempt at asynchronously getting the target's width. Let me know what you think.

File: packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx [hunk 4]
```diff
@@ -330,6 +332,23 @@ export class ContextualMenu extends BaseComponent<IContextualMenuProps, IContext
...
+    // If component doesn't care about target's width, then this is a no-op.
+    if ((!this.props.useTargetWidth && !this.props.useTargetAsMinWidth) || !targetAsHtmlElement) {
+      return;
+    }
+
+    this._async.requestAnimationFrame(() => {
+      const targetBoundingRect = targetAsHtmlElement.getBoundingClientRect();
+
+      this.setState({
+        targetWidth: targetBoundingRect.width - 2 /* Need to account for border width */
```
Comment (manishgarg1) [inline packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: >targetWidth [](start = 8, length = 11)

Since this async, how do we make sure this value is set when the render API is called?

Comment (martellaj) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: It gets called in `componentWillMount`, so the value should be available in the `render` function. We'll have this issue either way since @joschect said even reading `offsetWidth` should be moved to an async function. Can someone more familiar with this pattern in OUFR help solve the problem? Do you have any suggestions, @manishgarg1?

Comment (martellaj) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: Or if you have a better way to solve it, feel free to take it over. The issue has been open since November with no activity and we need a fix. Thanks!

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx]: It's okay if the value is not set at first render, although it may cause apparent resizing. You would need to provide a default value though.

**Comment by martellaj** [comment]
@manishgarg1 @joschect Can I revert back to my original change where I measure to get the appropriate width? It's a separate issue (that already exists today) that it's done in the `render` function. Given that this component doesn't even have true tests, it's not easy thing for someone unfamiliar with the component code to change.

**Comment by joschect** [comment]
It's probably okay to revert to your original fix for now.

**Comment by martellaj** [comment]
@manishgarg1 The async bit is a separate issue, and should be addressed by someone more familiar with the code. I've reverted back to my original change to measure width appropriately.

@joschect Your sign-off is still required since you're the owner. Please let me know if there's any more required changes. Thanks!

**Comment by martellaj** [comment]
@joschect @dzearing Any issues with merging and completing this PR? If not, feel free to do so or I can do it later this afternoon. Thanks!
