### PR TITLE
Fix Callout so it always gets a valid element when finding target by …

### LINKED ISSUE #1977: Callout loses target element on re-render
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes
Requested priority: Normal 

Products/sites affected: Planner

#### Describe the issue:

When a callout is given a target by classname to track a react component, it is not searching for the element when react renders the callout.  When the target component was rendered with new data, the original no longer exists and the callout jumps to the top left corner.

#### Actual behavior:

Callout jumps to corner because it has not found the new react component.

#### Expected behavior:

Callout should find the new element and stay on it.

### PR DESCRIPTION
**Pull request by daweffe**
…classname.

#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #1977 - [ ] Include a change request file using `$ npm run change`

#### Description of changes

Change the Callout logic to find a target element on every re-render if target is being tracked with a classname.  This will ensure the callout does not lose the element if it is disposed and re-rendered by react.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx [hunk 1]
```diff
@@ -76,7 +76,8 @@ export class CalloutContent extends BaseComponent<ICalloutProps, ICalloutState>
   }
 
   public componentWillUpdate(newProps: ICalloutProps) {
-    if (newProps.targetElement !== this.props.targetElement || newProps.target !== this.props.target) {
+    // If the target element changed, find the new one. If we are tracking target with class name, always find element because we do not know if fabric has rendered a new element and disposed the old element.
+    if (newProps.targetElement !== this.props.targetElement || newProps.targetElement == null) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: @joschect hmm. What do you think here? It seems some logic has changed...

@daweffe also need to add a change request file (`npm run change` at root)

Comment (daweffe) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: I ran npm run change and the output said I didn't need it.  Is the output wrong?

Comment (daweffe) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: And about the logic, might it make sense to test if the newProps.target is a string?  If it is a mouse event we shouldn't have to recalculate.

Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: @daweffe make sure you are on this branch when running that change command. It will compare your branch to master, so make sure that these changes aren't also in master for some reason.

Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: We still need to check `newProps.target ` targetElement is deprecated and is really only there until we remove it in a major update. We really don't care if targetElement is null generally. Actually I'm not sure I understand this change. 

I made this callout codepenand it looks like it's fine if the state changes.

https://codepen.io/slimemold/pen/PjpEzv?editors=0010

Comment (daweffe) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: @joschect Your codepen does show that the callout is not updating location when the button changes.  When the callout is opened, the beak points to the center of the button.  When it changes text and therefore width, the beak is not moving with it.  In Planner this manifests by the callout moving to the upper left corner of the screen.

Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: I see what you mean now. That change makes sense, but I don't believe your fix will achieve what you want. What you're saying, and it make some amount of sense, is that target should be recalculated every time and that the if statement should really just be removed.

Comment (daweffe) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: If the target is a mouse event we shouldn't have to recalculate.

Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: This still seems a bit off to me. Before, it was executing this code on the condition that target or targetElement prop has changed, you removed the target prop change check completely. What happened to that?

Comment (daweffe) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: When target is a string for the Element's className, we want to update the location since react may dispose and render a new version, even is the class name is still the same.

Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: You're also still missing the checks for props.target then. You're using targetElement which is not the same as target. targetElement is deprecated and the support for it is currently just for backwards compatability.

**Comment by dzearing** [comment]
@daweffe ping on this. Were you going to update it, or should we close? Thanks!

**Comment by daweffe** [comment]
Yeah, I'm going to update it.

File: packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx [hunk 2]
```diff
@@ -79,7 +79,8 @@ export class CalloutContent extends BaseComponent<ICalloutProps, ICalloutState>
   }
 
   public componentWillUpdate(newProps: ICalloutProps) {
-    if (newProps.targetElement !== this.props.targetElement || newProps.target !== this.props.target) {
+    // If the target element changed, find the new one. If we are tracking target with class name, always find element because we do not know if fabric has rendered a new element and disposed the old element.
+    if (newProps.targetElement !== this.props.targetElement || newProps.target !== this.props.target || typeof(newProps.target) === 'string' || newProps.target instanceof String) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: isn't the `newProps.target instanceof String` redundant with `typeof newProps.target === 'string'` ?

Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: @joschect mind taking another look here? I think this is probably ok, but i haven't tested or thought through the implications of remeasuring on every componentWillUpdate? This seems like it could cause extraneous reflows in the browser, if we're clearing the height every time when using a string based target.

Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Callout/CalloutContent.tsx]: I believe that this will work fine.
