### PR TITLE
Fixes: 6962 - Label a11y pass

### LINKED ISSUE #6962: Label A11y Pass
Tracking all of the issues brought up with the 11/02 accessibility pass on label  control
Details on individual bugs can be found on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7b8a57405f-1c87-4e2d-8c24-5f15d53276a8%7d&action=edit&activeCell='Bugs'!L3&wdInitialSession=e7ad14f3-cb60-478f-bca2-be595d14abee&wdRldC=1)

- [x] Bug 1: [Accessibility][Visual requirements]: Color contrast ratio of 'I'm a disabled Label' text is less than 4.5:1.
- [x] Bug 2: [Accessibility][Usable]: Provide one instance to show the usage of "for” attribute to associate the labels to the form controls.

Component: Label
@micahgodbolt

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #6962
- [x] Include a change request file using `$ npm run change`

#### Description of changes

The first point of that bug isn't needed: the contrast ratio of a disabled button shouldn't be 4.5:1 - it should just be as it is.

The second is to add an example demonstrating the label for capability. This PR address the second issue of that bug.

### CODE REVIEW

File: packages/utilities/src/properties.ts [hunk 1]
```diff
@@ -231,6 +231,13 @@ export const buttonProperties = htmlElementProperties.concat(['disabled']);
  */
 export const divProperties = htmlElementProperties.concat(['align', 'noWrap']);
 
+/**
+ * An array of LABEL tag properties and events.
+ *
+ * @public
+ */
+export const labelProperties = htmlElementProperties.concat(['for', 'form']);
```
Comment (natalieethell) [inline packages/utilities/src/properties.ts]: Would we never need 'align' or 'noWrap' here, as added in `divProperties` above?

Comment (natalieethell) [reply packages/utilities/src/properties.ts]: Just curious given that Label used `divProperties` before

Comment (kenotron) [reply packages/utilities/src/properties.ts]: I'm gonna see if I can test out not mucking with this and just use "htmlFor" - although divProps seems wrong
