### PR TITLE
Coachmark: Positioning fixes

### LINKED ISSUE #4812: Teaching Bubble close icon on hover
#### Describe the issue:

The close icon on the teaching bubble turns white on hover instead of remaining blue. This is reproducible on the office fabric doc page. <a>https://developer.microsoft.com/en-us/fabric#/components/teachingbubble</a>

### PR DESCRIPTION
**Pull request by leddie24**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #4812
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

- Fixed positioning bugs (Coachmark/TeachingBubble will re-position on scroll/resize properly)
- Added in missing positions for Coachmark as well as alignment edges for the TeachingBubble/Beak
- Adds in missing beak directions for Beak
- Removed configuration props for Coachmark and set them as CONSTs instead
- Updated basic example to provide configuration of Coachmark position via Dropdown
- Fix TeachingBubble styling for buttons

**Coachmark right position:**
screen shot 2018-05-25 at 11 26 21 am

**Coachmark top position:**
screen shot 2018-05-25 at 11 26 37 am

**Coachmark left position**
screen shot 2018-05-25 at 11 26 44 am

**Teaching bubble close button hover fix**

Before:
screen shot 2018-05-25 at 11 30 54 am

After
screen shot 2018-05-25 at 11 27 02 am

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx [hunk 1]
```diff
@@ -197,11 +197,12 @@ export class PositioningContainer
     );
   }
 
-  public dismiss = (ev?: Event | React.MouseEvent<HTMLElement> | React.KeyboardEvent<HTMLElement>): void => {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx]: Since dismiss is public you'll need to keep it around and deprecate it.

File: packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.tsx [hunk 2]
```diff
@@ -165,56 +239,161 @@ export class Coachmark extends BaseComponent<ICoachmarkTypes, ICoachmarkState> {
...
+      case BeakDirection.Left:
+      case BeakDirection.Right:
+        // If there is no target alignment, then beak is Y-axis centered in callout
+        if (!targetAlignment) {
+          beakTop = `calc(50% - ${BEAK_WIDTH / 2}px)`;
+          transformOriginY = `center`;
+        } else {
+          // Beak is aligned to the top of target
+          if (targetAlignment === RectangleEdge.top) {
+            beakTop = `calc(${COACHMARK_WIDTH / 2}px - ${BEAK_WIDTH / 2}px)`;
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.tsx]: Why are you using calc? That's likely going to be slower than just doing the calculation right here in javascript.

File: packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.tsx [hunk 3]
```diff
@@ -98,33 +134,69 @@ export class Coachmark extends BaseComponent<ICoachmarkTypes, ICoachmarkState> {
     };
   }
 
+  private get _beakDirection(): BeakDirection {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.tsx]: I'd recommend using rectangleEdge from positioning. Then implement a public "getOppositeEdge" function in positioning which would look like 
```
export function getOppositeEdge(edge: RectangleEdge): RectangleEdge {
    return edge * -1;
} 
```

File: packages/office-ui-fabric-react/src/components/Coachmark/Beak/Beak.types.ts [hunk 4]
```diff
@@ -3,6 +3,13 @@ import { Beak } from './Beak';
 
 export interface IBeak { }
 
+export enum BeakDirection {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/Coachmark/Beak/Beak.types.ts]: Reuse RectangleEdge from positioning

**Comment by micahgodbolt** [comment]
@joschect i'm happy to sign off on this a codeowner as long as you are

**Comment by micahgodbolt** [comment]
give me a shout when you've got those bugs wrapped up and i'll approve

**Comment by leddie24** [comment]
@micahgodbolt  could you take another look when you get a chance?  Thanks!

**Comment by micahgodbolt** [comment]
As long as it all passes, i'm good. @joschect already signed off
