### PR TITLE
Button: Fix issue where button would eat keydowns

### LINKED ISSUE #8706: Vertical OveflowSet keyboard navigation sticks on the overflow
### Environment Information 
 
- __Package version(s)__: current
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:
 
https://developer.microsoft.com/en-us/fabric#/components/overflowset
 
#### Actual behavior:
 
arrowup and down in vertical overflow set, once you put focus on the overflow '...' you can't go back up

### PR DESCRIPTION
**Pull request by joschect**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #8706
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Buttons would prevent keyDown events from propagating when they had focus, they should only do that if they are in a state that has a menu that should be focused.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/8741)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 1]
```diff
@@ -677,15 +677,15 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
...
-      ev.preventDefault();
-      ev.stopPropagation();
+      const state = this.state;
+      // This should be done in the setStateCallback but because preventDefault
+      // needs to be called, we have to evaluate the current state, even though
+      // it might not be 100% accurate;
+      if (state.menuProps && !state.menuProps.shouldFocusOnMount) {
+        ev.preventDefault();
+        ev.stopPropagation();
+        this.setState({ menuProps: { ...state.menuProps, shouldFocusOnMount: true } });
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: Checking state directly for acting is consistent, but might want to use the `setState((state) =>{ menuProps: ...state.menuProps, shouldFocusOnMount: true } }` to make sure we don't overwrite any pending state writes.

Comment (khmakoto) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: I agree with Jason, once that's changed I'll approve the PR 😄

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: My only concern with that is that there can then be disconnect between preventing default and the current state, although that's pretty unlikely. I'll make the change.

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx [hunk 2]
```diff
@@ -677,14 +677,19 @@ export class BaseButton extends BaseComponent<IBaseButtonProps, IBaseButtonState
     }
 
     if (!(ev.altKey || ev.metaKey) && (isUp || isDown)) {
-      const state = this.state;
+      this.setState(state => {
+        if (state.menuProps && !state.menuProps.shouldFocusOnMount) {
+          return { menuProps: { ...state.menuProps, shouldFocusOnMount: true } };
+        }
+        return state;
+      });
```
Comment (JasonGore) [inline packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: I thought this would just be in the same location (line 687) without the `if` check. Did you have to move it?

Comment (joschect) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: I'm a bit confused, it looks like it is in the same location. Which bit of code are you talking about?

**Comment by joschect** [comment]
@khmakoto I think that this is ready to go!

File: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx (hunk 2 above)
Comment (JasonGore) [reply packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx]: It's a bit more apparent if you look at the [commit](https://github.com/OfficeDev/office-ui-fabric-react/pull/8741/commits/bb3dc9ac5f333ccee2861cd81f20c53d94d1311c). Just wanted to check on the reasoning for moving it down then back up.

**Comment by khmakoto** [comment]
@msft-github-bot request review from @JasonGore

**Comment by joschect** [comment]
Spoke with @JasonGore about it, he was fine with this change.
