### PR TITLE
Fix SpinButton's resetting behavior when used as an uncontrolled component

### LINKED ISSUE #7824: SpinButton: keeps resetting when used as uncontrolled component.
https://codepen.io/dzearing/pen/exzyMm?editors=1011

#### Actual behavior:
 
SpinButton can't be used as an uncontrolled component.

1. It keeps resetting on a re-render of the parent.
2. It does not have a "value" getter to read the current value.
 
#### Expected behavior:
 
1. It does not reset value on a re-render of the parent.
2. You can read the value at any time.

Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) High

### PR DESCRIPTION
**Pull request by aneeshack4**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #7824 
- [x] Include a change request file using `$ npm run change`

#### Description of changes

Rendering SpinButton has no props. So newProps is an empty objects and as a result, newProps.value is undefined. When this happens, in componentWillReceiveProps, the conditional statement evaluates to newProps.min (which is 0) and overrides the state value with 0. We can avoid this if we only update the value in setState if newProps.value is not undefined.

#### Focus areas to test

In order to get a local repro of the bug, we had to write a temporary basic componentDidMount() method in SpinButon.Basic.Example.tsx (commented out all the other examples in SpinButton,doc.tsx) because before, componentWillReceiveProps() wasn't being hit and instead, we were going straight from setState() to render(), skipping componentWillReceiveProps(). Calling setState() in this componentDidMount() let us trigger an extra rendering.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/7850)

### CODE REVIEW

**Comment by aneeshack4** [comment]
Azure Dev Ops says "The build was manually deleted" not sure what this means...

**Comment by leddie24** [comment]
@aneeshack4  looks like there's a TSLint error here:

react/src/components/SpinButton/SpinButton.tsx:102:24
ERROR: 102:24  triple-equals  != should be !==

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 1]
```diff
@@ -99,10 +99,12 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
       value = String(Math.max(newProps.min as number, Math.min(newProps.max as number, Number(newProps.defaultValue))));
     }
 
-    this.setState({
-      value: value,
-      precision: newProps.precision || this.state.precision
-    });
+    if (newProps.value !== undefined) {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: could you make a unit test? otherwise seems reasonable.

File: common/changes/office-ui-fabric-react/spinbutton_fix_Reset_2019-01-30-18-37.json [hunk 2]
```diff
@@ -0,0 +1,11 @@
+{
+  "changes": [
+    {
+      "packageName": "office-ui-fabric-react",
+      "comment": "Only update value in state if newProps.value is not undefined",
```
Comment (KevinTCoughlin) [inline common/changes/office-ui-fabric-react/spinbutton_fix_Reset_2019-01-30-18-37.json]:
```suggestion
     "comment": "SpinButton: Only update value in state if newProps.value is defined",
```

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx (hunk 1 above)
Comment (KevinTCoughlin) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: 👍 to a unit test please -- reach out if you need help with setup

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 3]
```diff
@@ -99,10 +99,12 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
...
+      this.setState({
+        value: value,
+        precision: newProps.precision || this.state.precision
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: In theory, precision should be updated even if value is undefined. (Also, the || check won't work right if the new precision is 0.)

Comment (ecraig12345) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Actually precision shouldn't be in the state at all (since state shouldn't be used to cache calculations)... It would be more appropriate to remove precision from the state and replace all usage with calls to a function like this. The function is memoized so it will only run the calculation once per combination of precision and step values.

```ts
const _getPrecision = memoizeFunction((precision: number| undefined, step: number | undefined): number => {
  if (typeof precision === 'number') {
    return precision;
  }
  // Ensure that the autocalculated precision is not negative.
  return Math.max(calculatePrecision(step!), 0);
});
```

Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: done.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx [hunk 4]
```diff
@@ -3,16 +3,31 @@ import * as React from 'react';
...
+    resetIds();
+  });
+
   it('renders SpinButton correctly', () => {
     const component = renderer.create(<SpinButton label="label" />);
     const tree = component.toJSON();
     expect(tree).toMatchSnapshot();
   });
 
+  it('renders SpinButton correctly and value should change accordingly even when no props are defined', () => {
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx]: Bit more to the point :)
```suggestion
  it('allows value updates when no props are defined', () => {
```

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx [hunk 5]
```diff
@@ -3,16 +3,31 @@ import * as React from 'react';
...
+    const renderedDOM: HTMLElement = renderIntoDocument(<SpinButton label="label" />);
+    // Assert on the input element.
+    const inputDOM: HTMLInputElement = renderedDOM.getElementsByTagName('input')[0];
+
+    ReactTestUtils.Simulate.keyDown(inputDOM, {
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx]: Ideally you should also verify that the SpinButton's `value` property is updated properly.
```
const ref = React.createRef<SpinButton>();
/*when rendering*/ <SpinButton componentRef={ref}/>
// after key event
expect(ref.current!.value).toEqual('1');
```

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 6]
```diff
@@ -73,13 +69,12 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
     this._lastValidValue = value;
 
     // Ensure that the autocalculated precision is not negative.
-    const precision = props.precision || Math.max(calculatePrecision(props.step!), 0);
+    this._precision = props.precision || Math.max(calculatePrecision(props.step!), 0);
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Ideally the precision calculation should be done in a helper function so it's not duplicated (and slightly different) between the constructor and componentWillReceiveProps. Also, the helper ought to do a check for precision being of type number (not just a truthy/falsey check) so it correctly detects a specified precision of 0.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx (hunk 4 above)
Comment (dzearing) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx]: When writing "it" descriptions, read it by appending it to the thing you're describing. In this case, here's why it's awkward:

`SpinButton renders SpinButton correctly and value should change...`

And why @ecraig12345 suggestion reads better:

`SpinButton allows value updates when no props are defined`

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx (hunk 5 above)
Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.test.tsx]: Isn't this being done with: (because it's right after keydown that I'm checking the value)
```
     ReactTestUtils.Simulate.keyDown(inputDOM, {
      which: KeyCodes.up
    });
    expect(inputDOM.value).toEqual('1');
```

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx (hunk 6 above)
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Please avoid the use of `!`! Do a type guard or otherwise, add comments in every place you use `!` to justify this usage.

`!` usages spread like a virus through codebases and it soon becomes impossible to reason about the correctness of the code.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 7]
```diff
@@ -277,6 +275,15 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
     }
   };
 
+  private _calculatePrecision = (props: ISpinButtonProps) => {
+    if (props.step) {
+      const { precision = Math.max(calculatePrecision(props.step!), 0) } = props;
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: `!` no longer necessary

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx (hunk 6 above)
Comment (micahgodbolt) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: @aneeshack4 is this resolved? I see the code is changed, but '!' appear to still be present.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx (hunk 7 above)
Comment (cliffkoh) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Actually best to fix the typings

Add something like 
```ts
public props: ISpinButtonProps & Required<Pick<ISpinButtonProps, 'step' | 'min'>>
```

into the class declaration and it should allow you to remove all usages of `!` operator

Comment (cliffkoh) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]:
```ts
type DefaultProps = Required<Pick<ISpinButtonProps, 'step' | 'min' | ... >>;
static defaultProps: DefaultProps =  {
    step: 1,
    min: 0,
    max: 100,
    disabled: false,
    labelPosition: Position.start,
    label: '',
    incrementButtonIcon: { iconName: 'ChevronUpSmall' },
    decrementButtonIcon: { iconName: 'ChevronDownSmall' }
  };

  public props: ISpinButtonProps & DefaultProps;
```

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 8]
```diff
@@ -31,16 +31,15 @@ export interface ISpinButtonState {
...
-   */
-  precision: number;
 }
 
+export type DefaultProps = Required<
+  Pick<ISpinButtonProps, 'step' | 'min' | 'max' | 'disabled' | 'labelPosition' | 'label' | 'incrementButtonIcon' | 'decrementButtonIcon'>
+>;
+
 @customizable('SpinButton', ['theme', 'styles'], true)
 export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState> implements ISpinButton {
```
Comment (ecraig12345) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: I'm guessing if you add `public props: ISpinButtonProps & DefaultProps` it would remove the need for the explicit conversions to that type everywhere else.

Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: When I tried this, it broke a bunch of things like all the examples because it makes all these props required for all the users.

Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: I spoke with Cliff & Katherine about this & ended up with having to just do this.props as ISpinButtonProps & DefaultProps for every instance of this.props

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 9]
```diff
@@ -300,8 +308,9 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
    * Increment function to use if one is not passed in
    */
   private _defaultOnIncrement = (value: string): string | void => {
-    let newValue: number = Math.min(Number(value) + Number(this.props.step)!, this.props.max!);
-    newValue = precisionRound(newValue, this.state.precision);
+    const props = this.props as ISpinButtonProps & DefaultProps;
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: const { max, steps } = this.props as ISpinnButtonProps & DefaultProps

then you don't need the `!` use in line 312

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 10]
```diff
@@ -317,8 +326,9 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
    * Increment function to use if one is not passed in
    */
   private _defaultOnDecrement = (value: string): string | void => {
-    let newValue: number = Math.max(Number(value) - Number(this.props.step)!, this.props.min!);
-    newValue = precisionRound(newValue, this.state.precision);
+    const props = this.props as ISpinButtonProps & DefaultProps;
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: same as above

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 11]
```diff
@@ -99,10 +99,13 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
...
-      value: value,
-      precision: newProps.precision || this.state.precision
-    });
+    if (newProps.value !== undefined) {
+      this.setState({
+        value: value
+      });
+    }
+    const propsForPrecision = newProps as ISpinButtonProps & DefaultProps;
+    this._precision = this._calculatePrecision(propsForPrecision);
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: i would just do `calculatePrecision(newProps as ...)` without having `propsForPrecision`

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 12]
```diff
@@ -277,6 +280,11 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
     }
   };
 
+  private _calculatePrecision = (props: ISpinButtonProps & DefaultProps) => {
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: non-blocking suggestion, but you can consider aliasing `ISpinButtonProps & DefaultProps` to something like `ISpinButtonInternalProps` so you don't have to type `ISpinButton & DefaultProps` over and over again

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 13]
```diff
@@ -37,6 +37,9 @@ export type DefaultProps = Required<
   Pick<ISpinButtonProps, 'step' | 'min' | 'max' | 'disabled' | 'labelPosition' | 'label' | 'incrementButtonIcon' | 'decrementButtonIcon'>
 >;
 
+/** Internal only props */
+export type ISpinButtonInternalProps = ISpinButtonProps & DefaultProps;
```
Comment (cliffkoh) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: does this error if you don't export? the type is only used within the function for casts

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 14]
```diff
@@ -31,16 +31,18 @@ export interface ISpinButtonState {
...
+  Pick<ISpinButtonProps, 'step' | 'min' | 'max' | 'disabled' | 'labelPosition' | 'label' | 'incrementButtonIcon' | 'decrementButtonIcon'>
+>;
+
+/** Internal only props */
+type ISpinButtonInternalProps = ISpinButtonProps & DefaultProps;
+
 @customizable('SpinButton', ['theme', 'styles'], true)
 export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState> implements ISpinButton {
-  public static defaultProps: ISpinButtonProps = {
+  public static defaultProps: DefaultProps = {
```
Comment (dzearing) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: don't understand this. What is this change for?

Comment (aneeshack4) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Had to create a separate DefaultProps that makes the optional props required within the class itself. All of this helped me get rid of the if/else undefined checks & the constant this.props usage.
