### PR TITLE
Fixes the fabric-website deployment baseCDNUrl

### LINKED ISSUE #9121: fabric docs website broken
### Environment Information 
 
- __Package version(s)__: NA
- __Browser and OS versions__: Chrome and Firefox desktop

#### Actual behavior:
 
- Docs website not loading completely
 
#### Expected behavior:
 
docs website should load completely

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: High
 
Products/sites affected: https://developer.microsoft.com/en-us/fabric
 
```txt
# Errors on console

fabric:624 GET https://developer.microsoft.com/en-us/fabricweb.azureedge.net/fabric-website/20190516.1/fabric-sitev5.min.js

Cross-Origin Read Blocking (CORB) blocked cross-origin response https://web.vortex.data.microsoft.com/collect/v1?$mscomCookies=false&ext-javascript-msfpc=%27GUID%3D2a2b33418000499d9f4f4b1495b33fb4%26HASH%3D2a2b%26LV%3D201905%26V%3D4%26LU%3D1558011872813%27 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
```

### PR DESCRIPTION
**Pull request by kenotron**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #9121
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

There was an issue with the fabric baseCDNUrl that came up where the `path.join` ate one of the `/`'s

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/9123)

### CODE REVIEW

File: apps/fabric-website/scripts/createFlightConfig.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ module.exports.createPublicFlightConfigTask = function() {
 
     let configData = {
       version: process.env.BUILD_BUILDNUMBER || '0',
-      baseCDNUrl: path.join(argv().baseCDNUrl, process.env.BUILD_BUILDNUMBER) + '/',
+      baseCDNUrl: argv().baseCDNUrl,
```
Comment (ecraig12345) [inline apps/fabric-website/scripts/createFlightConfig.js]: It seems safer to continue appending the build number here, just do it manually not with path.join().

Comment (kenotron) [reply apps/fabric-website/scripts/createFlightConfig.js]: I want to have symmetry with the other baseCDNUrl option for internal manifest generator. Will just have this be provided by the outside yaml.
