### PR TITLE
Remove ms-high-contrast-adjust:none from fabric styles

### LINKED ISSUE #1935: High contrast mode doesn't seem to work on dev boxes
### Bug Report

- __Package version(s)__: master branch
- __Browser and OS versions__: IE 11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes... eventually

Requested priority: Normal

Products/sites affected: n/a

#### Describe the issue:

Developing high contrast scenarios is harder as running "npm start" on a dev box results in a website that seems to have issues. Here is the side by side of what I see on my dev box vs dev.office.com/fabric 
untitled

#### Actual behavior:

See image

#### Expected behavior:

For both sites to have the same colors

### PR DESCRIPTION
**Pull request by mdahamiwal**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #1935 
- [x] Include a change request file using `$ npm run change`

#### Description of changes
We don't need high contrast just on everything, or it will cause entire site to render in normal mode. This attribute should be used as necessary on specific element where we handle full high contrast theme.

#### Focus areas to test

(optional)

### CODE REVIEW

File: packages/styling/src/styles/DefaultFontStyles.ts [hunk 1]
```diff
@@ -130,7 +130,6 @@ function _createFont(size: string, weight: number): IRawStyle {
   return {
     fontFamily: _getFontFamily(),
     MozOsxFontSmoothing: 'grayscale',
-    MsHighContrastAdjust: 'none',
```
Comment (dzearing) [inline packages/styling/src/styles/DefaultFontStyles.ts]: @mikewheaton I believe these styles were taken directly from fabric core. Is this removal OK?

Comment (mikewheaton) [inline packages/styling/src/styles/DefaultFontStyles.ts]: It was removed for Fabric Core 7.1.0 in [this PR](https://github.com/OfficeDev/office-ui-fabric-core/pull/988) so, yes, it should be removed from the Styling package as well.
