### PR TITLE
Autofill autocomplete

### LINKED ISSUE #11403: Cannot override autocomplete in PeoplePicker
### Environment Information

- **Package version(s)**: 6.195.6
- **Browser and OS versions**: Chrome Version 78.0.3904.108 (Official Build) (64-bit)

### Bug Description:

The autocomplete attribute is set to "off" in the PeoplePicker, but Chrome ignores it and overlays its own autofill picker in some cases. See this [stack overflow post](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill). 

We want to override the inputProps attribute for autoComplete to be set to "no", but it does not seem to work: https://codepen.io/dliu120/pen/GRgJoJL (see line 74)

There is a similar issue here [#10376](https://github.com/OfficeDev/office-ui-fabric-react/issues/10376) that was closed due to inactivity. 

#### Actual behavior:

image

#### Expected behavior:

image

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected:  https://flow.microsoft.com

Notes: We have a workaround, but it's not ideal. We manually patch the input's autocomplete attribute after the component renders.

### PR DESCRIPTION
**Pull request by micahgodbolt**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #11403

#### Description of changes

Backport of #11409

Moved autoCapitalize (and other static values) above the nativeInput props to allow those values to be overriden.

#### Focus areas to test

(optional)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/OfficeDev/office-ui-fabric-react/pull/11424)

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx [hunk 1]
```diff
@@ -911,9 +908,6 @@ export class BasePickerListBelow<T, P extends IBasePickerProps<T>> extends BaseP
               suggestedDisplayValue={suggestedDisplayValue}
               aria-activedescendant={this.getActiveDescendant()}
               aria-expanded={!!this.state.suggestionsVisible}
-              aria-haspopup="true"
-              autoCapitalize="off"
-              autoComplete="off"
```
Comment (micahgodbolt) [inline packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx]: values already specified in Autofill
