### PR TITLE
Addressing Issue #3776 - Sticky component loops forever if background-color is not set for page

### LINKED ISSUE #3776: Sticky component loops forever if background-color is not set for page
### Bug Report

- __Package version(s)__: 5.37.0
- __Browser and OS versions__: NA

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority:  Normal

Products/sites affected: (if applicable)

#### Describe the issue:

Sticky component loops forever if background-color is not set for page

#### Actual behavior:

This loop in _getBackground() never exits

while (window.getComputedStyle(curr).getPropertyValue('background-color') === 'rgba(0, 0, 0, 0)' ||
      window.getComputedStyle(curr).getPropertyValue('background-color') === 'transparent') {
      if (curr.parentElement) {
        curr = curr.parentElement;
      }
    }

#### Expected behavior:

Should check for curr == html and return

### PR DESCRIPTION
**Pull request by oengusmacinog**
#### Pull request checklist

- [ ] Addresses an existing issue: Fixes #3776
- [ ] Include a change request file using `$ npm run change`

#### Description of changes

added return default when reaching the html tag in while loop inside _getBackground() inside Sticky component

#### Focus areas to test

N/A

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx [hunk 1]
```diff
@@ -176,6 +176,10 @@ export class Sticky extends BaseComponent<IStickyProps, IStickyState> {
     let curr = this.refs.root;
     while (window.getComputedStyle(curr).getPropertyValue('background-color') === 'rgba(0, 0, 0, 0)' ||
       window.getComputedStyle(curr).getPropertyValue('background-color') === 'transparent') {
+      if (curr.tagName === 'HTML') {
+        // Fallback color if no element has a declared background-color attribute
+        return 'rgba(244, 244, 244, 1)';
```
Comment (battletoilet) [inline packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx]: We should just use `return;` instead of returning a hard-coded value.

Comment (oengusmacinog) [reply packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx]: It does need some fallback value since without one it defaults to transparent:

transparent-sticky

I'm updating to assign it outside the function. Let me know your thoughts on the updated solution.

File: packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx [hunk 2]
```diff
@@ -64,7 +64,7 @@ export class Sticky extends BaseComponent<IStickyProps, IStickyState> {
     const { scrollablePane } = this.context;
     scrollablePane.subscribe(this._onScrollEvent);
     this.content = document.createElement('div');
-    this.content.style.background = this._getBackground();
+    this.content.style.background = this._getBackground() || 'rgba(244, 244, 244, 1)';
     ReactDOM.render(<div>{ this.props.children }</div>, this.content);
```
Comment (battletoilet) [inline packages/office-ui-fabric-react/src/components/Sticky/Sticky.tsx]: Lets make this value a prop that the consumer can choose.
