### PR TITLE
[SpinButton] Fix floating point rounding issues and implemented precision

### LINKED ISSUE #3339: SpinButton has rounding issues for steps with decimal places
### Bug Report

- __Package version(s)__:
  - office-ui-fabric-react: 5.20.0
  - react: 16.0.0
  - react-dom: 16.0.0
- __Browser and OS versions__: Chrome Version 62.0.3202.62 / Windows 10 Pro Version 1703

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

Using a SpinButton and setting the step prop to a number with decimal places (e.g. 0.1 or 1.3) causes rounding errors due to floating point math.

I propose adding a new `precision` prop to SpinButton. Its value is then utilized using `Number.prototype.toFixed` to round the value to the desired precision. This solution worked for me where I use a SpinButton and provide custom `onIncrement/onDecrement` handlers.

#### Actual behavior:

Rendering a SpinButton with a step of 0.1 and a defaultValue of 0, clicking the increment button thrice results in an output of `0.30000000000000004`.

#### Expected behavior:

Rendering a SpinButton with a step of 0.1 and a defaultValue of 0, clicking the increment button thrice results in an output of `0.3`.

### If applicable, please provide a codepen repro:

CodeSandbox instead of codepen, but does the same job:

https://codesandbox.io/s/0ook2q68xl

### PR DESCRIPTION
**Pull request by lambertwang**
#### Pull request checklist

- [x] Addresses an existing issue: Fixes #3339
- [x] Include a change request file using `$ npm run change`

#### Description of changes

SpinButton will now round with a degree of precision calculated based on the input step value or a user-defined value.

### CODE REVIEW

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 1]
```diff
@@ -40,6 +40,45 @@ export interface ISpinButtonState {
...
+  }
+  return 0;
+}
+
+/**
+ *
+ * @param value The value that is being rounded.
+ * @param precision The number of decimal places to round the number to
+ */
+export function precisionRound(value: number, precision: number, base: number = 10): number {
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: This should definitely be a utility function.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 2]
```diff
@@ -40,6 +40,45 @@ export interface ISpinButtonState {
...
+  const exp = Math.pow(base, precision);
+  return Math.round(value * exp) / exp;
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: Why not just do `return value.toFixed(precision));` toFixed will round decimals for you and even returns as a string.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts [hunk 3]
```diff
@@ -165,6 +167,13 @@ export interface ISpinButtonProps {
    * Accessibility label text for the decrement button for the benefit of the screen reader.
    */
   decrementButtonAriaLabel?: string;
+
+  /**
+   * To how many decimal places the value should be rounded to.
+   * The default value is calculated based on the precision of step.
+   * IE: if step = 1, precision = 0. step = 0.0089, precision = 4. step = 300, precision = 2. step = 23.00, precision = 2.
+   */
+  precision?: number;
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts]: ITT either have this, or make step accept a string, but don't do both. It might make the most sense that step can just be used for precision but then again you have no way to check and make sure that the string I entered is valid.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx (hunk 2 above)
Comment (lambertwang) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: toFixed doesn't support negative precision.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts (hunk 3 above)
Comment (lambertwang) [reply packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts]: If you want step to be 200 and precision to be -1, there is no way to pass step as a string and satisfy that.

File: packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx [hunk 4]
```diff
@@ -80,10 +87,14 @@ export class SpinButton extends BaseComponent<ISpinButtonProps, ISpinButtonState
     let value = props.value || props.defaultValue || String(props.min) || '0';
     this._lastValidValue = value;
 
+    // Ensure that the autocalculated precision is not negative.
+    const precision = props.precision || Math.max(calculatePrecision(props.step || SpinButton.defaultProps.step!), 0);
```
Comment (joschect) [inline packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx]: just do this.props.precision and `this.props.step` so you don't need to reference the default props directly. `this.props` will get set in super(props) so you can use it immediately afterwards and it will handle the default for you.
